linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gosec
    - goconst
    - gocyclo
    - dupl

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocyclo:
    min-complexity: 15
  
  gosec:
    excludes:
      - G104  # Audit errors not checked (we handle explicitly)
  
  dupl:
    threshold: 100

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - docs
    - scripts

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
    
    # Exclude some linters from migrations
    - path: migrations/
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
