with-expecter: true
dir: "mocks"
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.PackageName}}_{{.InterfaceName | snakecase}}.go"
outpkg: "mocks"
packages:
  github.com/osse101/BrandishBot_Go/internal/user:
    interfaces:
      Service:
      Repository:
      JobService:
  github.com/osse101/BrandishBot_Go/internal/economy:
    interfaces:
      Service:
      Repository:
      JobService:
  github.com/osse101/BrandishBot_Go/internal/progression:
    interfaces:
      Service:
      Repository:
  github.com/osse101/BrandishBot_Go/internal/eventlog:
    interfaces:
      Service:
      Repository:
  github.com/osse101/BrandishBot_Go/internal/linking:
    interfaces:
      Service:
      Repository:
      UserService:
  github.com/osse101/BrandishBot_Go/internal/stats:
    interfaces:
      Service:
      Repository:
  github.com/osse101/BrandishBot_Go/internal/gamble:
    interfaces:
      Service:
      Repository:
      JobService:
  github.com/osse101/BrandishBot_Go/internal/lootbox:
    interfaces:
      Service:
      ItemRepository:
  github.com/osse101/BrandishBot_Go/internal/job:
    interfaces:
      Service:
      Repository:
      ProgressionService:
  github.com/osse101/BrandishBot_Go/internal/crafting:
    interfaces:
      Service:
      Repository:
      JobService:
  github.com/osse101/BrandishBot_Go/internal/cooldown:
    interfaces:
      Service:
  github.com/osse101/BrandishBot_Go/internal/event:
    interfaces:
      Bus:
  github.com/osse101/BrandishBot_Go/internal/database:
    interfaces:
      Pool:
  github.com/osse101/BrandishBot_Go/internal/repository:
    interfaces:
      Tx:
      GambleTx:
  github.com/osse101/BrandishBot_Go/internal/naming:
    interfaces:
      Resolver:
  github.com/osse101/BrandishBot_Go/internal/handler:
    interfaces:
      HealthChecker:
  github.com/osse101/BrandishBot_Go/internal/worker:
    interfaces:
      Job:
