// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetEventCounts provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockRepository) GetEventCounts(ctx context.Context, startTime time.Time, endTime time.Time) (map[domain.EventType]int, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetEventCounts")
	}

	var r0 map[domain.EventType]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (map[domain.EventType]int, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) map[domain.EventType]int); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.EventType]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetEventCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventCounts'
type MockRepository_GetEventCounts_Call struct {
	*mock.Call
}

// GetEventCounts is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockRepository_Expecter) GetEventCounts(ctx interface{}, startTime interface{}, endTime interface{}) *MockRepository_GetEventCounts_Call {
	return &MockRepository_GetEventCounts_Call{Call: _e.mock.On("GetEventCounts", ctx, startTime, endTime)}
}

func (_c *MockRepository_GetEventCounts_Call) Run(run func(ctx context.Context, startTime time.Time, endTime time.Time)) *MockRepository_GetEventCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_GetEventCounts_Call) Return(_a0 map[domain.EventType]int, _a1 error) *MockRepository_GetEventCounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetEventCounts_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (map[domain.EventType]int, error)) *MockRepository_GetEventCounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsByType provides a mock function with given fields: ctx, eventType, startTime, endTime
func (_m *MockRepository) GetEventsByType(ctx context.Context, eventType domain.EventType, startTime time.Time, endTime time.Time) ([]domain.StatsEvent, error) {
	ret := _m.Called(ctx, eventType, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByType")
	}

	var r0 []domain.StatsEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.EventType, time.Time, time.Time) ([]domain.StatsEvent, error)); ok {
		return rf(ctx, eventType, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.EventType, time.Time, time.Time) []domain.StatsEvent); ok {
		r0 = rf(ctx, eventType, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StatsEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.EventType, time.Time, time.Time) error); ok {
		r1 = rf(ctx, eventType, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetEventsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsByType'
type MockRepository_GetEventsByType_Call struct {
	*mock.Call
}

// GetEventsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType domain.EventType
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockRepository_Expecter) GetEventsByType(ctx interface{}, eventType interface{}, startTime interface{}, endTime interface{}) *MockRepository_GetEventsByType_Call {
	return &MockRepository_GetEventsByType_Call{Call: _e.mock.On("GetEventsByType", ctx, eventType, startTime, endTime)}
}

func (_c *MockRepository_GetEventsByType_Call) Run(run func(ctx context.Context, eventType domain.EventType, startTime time.Time, endTime time.Time)) *MockRepository_GetEventsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.EventType), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_GetEventsByType_Call) Return(_a0 []domain.StatsEvent, _a1 error) *MockRepository_GetEventsByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetEventsByType_Call) RunAndReturn(run func(context.Context, domain.EventType, time.Time, time.Time) ([]domain.StatsEvent, error)) *MockRepository_GetEventsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsByUser provides a mock function with given fields: ctx, userID, startTime, endTime
func (_m *MockRepository) GetEventsByUser(ctx context.Context, userID string, startTime time.Time, endTime time.Time) ([]domain.StatsEvent, error) {
	ret := _m.Called(ctx, userID, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByUser")
	}

	var r0 []domain.StatsEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]domain.StatsEvent, error)); ok {
		return rf(ctx, userID, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []domain.StatsEvent); ok {
		r0 = rf(ctx, userID, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StatsEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetEventsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsByUser'
type MockRepository_GetEventsByUser_Call struct {
	*mock.Call
}

// GetEventsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockRepository_Expecter) GetEventsByUser(ctx interface{}, userID interface{}, startTime interface{}, endTime interface{}) *MockRepository_GetEventsByUser_Call {
	return &MockRepository_GetEventsByUser_Call{Call: _e.mock.On("GetEventsByUser", ctx, userID, startTime, endTime)}
}

func (_c *MockRepository_GetEventsByUser_Call) Run(run func(ctx context.Context, userID string, startTime time.Time, endTime time.Time)) *MockRepository_GetEventsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_GetEventsByUser_Call) Return(_a0 []domain.StatsEvent, _a1 error) *MockRepository_GetEventsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetEventsByUser_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]domain.StatsEvent, error)) *MockRepository_GetEventsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopUsers provides a mock function with given fields: ctx, eventType, startTime, endTime, limit
func (_m *MockRepository) GetTopUsers(ctx context.Context, eventType domain.EventType, startTime time.Time, endTime time.Time, limit int) ([]domain.LeaderboardEntry, error) {
	ret := _m.Called(ctx, eventType, startTime, endTime, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopUsers")
	}

	var r0 []domain.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.EventType, time.Time, time.Time, int) ([]domain.LeaderboardEntry, error)); ok {
		return rf(ctx, eventType, startTime, endTime, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.EventType, time.Time, time.Time, int) []domain.LeaderboardEntry); ok {
		r0 = rf(ctx, eventType, startTime, endTime, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.EventType, time.Time, time.Time, int) error); ok {
		r1 = rf(ctx, eventType, startTime, endTime, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTopUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopUsers'
type MockRepository_GetTopUsers_Call struct {
	*mock.Call
}

// GetTopUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType domain.EventType
//   - startTime time.Time
//   - endTime time.Time
//   - limit int
func (_e *MockRepository_Expecter) GetTopUsers(ctx interface{}, eventType interface{}, startTime interface{}, endTime interface{}, limit interface{}) *MockRepository_GetTopUsers_Call {
	return &MockRepository_GetTopUsers_Call{Call: _e.mock.On("GetTopUsers", ctx, eventType, startTime, endTime, limit)}
}

func (_c *MockRepository_GetTopUsers_Call) Run(run func(ctx context.Context, eventType domain.EventType, startTime time.Time, endTime time.Time, limit int)) *MockRepository_GetTopUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.EventType), args[2].(time.Time), args[3].(time.Time), args[4].(int))
	})
	return _c
}

func (_c *MockRepository_GetTopUsers_Call) Return(_a0 []domain.LeaderboardEntry, _a1 error) *MockRepository_GetTopUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTopUsers_Call) RunAndReturn(run func(context.Context, domain.EventType, time.Time, time.Time, int) ([]domain.LeaderboardEntry, error)) *MockRepository_GetTopUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalEventCount provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockRepository) GetTotalEventCount(ctx context.Context, startTime time.Time, endTime time.Time) (int, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalEventCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (int, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) int); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTotalEventCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalEventCount'
type MockRepository_GetTotalEventCount_Call struct {
	*mock.Call
}

// GetTotalEventCount is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockRepository_Expecter) GetTotalEventCount(ctx interface{}, startTime interface{}, endTime interface{}) *MockRepository_GetTotalEventCount_Call {
	return &MockRepository_GetTotalEventCount_Call{Call: _e.mock.On("GetTotalEventCount", ctx, startTime, endTime)}
}

func (_c *MockRepository_GetTotalEventCount_Call) Run(run func(ctx context.Context, startTime time.Time, endTime time.Time)) *MockRepository_GetTotalEventCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_GetTotalEventCount_Call) Return(_a0 int, _a1 error) *MockRepository_GetTotalEventCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTotalEventCount_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (int, error)) *MockRepository_GetTotalEventCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserEventCounts provides a mock function with given fields: ctx, userID, startTime, endTime
func (_m *MockRepository) GetUserEventCounts(ctx context.Context, userID string, startTime time.Time, endTime time.Time) (map[domain.EventType]int, error) {
	ret := _m.Called(ctx, userID, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetUserEventCounts")
	}

	var r0 map[domain.EventType]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (map[domain.EventType]int, error)); ok {
		return rf(ctx, userID, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) map[domain.EventType]int); ok {
		r0 = rf(ctx, userID, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.EventType]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserEventCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserEventCounts'
type MockRepository_GetUserEventCounts_Call struct {
	*mock.Call
}

// GetUserEventCounts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockRepository_Expecter) GetUserEventCounts(ctx interface{}, userID interface{}, startTime interface{}, endTime interface{}) *MockRepository_GetUserEventCounts_Call {
	return &MockRepository_GetUserEventCounts_Call{Call: _e.mock.On("GetUserEventCounts", ctx, userID, startTime, endTime)}
}

func (_c *MockRepository_GetUserEventCounts_Call) Run(run func(ctx context.Context, userID string, startTime time.Time, endTime time.Time)) *MockRepository_GetUserEventCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_GetUserEventCounts_Call) Return(_a0 map[domain.EventType]int, _a1 error) *MockRepository_GetUserEventCounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserEventCounts_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) (map[domain.EventType]int, error)) *MockRepository_GetUserEventCounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserEventsByType provides a mock function with given fields: ctx, userID, eventType, limit
func (_m *MockRepository) GetUserEventsByType(ctx context.Context, userID string, eventType domain.EventType, limit int) ([]domain.StatsEvent, error) {
	ret := _m.Called(ctx, userID, eventType, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUserEventsByType")
	}

	var r0 []domain.StatsEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.EventType, int) ([]domain.StatsEvent, error)); ok {
		return rf(ctx, userID, eventType, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.EventType, int) []domain.StatsEvent); ok {
		r0 = rf(ctx, userID, eventType, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StatsEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.EventType, int) error); ok {
		r1 = rf(ctx, userID, eventType, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserEventsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserEventsByType'
type MockRepository_GetUserEventsByType_Call struct {
	*mock.Call
}

// GetUserEventsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - eventType domain.EventType
//   - limit int
func (_e *MockRepository_Expecter) GetUserEventsByType(ctx interface{}, userID interface{}, eventType interface{}, limit interface{}) *MockRepository_GetUserEventsByType_Call {
	return &MockRepository_GetUserEventsByType_Call{Call: _e.mock.On("GetUserEventsByType", ctx, userID, eventType, limit)}
}

func (_c *MockRepository_GetUserEventsByType_Call) Run(run func(ctx context.Context, userID string, eventType domain.EventType, limit int)) *MockRepository_GetUserEventsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.EventType), args[3].(int))
	})
	return _c
}

func (_c *MockRepository_GetUserEventsByType_Call) Return(_a0 []domain.StatsEvent, _a1 error) *MockRepository_GetUserEventsByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserEventsByType_Call) RunAndReturn(run func(context.Context, string, domain.EventType, int) ([]domain.StatsEvent, error)) *MockRepository_GetUserEventsByType_Call {
	_c.Call.Return(run)
	return _c
}

// RecordEvent provides a mock function with given fields: ctx, event
func (_m *MockRepository) RecordEvent(ctx context.Context, event *domain.StatsEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for RecordEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StatsEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RecordEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordEvent'
type MockRepository_RecordEvent_Call struct {
	*mock.Call
}

// RecordEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *domain.StatsEvent
func (_e *MockRepository_Expecter) RecordEvent(ctx interface{}, event interface{}) *MockRepository_RecordEvent_Call {
	return &MockRepository_RecordEvent_Call{Call: _e.mock.On("RecordEvent", ctx, event)}
}

func (_c *MockRepository_RecordEvent_Call) Run(run func(ctx context.Context, event *domain.StatsEvent)) *MockRepository_RecordEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.StatsEvent))
	})
	return _c
}

func (_c *MockRepository_RecordEvent_Call) Return(_a0 error) *MockRepository_RecordEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RecordEvent_Call) RunAndReturn(run func(context.Context, *domain.StatsEvent) error) *MockRepository_RecordEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
