// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	crafting "github.com/osse101/BrandishBot_Go/internal/crafting"
	domain "github.com/osse101/BrandishBot_Go/internal/domain"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/osse101/BrandishBot_Go/internal/repository"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx
func (_m *MockRepository) BeginTx(ctx context.Context) (repository.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) BeginTx(ctx interface{}) *MockRepository_BeginTx_Call {
	return &MockRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockRepository_BeginTx_Call) Run(run func(ctx context.Context)) *MockRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_BeginTx_Call) Return(_a0 repository.Tx, _a1 error) *MockRepository_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_BeginTx_Call) RunAndReturn(run func(context.Context) (repository.Tx, error)) *MockRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssociatedUpgradeRecipeID provides a mock function with given fields: ctx, disassembleRecipeID
func (_m *MockRepository) GetAssociatedUpgradeRecipeID(ctx context.Context, disassembleRecipeID int) (int, error) {
	ret := _m.Called(ctx, disassembleRecipeID)

	if len(ret) == 0 {
		panic("no return value specified for GetAssociatedUpgradeRecipeID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, disassembleRecipeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, disassembleRecipeID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, disassembleRecipeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAssociatedUpgradeRecipeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssociatedUpgradeRecipeID'
type MockRepository_GetAssociatedUpgradeRecipeID_Call struct {
	*mock.Call
}

// GetAssociatedUpgradeRecipeID is a helper method to define mock.On call
//   - ctx context.Context
//   - disassembleRecipeID int
func (_e *MockRepository_Expecter) GetAssociatedUpgradeRecipeID(ctx interface{}, disassembleRecipeID interface{}) *MockRepository_GetAssociatedUpgradeRecipeID_Call {
	return &MockRepository_GetAssociatedUpgradeRecipeID_Call{Call: _e.mock.On("GetAssociatedUpgradeRecipeID", ctx, disassembleRecipeID)}
}

func (_c *MockRepository_GetAssociatedUpgradeRecipeID_Call) Run(run func(ctx context.Context, disassembleRecipeID int)) *MockRepository_GetAssociatedUpgradeRecipeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_GetAssociatedUpgradeRecipeID_Call) Return(_a0 int, _a1 error) *MockRepository_GetAssociatedUpgradeRecipeID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAssociatedUpgradeRecipeID_Call) RunAndReturn(run func(context.Context, int) (int, error)) *MockRepository_GetAssociatedUpgradeRecipeID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDisassembleRecipeBySourceItemID provides a mock function with given fields: ctx, itemID
func (_m *MockRepository) GetDisassembleRecipeBySourceItemID(ctx context.Context, itemID int) (*domain.DisassembleRecipe, error) {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetDisassembleRecipeBySourceItemID")
	}

	var r0 *domain.DisassembleRecipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.DisassembleRecipe, error)); ok {
		return rf(ctx, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.DisassembleRecipe); ok {
		r0 = rf(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DisassembleRecipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetDisassembleRecipeBySourceItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDisassembleRecipeBySourceItemID'
type MockRepository_GetDisassembleRecipeBySourceItemID_Call struct {
	*mock.Call
}

// GetDisassembleRecipeBySourceItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID int
func (_e *MockRepository_Expecter) GetDisassembleRecipeBySourceItemID(ctx interface{}, itemID interface{}) *MockRepository_GetDisassembleRecipeBySourceItemID_Call {
	return &MockRepository_GetDisassembleRecipeBySourceItemID_Call{Call: _e.mock.On("GetDisassembleRecipeBySourceItemID", ctx, itemID)}
}

func (_c *MockRepository_GetDisassembleRecipeBySourceItemID_Call) Run(run func(ctx context.Context, itemID int)) *MockRepository_GetDisassembleRecipeBySourceItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_GetDisassembleRecipeBySourceItemID_Call) Return(_a0 *domain.DisassembleRecipe, _a1 error) *MockRepository_GetDisassembleRecipeBySourceItemID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetDisassembleRecipeBySourceItemID_Call) RunAndReturn(run func(context.Context, int) (*domain.DisassembleRecipe, error)) *MockRepository_GetDisassembleRecipeBySourceItemID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInventory provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetInventory(ctx context.Context, userID string) (*domain.Inventory, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 *domain.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Inventory, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Inventory); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventory'
type MockRepository_GetInventory_Call struct {
	*mock.Call
}

// GetInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetInventory(ctx interface{}, userID interface{}) *MockRepository_GetInventory_Call {
	return &MockRepository_GetInventory_Call{Call: _e.mock.On("GetInventory", ctx, userID)}
}

func (_c *MockRepository_GetInventory_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetInventory_Call) Return(_a0 *domain.Inventory, _a1 error) *MockRepository_GetInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetInventory_Call) RunAndReturn(run func(context.Context, string) (*domain.Inventory, error)) *MockRepository_GetInventory_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetItemByID(ctx context.Context, id int) (*domain.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByID'
type MockRepository_GetItemByID_Call struct {
	*mock.Call
}

// GetItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) GetItemByID(ctx interface{}, id interface{}) *MockRepository_GetItemByID_Call {
	return &MockRepository_GetItemByID_Call{Call: _e.mock.On("GetItemByID", ctx, id)}
}

func (_c *MockRepository_GetItemByID_Call) Run(run func(ctx context.Context, id int)) *MockRepository_GetItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_GetItemByID_Call) Return(_a0 *domain.Item, _a1 error) *MockRepository_GetItemByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetItemByID_Call) RunAndReturn(run func(context.Context, int) (*domain.Item, error)) *MockRepository_GetItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByName provides a mock function with given fields: ctx, itemName
func (_m *MockRepository) GetItemByName(ctx context.Context, itemName string) (*domain.Item, error) {
	ret := _m.Called(ctx, itemName)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByName")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Item, error)); ok {
		return rf(ctx, itemName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Item); ok {
		r0 = rf(ctx, itemName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, itemName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetItemByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByName'
type MockRepository_GetItemByName_Call struct {
	*mock.Call
}

// GetItemByName is a helper method to define mock.On call
//   - ctx context.Context
//   - itemName string
func (_e *MockRepository_Expecter) GetItemByName(ctx interface{}, itemName interface{}) *MockRepository_GetItemByName_Call {
	return &MockRepository_GetItemByName_Call{Call: _e.mock.On("GetItemByName", ctx, itemName)}
}

func (_c *MockRepository_GetItemByName_Call) Run(run func(ctx context.Context, itemName string)) *MockRepository_GetItemByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetItemByName_Call) Return(_a0 *domain.Item, _a1 error) *MockRepository_GetItemByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetItemByName_Call) RunAndReturn(run func(context.Context, string) (*domain.Item, error)) *MockRepository_GetItemByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecipeByTargetItemID provides a mock function with given fields: ctx, itemID
func (_m *MockRepository) GetRecipeByTargetItemID(ctx context.Context, itemID int) (*domain.Recipe, error) {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipeByTargetItemID")
	}

	var r0 *domain.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Recipe, error)); ok {
		return rf(ctx, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Recipe); ok {
		r0 = rf(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetRecipeByTargetItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecipeByTargetItemID'
type MockRepository_GetRecipeByTargetItemID_Call struct {
	*mock.Call
}

// GetRecipeByTargetItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID int
func (_e *MockRepository_Expecter) GetRecipeByTargetItemID(ctx interface{}, itemID interface{}) *MockRepository_GetRecipeByTargetItemID_Call {
	return &MockRepository_GetRecipeByTargetItemID_Call{Call: _e.mock.On("GetRecipeByTargetItemID", ctx, itemID)}
}

func (_c *MockRepository_GetRecipeByTargetItemID_Call) Run(run func(ctx context.Context, itemID int)) *MockRepository_GetRecipeByTargetItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_GetRecipeByTargetItemID_Call) Return(_a0 *domain.Recipe, _a1 error) *MockRepository_GetRecipeByTargetItemID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetRecipeByTargetItemID_Call) RunAndReturn(run func(context.Context, int) (*domain.Recipe, error)) *MockRepository_GetRecipeByTargetItemID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnlockedRecipesForUser provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetUnlockedRecipesForUser(ctx context.Context, userID string) ([]crafting.UnlockedRecipeInfo, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnlockedRecipesForUser")
	}

	var r0 []crafting.UnlockedRecipeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]crafting.UnlockedRecipeInfo, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []crafting.UnlockedRecipeInfo); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]crafting.UnlockedRecipeInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUnlockedRecipesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnlockedRecipesForUser'
type MockRepository_GetUnlockedRecipesForUser_Call struct {
	*mock.Call
}

// GetUnlockedRecipesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetUnlockedRecipesForUser(ctx interface{}, userID interface{}) *MockRepository_GetUnlockedRecipesForUser_Call {
	return &MockRepository_GetUnlockedRecipesForUser_Call{Call: _e.mock.On("GetUnlockedRecipesForUser", ctx, userID)}
}

func (_c *MockRepository_GetUnlockedRecipesForUser_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetUnlockedRecipesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUnlockedRecipesForUser_Call) Return(_a0 []crafting.UnlockedRecipeInfo, _a1 error) *MockRepository_GetUnlockedRecipesForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUnlockedRecipesForUser_Call) RunAndReturn(run func(context.Context, string) ([]crafting.UnlockedRecipeInfo, error)) *MockRepository_GetUnlockedRecipesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByPlatformID provides a mock function with given fields: ctx, platform, platformID
func (_m *MockRepository) GetUserByPlatformID(ctx context.Context, platform string, platformID string) (*domain.User, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByPlatformID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByPlatformID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPlatformID'
type MockRepository_GetUserByPlatformID_Call struct {
	*mock.Call
}

// GetUserByPlatformID is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockRepository_Expecter) GetUserByPlatformID(ctx interface{}, platform interface{}, platformID interface{}) *MockRepository_GetUserByPlatformID_Call {
	return &MockRepository_GetUserByPlatformID_Call{Call: _e.mock.On("GetUserByPlatformID", ctx, platform, platformID)}
}

func (_c *MockRepository_GetUserByPlatformID_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockRepository_GetUserByPlatformID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserByPlatformID_Call) Return(_a0 *domain.User, _a1 error) *MockRepository_GetUserByPlatformID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByPlatformID_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockRepository_GetUserByPlatformID_Call {
	_c.Call.Return(run)
	return _c
}

// IsRecipeUnlocked provides a mock function with given fields: ctx, userID, recipeID
func (_m *MockRepository) IsRecipeUnlocked(ctx context.Context, userID string, recipeID int) (bool, error) {
	ret := _m.Called(ctx, userID, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for IsRecipeUnlocked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (bool, error)); ok {
		return rf(ctx, userID, recipeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) bool); ok {
		r0 = rf(ctx, userID, recipeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, recipeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_IsRecipeUnlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRecipeUnlocked'
type MockRepository_IsRecipeUnlocked_Call struct {
	*mock.Call
}

// IsRecipeUnlocked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - recipeID int
func (_e *MockRepository_Expecter) IsRecipeUnlocked(ctx interface{}, userID interface{}, recipeID interface{}) *MockRepository_IsRecipeUnlocked_Call {
	return &MockRepository_IsRecipeUnlocked_Call{Call: _e.mock.On("IsRecipeUnlocked", ctx, userID, recipeID)}
}

func (_c *MockRepository_IsRecipeUnlocked_Call) Run(run func(ctx context.Context, userID string, recipeID int)) *MockRepository_IsRecipeUnlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_IsRecipeUnlocked_Call) Return(_a0 bool, _a1 error) *MockRepository_IsRecipeUnlocked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_IsRecipeUnlocked_Call) RunAndReturn(run func(context.Context, string, int) (bool, error)) *MockRepository_IsRecipeUnlocked_Call {
	_c.Call.Return(run)
	return _c
}

// UnlockRecipe provides a mock function with given fields: ctx, userID, recipeID
func (_m *MockRepository) UnlockRecipe(ctx context.Context, userID string, recipeID int) error {
	ret := _m.Called(ctx, userID, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for UnlockRecipe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, userID, recipeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UnlockRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlockRecipe'
type MockRepository_UnlockRecipe_Call struct {
	*mock.Call
}

// UnlockRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - recipeID int
func (_e *MockRepository_Expecter) UnlockRecipe(ctx interface{}, userID interface{}, recipeID interface{}) *MockRepository_UnlockRecipe_Call {
	return &MockRepository_UnlockRecipe_Call{Call: _e.mock.On("UnlockRecipe", ctx, userID, recipeID)}
}

func (_c *MockRepository_UnlockRecipe_Call) Run(run func(ctx context.Context, userID string, recipeID int)) *MockRepository_UnlockRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_UnlockRecipe_Call) Return(_a0 error) *MockRepository_UnlockRecipe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UnlockRecipe_Call) RunAndReturn(run func(context.Context, string, int) error) *MockRepository_UnlockRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInventory provides a mock function with given fields: ctx, userID, inventory
func (_m *MockRepository) UpdateInventory(ctx context.Context, userID string, inventory domain.Inventory) error {
	ret := _m.Called(ctx, userID, inventory)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Inventory) error); ok {
		r0 = rf(ctx, userID, inventory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInventory'
type MockRepository_UpdateInventory_Call struct {
	*mock.Call
}

// UpdateInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inventory domain.Inventory
func (_e *MockRepository_Expecter) UpdateInventory(ctx interface{}, userID interface{}, inventory interface{}) *MockRepository_UpdateInventory_Call {
	return &MockRepository_UpdateInventory_Call{Call: _e.mock.On("UpdateInventory", ctx, userID, inventory)}
}

func (_c *MockRepository_UpdateInventory_Call) Run(run func(ctx context.Context, userID string, inventory domain.Inventory)) *MockRepository_UpdateInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Inventory))
	})
	return _c
}

func (_c *MockRepository_UpdateInventory_Call) Return(_a0 error) *MockRepository_UpdateInventory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateInventory_Call) RunAndReturn(run func(context.Context, string, domain.Inventory) error) *MockRepository_UpdateInventory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
