// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	user "github.com/osse101/BrandishBot_Go/internal/user"
)

// MockUserService is an autogenerated mock type for the Service type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// AddItemByUsername provides a mock function with given fields: ctx, platform, username, itemName, quantity
func (_m *MockUserService) AddItemByUsername(ctx context.Context, platform string, username string, itemName string, quantity int) error {
	ret := _m.Called(ctx, platform, username, itemName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddItemByUsername")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int) error); ok {
		r0 = rf(ctx, platform, username, itemName, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_AddItemByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItemByUsername'
type MockUserService_AddItemByUsername_Call struct {
	*mock.Call
}

// AddItemByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - username string
//   - itemName string
//   - quantity int
func (_e *MockUserService_Expecter) AddItemByUsername(ctx interface{}, platform interface{}, username interface{}, itemName interface{}, quantity interface{}) *MockUserService_AddItemByUsername_Call {
	return &MockUserService_AddItemByUsername_Call{Call: _e.mock.On("AddItemByUsername", ctx, platform, username, itemName, quantity)}
}

func (_c *MockUserService_AddItemByUsername_Call) Run(run func(ctx context.Context, platform string, username string, itemName string, quantity int)) *MockUserService_AddItemByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockUserService_AddItemByUsername_Call) Return(_a0 error) *MockUserService_AddItemByUsername_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_AddItemByUsername_Call) RunAndReturn(run func(context.Context, string, string, string, int) error) *MockUserService_AddItemByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyShield provides a mock function with given fields: ctx, _a1, quantity
func (_m *MockUserService) ApplyShield(ctx context.Context, _a1 *domain.User, quantity int) error {
	ret := _m.Called(ctx, _a1, quantity)

	if len(ret) == 0 {
		panic("no return value specified for ApplyShield")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, int) error); ok {
		r0 = rf(ctx, _a1, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_ApplyShield_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyShield'
type MockUserService_ApplyShield_Call struct {
	*mock.Call
}

// ApplyShield is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *domain.User
//   - quantity int
func (_e *MockUserService_Expecter) ApplyShield(ctx interface{}, _a1 interface{}, quantity interface{}) *MockUserService_ApplyShield_Call {
	return &MockUserService_ApplyShield_Call{Call: _e.mock.On("ApplyShield", ctx, _a1, quantity)}
}

func (_c *MockUserService_ApplyShield_Call) Run(run func(ctx context.Context, _a1 *domain.User, quantity int)) *MockUserService_ApplyShield_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User), args[2].(int))
	})
	return _c
}

func (_c *MockUserService_ApplyShield_Call) Return(_a0 error) *MockUserService_ApplyShield_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_ApplyShield_Call) RunAndReturn(run func(context.Context, *domain.User, int) error) *MockUserService_ApplyShield_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByPlatformID provides a mock function with given fields: ctx, platform, platformID
func (_m *MockUserService) FindUserByPlatformID(ctx context.Context, platform string, platformID string) (*domain.User, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByPlatformID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_FindUserByPlatformID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByPlatformID'
type MockUserService_FindUserByPlatformID_Call struct {
	*mock.Call
}

// FindUserByPlatformID is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockUserService_Expecter) FindUserByPlatformID(ctx interface{}, platform interface{}, platformID interface{}) *MockUserService_FindUserByPlatformID_Call {
	return &MockUserService_FindUserByPlatformID_Call{Call: _e.mock.On("FindUserByPlatformID", ctx, platform, platformID)}
}

func (_c *MockUserService_FindUserByPlatformID_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockUserService_FindUserByPlatformID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_FindUserByPlatformID_Call) Return(_a0 *domain.User, _a1 error) *MockUserService_FindUserByPlatformID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_FindUserByPlatformID_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockUserService_FindUserByPlatformID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCacheStats provides a mock function with no fields
func (_m *MockUserService) GetCacheStats() user.CacheStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCacheStats")
	}

	var r0 user.CacheStats
	if rf, ok := ret.Get(0).(func() user.CacheStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(user.CacheStats)
	}

	return r0
}

// MockUserService_GetCacheStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheStats'
type MockUserService_GetCacheStats_Call struct {
	*mock.Call
}

// GetCacheStats is a helper method to define mock.On call
func (_e *MockUserService_Expecter) GetCacheStats() *MockUserService_GetCacheStats_Call {
	return &MockUserService_GetCacheStats_Call{Call: _e.mock.On("GetCacheStats")}
}

func (_c *MockUserService_GetCacheStats_Call) Run(run func()) *MockUserService_GetCacheStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserService_GetCacheStats_Call) Return(_a0 user.CacheStats) *MockUserService_GetCacheStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_GetCacheStats_Call) RunAndReturn(run func() user.CacheStats) *MockUserService_GetCacheStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetInventory provides a mock function with given fields: ctx, platform, platformID, username, filter
func (_m *MockUserService) GetInventory(ctx context.Context, platform string, platformID string, username string, filter string) ([]user.InventoryItem, error) {
	ret := _m.Called(ctx, platform, platformID, username, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 []user.InventoryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) ([]user.InventoryItem, error)); ok {
		return rf(ctx, platform, platformID, username, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) []user.InventoryItem); ok {
		r0 = rf(ctx, platform, platformID, username, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.InventoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, platform, platformID, username, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventory'
type MockUserService_GetInventory_Call struct {
	*mock.Call
}

// GetInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - filter string
func (_e *MockUserService_Expecter) GetInventory(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, filter interface{}) *MockUserService_GetInventory_Call {
	return &MockUserService_GetInventory_Call{Call: _e.mock.On("GetInventory", ctx, platform, platformID, username, filter)}
}

func (_c *MockUserService_GetInventory_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, filter string)) *MockUserService_GetInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockUserService_GetInventory_Call) Return(_a0 []user.InventoryItem, _a1 error) *MockUserService_GetInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetInventory_Call) RunAndReturn(run func(context.Context, string, string, string, string) ([]user.InventoryItem, error)) *MockUserService_GetInventory_Call {
	_c.Call.Return(run)
	return _c
}

// GetInventoryByUsername provides a mock function with given fields: ctx, platform, username, filter
func (_m *MockUserService) GetInventoryByUsername(ctx context.Context, platform string, username string, filter string) ([]user.InventoryItem, error) {
	ret := _m.Called(ctx, platform, username, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInventoryByUsername")
	}

	var r0 []user.InventoryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]user.InventoryItem, error)); ok {
		return rf(ctx, platform, username, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []user.InventoryItem); ok {
		r0 = rf(ctx, platform, username, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.InventoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, platform, username, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetInventoryByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventoryByUsername'
type MockUserService_GetInventoryByUsername_Call struct {
	*mock.Call
}

// GetInventoryByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - username string
//   - filter string
func (_e *MockUserService_Expecter) GetInventoryByUsername(ctx interface{}, platform interface{}, username interface{}, filter interface{}) *MockUserService_GetInventoryByUsername_Call {
	return &MockUserService_GetInventoryByUsername_Call{Call: _e.mock.On("GetInventoryByUsername", ctx, platform, username, filter)}
}

func (_c *MockUserService_GetInventoryByUsername_Call) Run(run func(ctx context.Context, platform string, username string, filter string)) *MockUserService_GetInventoryByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUserService_GetInventoryByUsername_Call) Return(_a0 []user.InventoryItem, _a1 error) *MockUserService_GetInventoryByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetInventoryByUsername_Call) RunAndReturn(run func(context.Context, string, string, string) ([]user.InventoryItem, error)) *MockUserService_GetInventoryByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkedPlatforms provides a mock function with given fields: ctx, platform, platformID
func (_m *MockUserService) GetLinkedPlatforms(ctx context.Context, platform string, platformID string) ([]string, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkedPlatforms")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetLinkedPlatforms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkedPlatforms'
type MockUserService_GetLinkedPlatforms_Call struct {
	*mock.Call
}

// GetLinkedPlatforms is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockUserService_Expecter) GetLinkedPlatforms(ctx interface{}, platform interface{}, platformID interface{}) *MockUserService_GetLinkedPlatforms_Call {
	return &MockUserService_GetLinkedPlatforms_Call{Call: _e.mock.On("GetLinkedPlatforms", ctx, platform, platformID)}
}

func (_c *MockUserService_GetLinkedPlatforms_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockUserService_GetLinkedPlatforms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_GetLinkedPlatforms_Call) Return(_a0 []string, _a1 error) *MockUserService_GetLinkedPlatforms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetLinkedPlatforms_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *MockUserService_GetLinkedPlatforms_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeout provides a mock function with given fields: ctx, username
func (_m *MockUserService) GetTimeout(ctx context.Context, username string) (time.Duration, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeout")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (time.Duration, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) time.Duration); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeout'
type MockUserService_GetTimeout_Call struct {
	*mock.Call
}

// GetTimeout is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserService_Expecter) GetTimeout(ctx interface{}, username interface{}) *MockUserService_GetTimeout_Call {
	return &MockUserService_GetTimeout_Call{Call: _e.mock.On("GetTimeout", ctx, username)}
}

func (_c *MockUserService_GetTimeout_Call) Run(run func(ctx context.Context, username string)) *MockUserService_GetTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetTimeout_Call) Return(_a0 time.Duration, _a1 error) *MockUserService_GetTimeout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetTimeout_Call) RunAndReturn(run func(context.Context, string) (time.Duration, error)) *MockUserService_GetTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByPlatformUsername provides a mock function with given fields: ctx, platform, username
func (_m *MockUserService) GetUserByPlatformUsername(ctx context.Context, platform string, username string) (*domain.User, error) {
	ret := _m.Called(ctx, platform, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByPlatformUsername")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, platform, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, platform, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetUserByPlatformUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPlatformUsername'
type MockUserService_GetUserByPlatformUsername_Call struct {
	*mock.Call
}

// GetUserByPlatformUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - username string
func (_e *MockUserService_Expecter) GetUserByPlatformUsername(ctx interface{}, platform interface{}, username interface{}) *MockUserService_GetUserByPlatformUsername_Call {
	return &MockUserService_GetUserByPlatformUsername_Call{Call: _e.mock.On("GetUserByPlatformUsername", ctx, platform, username)}
}

func (_c *MockUserService_GetUserByPlatformUsername_Call) Run(run func(ctx context.Context, platform string, username string)) *MockUserService_GetUserByPlatformUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_GetUserByPlatformUsername_Call) Return(_a0 *domain.User, _a1 error) *MockUserService_GetUserByPlatformUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserByPlatformUsername_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockUserService_GetUserByPlatformUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GiveItem provides a mock function with given fields: ctx, ownerPlatform, ownerPlatformID, ownerUsername, receiverPlatform, receiverUsername, itemName, quantity
func (_m *MockUserService) GiveItem(ctx context.Context, ownerPlatform string, ownerPlatformID string, ownerUsername string, receiverPlatform string, receiverUsername string, itemName string, quantity int) error {
	ret := _m.Called(ctx, ownerPlatform, ownerPlatformID, ownerUsername, receiverPlatform, receiverUsername, itemName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for GiveItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, int) error); ok {
		r0 = rf(ctx, ownerPlatform, ownerPlatformID, ownerUsername, receiverPlatform, receiverUsername, itemName, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_GiveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GiveItem'
type MockUserService_GiveItem_Call struct {
	*mock.Call
}

// GiveItem is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerPlatform string
//   - ownerPlatformID string
//   - ownerUsername string
//   - receiverPlatform string
//   - receiverUsername string
//   - itemName string
//   - quantity int
func (_e *MockUserService_Expecter) GiveItem(ctx interface{}, ownerPlatform interface{}, ownerPlatformID interface{}, ownerUsername interface{}, receiverPlatform interface{}, receiverUsername interface{}, itemName interface{}, quantity interface{}) *MockUserService_GiveItem_Call {
	return &MockUserService_GiveItem_Call{Call: _e.mock.On("GiveItem", ctx, ownerPlatform, ownerPlatformID, ownerUsername, receiverPlatform, receiverUsername, itemName, quantity)}
}

func (_c *MockUserService_GiveItem_Call) Run(run func(ctx context.Context, ownerPlatform string, ownerPlatformID string, ownerUsername string, receiverPlatform string, receiverUsername string, itemName string, quantity int)) *MockUserService_GiveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string), args[7].(int))
	})
	return _c
}

func (_c *MockUserService_GiveItem_Call) Return(_a0 error) *MockUserService_GiveItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_GiveItem_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, string, int) error) *MockUserService_GiveItem_Call {
	_c.Call.Return(run)
	return _c
}

// HandleIncomingMessage provides a mock function with given fields: ctx, platform, platformID, username, message
func (_m *MockUserService) HandleIncomingMessage(ctx context.Context, platform string, platformID string, username string, message string) (*domain.MessageResult, error) {
	ret := _m.Called(ctx, platform, platformID, username, message)

	if len(ret) == 0 {
		panic("no return value specified for HandleIncomingMessage")
	}

	var r0 *domain.MessageResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*domain.MessageResult, error)); ok {
		return rf(ctx, platform, platformID, username, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *domain.MessageResult); ok {
		r0 = rf(ctx, platform, platformID, username, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MessageResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, platform, platformID, username, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_HandleIncomingMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleIncomingMessage'
type MockUserService_HandleIncomingMessage_Call struct {
	*mock.Call
}

// HandleIncomingMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - message string
func (_e *MockUserService_Expecter) HandleIncomingMessage(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, message interface{}) *MockUserService_HandleIncomingMessage_Call {
	return &MockUserService_HandleIncomingMessage_Call{Call: _e.mock.On("HandleIncomingMessage", ctx, platform, platformID, username, message)}
}

func (_c *MockUserService_HandleIncomingMessage_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, message string)) *MockUserService_HandleIncomingMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockUserService_HandleIncomingMessage_Call) Return(_a0 *domain.MessageResult, _a1 error) *MockUserService_HandleIncomingMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_HandleIncomingMessage_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*domain.MessageResult, error)) *MockUserService_HandleIncomingMessage_Call {
	_c.Call.Return(run)
	return _c
}

// HandleSearch provides a mock function with given fields: ctx, platform, platformID, username
func (_m *MockUserService) HandleSearch(ctx context.Context, platform string, platformID string, username string) (string, error) {
	ret := _m.Called(ctx, platform, platformID, username)

	if len(ret) == 0 {
		panic("no return value specified for HandleSearch")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, platform, platformID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, platform, platformID, username)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, platform, platformID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_HandleSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSearch'
type MockUserService_HandleSearch_Call struct {
	*mock.Call
}

// HandleSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
func (_e *MockUserService_Expecter) HandleSearch(ctx interface{}, platform interface{}, platformID interface{}, username interface{}) *MockUserService_HandleSearch_Call {
	return &MockUserService_HandleSearch_Call{Call: _e.mock.On("HandleSearch", ctx, platform, platformID, username)}
}

func (_c *MockUserService_HandleSearch_Call) Run(run func(ctx context.Context, platform string, platformID string, username string)) *MockUserService_HandleSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUserService_HandleSearch_Call) Return(_a0 string, _a1 error) *MockUserService_HandleSearch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_HandleSearch_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *MockUserService_HandleSearch_Call {
	_c.Call.Return(run)
	return _c
}

// MergeUsers provides a mock function with given fields: ctx, primaryUserID, secondaryUserID
func (_m *MockUserService) MergeUsers(ctx context.Context, primaryUserID string, secondaryUserID string) error {
	ret := _m.Called(ctx, primaryUserID, secondaryUserID)

	if len(ret) == 0 {
		panic("no return value specified for MergeUsers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, primaryUserID, secondaryUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_MergeUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeUsers'
type MockUserService_MergeUsers_Call struct {
	*mock.Call
}

// MergeUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - primaryUserID string
//   - secondaryUserID string
func (_e *MockUserService_Expecter) MergeUsers(ctx interface{}, primaryUserID interface{}, secondaryUserID interface{}) *MockUserService_MergeUsers_Call {
	return &MockUserService_MergeUsers_Call{Call: _e.mock.On("MergeUsers", ctx, primaryUserID, secondaryUserID)}
}

func (_c *MockUserService_MergeUsers_Call) Run(run func(ctx context.Context, primaryUserID string, secondaryUserID string)) *MockUserService_MergeUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_MergeUsers_Call) Return(_a0 error) *MockUserService_MergeUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_MergeUsers_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserService_MergeUsers_Call {
	_c.Call.Return(run)
	return _c
}

// ReduceTimeout provides a mock function with given fields: ctx, username, reduction
func (_m *MockUserService) ReduceTimeout(ctx context.Context, username string, reduction time.Duration) error {
	ret := _m.Called(ctx, username, reduction)

	if len(ret) == 0 {
		panic("no return value specified for ReduceTimeout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, username, reduction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_ReduceTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReduceTimeout'
type MockUserService_ReduceTimeout_Call struct {
	*mock.Call
}

// ReduceTimeout is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - reduction time.Duration
func (_e *MockUserService_Expecter) ReduceTimeout(ctx interface{}, username interface{}, reduction interface{}) *MockUserService_ReduceTimeout_Call {
	return &MockUserService_ReduceTimeout_Call{Call: _e.mock.On("ReduceTimeout", ctx, username, reduction)}
}

func (_c *MockUserService_ReduceTimeout_Call) Run(run func(ctx context.Context, username string, reduction time.Duration)) *MockUserService_ReduceTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockUserService_ReduceTimeout_Call) Return(_a0 error) *MockUserService_ReduceTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_ReduceTimeout_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockUserService_ReduceTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, _a1
func (_m *MockUserService) RegisterUser(ctx context.Context, _a1 domain.User) (domain.User, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockUserService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 domain.User
func (_e *MockUserService_Expecter) RegisterUser(ctx interface{}, _a1 interface{}) *MockUserService_RegisterUser_Call {
	return &MockUserService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, _a1)}
}

func (_c *MockUserService_RegisterUser_Call) Run(run func(ctx context.Context, _a1 domain.User)) *MockUserService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockUserService_RegisterUser_Call) Return(_a0 domain.User, _a1 error) *MockUserService_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_RegisterUser_Call) RunAndReturn(run func(context.Context, domain.User) (domain.User, error)) *MockUserService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItemByUsername provides a mock function with given fields: ctx, platform, username, itemName, quantity
func (_m *MockUserService) RemoveItemByUsername(ctx context.Context, platform string, username string, itemName string, quantity int) (int, error) {
	ret := _m.Called(ctx, platform, username, itemName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItemByUsername")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int) (int, error)); ok {
		return rf(ctx, platform, username, itemName, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int) int); ok {
		r0 = rf(ctx, platform, username, itemName, quantity)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int) error); ok {
		r1 = rf(ctx, platform, username, itemName, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_RemoveItemByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItemByUsername'
type MockUserService_RemoveItemByUsername_Call struct {
	*mock.Call
}

// RemoveItemByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - username string
//   - itemName string
//   - quantity int
func (_e *MockUserService_Expecter) RemoveItemByUsername(ctx interface{}, platform interface{}, username interface{}, itemName interface{}, quantity interface{}) *MockUserService_RemoveItemByUsername_Call {
	return &MockUserService_RemoveItemByUsername_Call{Call: _e.mock.On("RemoveItemByUsername", ctx, platform, username, itemName, quantity)}
}

func (_c *MockUserService_RemoveItemByUsername_Call) Run(run func(ctx context.Context, platform string, username string, itemName string, quantity int)) *MockUserService_RemoveItemByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockUserService_RemoveItemByUsername_Call) Return(_a0 int, _a1 error) *MockUserService_RemoveItemByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_RemoveItemByUsername_Call) RunAndReturn(run func(context.Context, string, string, string, int) (int, error)) *MockUserService_RemoveItemByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockUserService) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockUserService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserService_Expecter) Shutdown(ctx interface{}) *MockUserService_Shutdown_Call {
	return &MockUserService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockUserService_Shutdown_Call) Run(run func(ctx context.Context)) *MockUserService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserService_Shutdown_Call) Return(_a0 error) *MockUserService_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_Shutdown_Call) RunAndReturn(run func(context.Context) error) *MockUserService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// TimeoutUser provides a mock function with given fields: ctx, username, duration, reason
func (_m *MockUserService) TimeoutUser(ctx context.Context, username string, duration time.Duration, reason string) error {
	ret := _m.Called(ctx, username, duration, reason)

	if len(ret) == 0 {
		panic("no return value specified for TimeoutUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, string) error); ok {
		r0 = rf(ctx, username, duration, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_TimeoutUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeoutUser'
type MockUserService_TimeoutUser_Call struct {
	*mock.Call
}

// TimeoutUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - duration time.Duration
//   - reason string
func (_e *MockUserService_Expecter) TimeoutUser(ctx interface{}, username interface{}, duration interface{}, reason interface{}) *MockUserService_TimeoutUser_Call {
	return &MockUserService_TimeoutUser_Call{Call: _e.mock.On("TimeoutUser", ctx, username, duration, reason)}
}

func (_c *MockUserService_TimeoutUser_Call) Run(run func(ctx context.Context, username string, duration time.Duration, reason string)) *MockUserService_TimeoutUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration), args[3].(string))
	})
	return _c
}

func (_c *MockUserService_TimeoutUser_Call) Return(_a0 error) *MockUserService_TimeoutUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_TimeoutUser_Call) RunAndReturn(run func(context.Context, string, time.Duration, string) error) *MockUserService_TimeoutUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnlinkPlatform provides a mock function with given fields: ctx, userID, platform
func (_m *MockUserService) UnlinkPlatform(ctx context.Context, userID string, platform string) error {
	ret := _m.Called(ctx, userID, platform)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkPlatform")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, platform)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_UnlinkPlatform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlinkPlatform'
type MockUserService_UnlinkPlatform_Call struct {
	*mock.Call
}

// UnlinkPlatform is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - platform string
func (_e *MockUserService_Expecter) UnlinkPlatform(ctx interface{}, userID interface{}, platform interface{}) *MockUserService_UnlinkPlatform_Call {
	return &MockUserService_UnlinkPlatform_Call{Call: _e.mock.On("UnlinkPlatform", ctx, userID, platform)}
}

func (_c *MockUserService_UnlinkPlatform_Call) Run(run func(ctx context.Context, userID string, platform string)) *MockUserService_UnlinkPlatform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_UnlinkPlatform_Call) Return(_a0 error) *MockUserService_UnlinkPlatform_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_UnlinkPlatform_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserService_UnlinkPlatform_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, _a1
func (_m *MockUserService) UpdateUser(ctx context.Context, _a1 domain.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 domain.User
func (_e *MockUserService_Expecter) UpdateUser(ctx interface{}, _a1 interface{}) *MockUserService_UpdateUser_Call {
	return &MockUserService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, _a1)}
}

func (_c *MockUserService_UpdateUser_Call) Run(run func(ctx context.Context, _a1 domain.User)) *MockUserService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockUserService_UpdateUser_Call) Return(_a0 error) *MockUserService_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_UpdateUser_Call) RunAndReturn(run func(context.Context, domain.User) error) *MockUserService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UseItem provides a mock function with given fields: ctx, platform, platformID, username, itemName, quantity, targetUsername
func (_m *MockUserService) UseItem(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int, targetUsername string) (string, error) {
	ret := _m.Called(ctx, platform, platformID, username, itemName, quantity, targetUsername)

	if len(ret) == 0 {
		panic("no return value specified for UseItem")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, string) (string, error)); ok {
		return rf(ctx, platform, platformID, username, itemName, quantity, targetUsername)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, string) string); ok {
		r0 = rf(ctx, platform, platformID, username, itemName, quantity, targetUsername)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int, string) error); ok {
		r1 = rf(ctx, platform, platformID, username, itemName, quantity, targetUsername)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_UseItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseItem'
type MockUserService_UseItem_Call struct {
	*mock.Call
}

// UseItem is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - itemName string
//   - quantity int
//   - targetUsername string
func (_e *MockUserService_Expecter) UseItem(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, itemName interface{}, quantity interface{}, targetUsername interface{}) *MockUserService_UseItem_Call {
	return &MockUserService_UseItem_Call{Call: _e.mock.On("UseItem", ctx, platform, platformID, username, itemName, quantity, targetUsername)}
}

func (_c *MockUserService_UseItem_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int, targetUsername string)) *MockUserService_UseItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int), args[6].(string))
	})
	return _c
}

func (_c *MockUserService_UseItem_Call) Return(_a0 string, _a1 error) *MockUserService_UseItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_UseItem_Call) RunAndReturn(run func(context.Context, string, string, string, string, int, string) (string, error)) *MockUserService_UseItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
