// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockJob is an autogenerated mock type for the Job type
type MockJob struct {
	mock.Mock
}

type MockJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJob) EXPECT() *MockJob_Expecter {
	return &MockJob_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: ctx
func (_m *MockJob) Process(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJob_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockJob_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockJob_Expecter) Process(ctx interface{}) *MockJob_Process_Call {
	return &MockJob_Process_Call{Call: _e.mock.On("Process", ctx)}
}

func (_c *MockJob_Process_Call) Run(run func(ctx context.Context)) *MockJob_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockJob_Process_Call) Return(_a0 error) *MockJob_Process_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJob_Process_Call) RunAndReturn(run func(context.Context) error) *MockJob_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJob creates a new instance of MockJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJob {
	mock := &MockJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
