// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	user "github.com/osse101/BrandishBot_Go/internal/user"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function with given fields: ctx, platform, platformID, username, itemName, quantity
func (_m *MockService) AddItem(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int) error {
	ret := _m.Called(ctx, platform, platformID, username, itemName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) error); ok {
		r0 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockService_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - itemName string
//   - quantity int
func (_e *MockService_Expecter) AddItem(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, itemName interface{}, quantity interface{}) *MockService_AddItem_Call {
	return &MockService_AddItem_Call{Call: _e.mock.On("AddItem", ctx, platform, platformID, username, itemName, quantity)}
}

func (_c *MockService_AddItem_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int)) *MockService_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockService_AddItem_Call) Return(_a0 error) *MockService_AddItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_AddItem_Call) RunAndReturn(run func(context.Context, string, string, string, string, int) error) *MockService_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByPlatformID provides a mock function with given fields: ctx, platform, platformID
func (_m *MockService) FindUserByPlatformID(ctx context.Context, platform string, platformID string) (*domain.User, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByPlatformID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_FindUserByPlatformID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByPlatformID'
type MockService_FindUserByPlatformID_Call struct {
	*mock.Call
}

// FindUserByPlatformID is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockService_Expecter) FindUserByPlatformID(ctx interface{}, platform interface{}, platformID interface{}) *MockService_FindUserByPlatformID_Call {
	return &MockService_FindUserByPlatformID_Call{Call: _e.mock.On("FindUserByPlatformID", ctx, platform, platformID)}
}

func (_c *MockService_FindUserByPlatformID_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockService_FindUserByPlatformID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_FindUserByPlatformID_Call) Return(_a0 *domain.User, _a1 error) *MockService_FindUserByPlatformID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_FindUserByPlatformID_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockService_FindUserByPlatformID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInventory provides a mock function with given fields: ctx, platform, platformID, username
func (_m *MockService) GetInventory(ctx context.Context, platform string, platformID string, username string) ([]user.UserInventoryItem, error) {
	ret := _m.Called(ctx, platform, platformID, username)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 []user.UserInventoryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]user.UserInventoryItem, error)); ok {
		return rf(ctx, platform, platformID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []user.UserInventoryItem); ok {
		r0 = rf(ctx, platform, platformID, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.UserInventoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, platform, platformID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventory'
type MockService_GetInventory_Call struct {
	*mock.Call
}

// GetInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
func (_e *MockService_Expecter) GetInventory(ctx interface{}, platform interface{}, platformID interface{}, username interface{}) *MockService_GetInventory_Call {
	return &MockService_GetInventory_Call{Call: _e.mock.On("GetInventory", ctx, platform, platformID, username)}
}

func (_c *MockService_GetInventory_Call) Run(run func(ctx context.Context, platform string, platformID string, username string)) *MockService_GetInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_GetInventory_Call) Return(_a0 []user.UserInventoryItem, _a1 error) *MockService_GetInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetInventory_Call) RunAndReturn(run func(context.Context, string, string, string) ([]user.UserInventoryItem, error)) *MockService_GetInventory_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkedPlatforms provides a mock function with given fields: ctx, platform, platformID
func (_m *MockService) GetLinkedPlatforms(ctx context.Context, platform string, platformID string) ([]string, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkedPlatforms")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetLinkedPlatforms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkedPlatforms'
type MockService_GetLinkedPlatforms_Call struct {
	*mock.Call
}

// GetLinkedPlatforms is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockService_Expecter) GetLinkedPlatforms(ctx interface{}, platform interface{}, platformID interface{}) *MockService_GetLinkedPlatforms_Call {
	return &MockService_GetLinkedPlatforms_Call{Call: _e.mock.On("GetLinkedPlatforms", ctx, platform, platformID)}
}

func (_c *MockService_GetLinkedPlatforms_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockService_GetLinkedPlatforms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetLinkedPlatforms_Call) Return(_a0 []string, _a1 error) *MockService_GetLinkedPlatforms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetLinkedPlatforms_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *MockService_GetLinkedPlatforms_Call {
	_c.Call.Return(run)
	return _c
}

// GiveItem provides a mock function with given fields: ctx, ownerPlatform, ownerPlatformID, ownerUsername, receiverPlatform, receiverPlatformID, receiverUsername, itemName, quantity
func (_m *MockService) GiveItem(ctx context.Context, ownerPlatform string, ownerPlatformID string, ownerUsername string, receiverPlatform string, receiverPlatformID string, receiverUsername string, itemName string, quantity int) error {
	ret := _m.Called(ctx, ownerPlatform, ownerPlatformID, ownerUsername, receiverPlatform, receiverPlatformID, receiverUsername, itemName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for GiveItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string, int) error); ok {
		r0 = rf(ctx, ownerPlatform, ownerPlatformID, ownerUsername, receiverPlatform, receiverPlatformID, receiverUsername, itemName, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_GiveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GiveItem'
type MockService_GiveItem_Call struct {
	*mock.Call
}

// GiveItem is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerPlatform string
//   - ownerPlatformID string
//   - ownerUsername string
//   - receiverPlatform string
//   - receiverPlatformID string
//   - receiverUsername string
//   - itemName string
//   - quantity int
func (_e *MockService_Expecter) GiveItem(ctx interface{}, ownerPlatform interface{}, ownerPlatformID interface{}, ownerUsername interface{}, receiverPlatform interface{}, receiverPlatformID interface{}, receiverUsername interface{}, itemName interface{}, quantity interface{}) *MockService_GiveItem_Call {
	return &MockService_GiveItem_Call{Call: _e.mock.On("GiveItem", ctx, ownerPlatform, ownerPlatformID, ownerUsername, receiverPlatform, receiverPlatformID, receiverUsername, itemName, quantity)}
}

func (_c *MockService_GiveItem_Call) Run(run func(ctx context.Context, ownerPlatform string, ownerPlatformID string, ownerUsername string, receiverPlatform string, receiverPlatformID string, receiverUsername string, itemName string, quantity int)) *MockService_GiveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string), args[7].(string), args[8].(int))
	})
	return _c
}

func (_c *MockService_GiveItem_Call) Return(_a0 error) *MockService_GiveItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_GiveItem_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, string, string, int) error) *MockService_GiveItem_Call {
	_c.Call.Return(run)
	return _c
}

// HandleIncomingMessage provides a mock function with given fields: ctx, platform, platformID, username, message
func (_m *MockService) HandleIncomingMessage(ctx context.Context, platform string, platformID string, username string, message string) (*domain.MessageResult, error) {
	ret := _m.Called(ctx, platform, platformID, username, message)

	if len(ret) == 0 {
		panic("no return value specified for HandleIncomingMessage")
	}

	var r0 *domain.MessageResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*domain.MessageResult, error)); ok {
		return rf(ctx, platform, platformID, username, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *domain.MessageResult); ok {
		r0 = rf(ctx, platform, platformID, username, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MessageResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, platform, platformID, username, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_HandleIncomingMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleIncomingMessage'
type MockService_HandleIncomingMessage_Call struct {
	*mock.Call
}

// HandleIncomingMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - message string
func (_e *MockService_Expecter) HandleIncomingMessage(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, message interface{}) *MockService_HandleIncomingMessage_Call {
	return &MockService_HandleIncomingMessage_Call{Call: _e.mock.On("HandleIncomingMessage", ctx, platform, platformID, username, message)}
}

func (_c *MockService_HandleIncomingMessage_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, message string)) *MockService_HandleIncomingMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockService_HandleIncomingMessage_Call) Return(_a0 *domain.MessageResult, _a1 error) *MockService_HandleIncomingMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_HandleIncomingMessage_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*domain.MessageResult, error)) *MockService_HandleIncomingMessage_Call {
	_c.Call.Return(run)
	return _c
}

// HandleSearch provides a mock function with given fields: ctx, platform, platformID, username
func (_m *MockService) HandleSearch(ctx context.Context, platform string, platformID string, username string) (string, error) {
	ret := _m.Called(ctx, platform, platformID, username)

	if len(ret) == 0 {
		panic("no return value specified for HandleSearch")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, platform, platformID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, platform, platformID, username)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, platform, platformID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_HandleSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSearch'
type MockService_HandleSearch_Call struct {
	*mock.Call
}

// HandleSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
func (_e *MockService_Expecter) HandleSearch(ctx interface{}, platform interface{}, platformID interface{}, username interface{}) *MockService_HandleSearch_Call {
	return &MockService_HandleSearch_Call{Call: _e.mock.On("HandleSearch", ctx, platform, platformID, username)}
}

func (_c *MockService_HandleSearch_Call) Run(run func(ctx context.Context, platform string, platformID string, username string)) *MockService_HandleSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_HandleSearch_Call) Return(_a0 string, _a1 error) *MockService_HandleSearch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_HandleSearch_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *MockService_HandleSearch_Call {
	_c.Call.Return(run)
	return _c
}

// MergeUsers provides a mock function with given fields: ctx, primaryUserID, secondaryUserID
func (_m *MockService) MergeUsers(ctx context.Context, primaryUserID string, secondaryUserID string) error {
	ret := _m.Called(ctx, primaryUserID, secondaryUserID)

	if len(ret) == 0 {
		panic("no return value specified for MergeUsers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, primaryUserID, secondaryUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_MergeUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeUsers'
type MockService_MergeUsers_Call struct {
	*mock.Call
}

// MergeUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - primaryUserID string
//   - secondaryUserID string
func (_e *MockService_Expecter) MergeUsers(ctx interface{}, primaryUserID interface{}, secondaryUserID interface{}) *MockService_MergeUsers_Call {
	return &MockService_MergeUsers_Call{Call: _e.mock.On("MergeUsers", ctx, primaryUserID, secondaryUserID)}
}

func (_c *MockService_MergeUsers_Call) Run(run func(ctx context.Context, primaryUserID string, secondaryUserID string)) *MockService_MergeUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_MergeUsers_Call) Return(_a0 error) *MockService_MergeUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_MergeUsers_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_MergeUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, _a1
func (_m *MockService) RegisterUser(ctx context.Context, _a1 domain.User) (domain.User, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 domain.User
func (_e *MockService_Expecter) RegisterUser(ctx interface{}, _a1 interface{}) *MockService_RegisterUser_Call {
	return &MockService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, _a1)}
}

func (_c *MockService_RegisterUser_Call) Run(run func(ctx context.Context, _a1 domain.User)) *MockService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockService_RegisterUser_Call) Return(_a0 domain.User, _a1 error) *MockService_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RegisterUser_Call) RunAndReturn(run func(context.Context, domain.User) (domain.User, error)) *MockService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItem provides a mock function with given fields: ctx, platform, platformID, username, itemName, quantity
func (_m *MockService) RemoveItem(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int) (int, error) {
	ret := _m.Called(ctx, platform, platformID, username, itemName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) (int, error)); ok {
		return rf(ctx, platform, platformID, username, itemName, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) int); ok {
		r0 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int) error); ok {
		r1 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RemoveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItem'
type MockService_RemoveItem_Call struct {
	*mock.Call
}

// RemoveItem is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - itemName string
//   - quantity int
func (_e *MockService_Expecter) RemoveItem(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, itemName interface{}, quantity interface{}) *MockService_RemoveItem_Call {
	return &MockService_RemoveItem_Call{Call: _e.mock.On("RemoveItem", ctx, platform, platformID, username, itemName, quantity)}
}

func (_c *MockService_RemoveItem_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int)) *MockService_RemoveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockService_RemoveItem_Call) Return(_a0 int, _a1 error) *MockService_RemoveItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RemoveItem_Call) RunAndReturn(run func(context.Context, string, string, string, string, int) (int, error)) *MockService_RemoveItem_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockService) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Shutdown(ctx interface{}) *MockService_Shutdown_Call {
	return &MockService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockService_Shutdown_Call) Run(run func(ctx context.Context)) *MockService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Shutdown_Call) Return(_a0 error) *MockService_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Shutdown_Call) RunAndReturn(run func(context.Context) error) *MockService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// TimeoutUser provides a mock function with given fields: ctx, username, duration, reason
func (_m *MockService) TimeoutUser(ctx context.Context, username string, duration time.Duration, reason string) error {
	ret := _m.Called(ctx, username, duration, reason)

	if len(ret) == 0 {
		panic("no return value specified for TimeoutUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, string) error); ok {
		r0 = rf(ctx, username, duration, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_TimeoutUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeoutUser'
type MockService_TimeoutUser_Call struct {
	*mock.Call
}

// TimeoutUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - duration time.Duration
//   - reason string
func (_e *MockService_Expecter) TimeoutUser(ctx interface{}, username interface{}, duration interface{}, reason interface{}) *MockService_TimeoutUser_Call {
	return &MockService_TimeoutUser_Call{Call: _e.mock.On("TimeoutUser", ctx, username, duration, reason)}
}

func (_c *MockService_TimeoutUser_Call) Run(run func(ctx context.Context, username string, duration time.Duration, reason string)) *MockService_TimeoutUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration), args[3].(string))
	})
	return _c
}

func (_c *MockService_TimeoutUser_Call) Return(_a0 error) *MockService_TimeoutUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_TimeoutUser_Call) RunAndReturn(run func(context.Context, string, time.Duration, string) error) *MockService_TimeoutUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnlinkPlatform provides a mock function with given fields: ctx, userID, platform
func (_m *MockService) UnlinkPlatform(ctx context.Context, userID string, platform string) error {
	ret := _m.Called(ctx, userID, platform)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkPlatform")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, platform)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UnlinkPlatform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlinkPlatform'
type MockService_UnlinkPlatform_Call struct {
	*mock.Call
}

// UnlinkPlatform is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - platform string
func (_e *MockService_Expecter) UnlinkPlatform(ctx interface{}, userID interface{}, platform interface{}) *MockService_UnlinkPlatform_Call {
	return &MockService_UnlinkPlatform_Call{Call: _e.mock.On("UnlinkPlatform", ctx, userID, platform)}
}

func (_c *MockService_UnlinkPlatform_Call) Run(run func(ctx context.Context, userID string, platform string)) *MockService_UnlinkPlatform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_UnlinkPlatform_Call) Return(_a0 error) *MockService_UnlinkPlatform_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UnlinkPlatform_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_UnlinkPlatform_Call {
	_c.Call.Return(run)
	return _c
}

// UseItem provides a mock function with given fields: ctx, platform, platformID, username, itemName, quantity, targetUsername
func (_m *MockService) UseItem(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int, targetUsername string) (string, error) {
	ret := _m.Called(ctx, platform, platformID, username, itemName, quantity, targetUsername)

	if len(ret) == 0 {
		panic("no return value specified for UseItem")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, string) (string, error)); ok {
		return rf(ctx, platform, platformID, username, itemName, quantity, targetUsername)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, string) string); ok {
		r0 = rf(ctx, platform, platformID, username, itemName, quantity, targetUsername)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int, string) error); ok {
		r1 = rf(ctx, platform, platformID, username, itemName, quantity, targetUsername)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UseItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseItem'
type MockService_UseItem_Call struct {
	*mock.Call
}

// UseItem is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - itemName string
//   - quantity int
//   - targetUsername string
func (_e *MockService_Expecter) UseItem(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, itemName interface{}, quantity interface{}, targetUsername interface{}) *MockService_UseItem_Call {
	return &MockService_UseItem_Call{Call: _e.mock.On("UseItem", ctx, platform, platformID, username, itemName, quantity, targetUsername)}
}

func (_c *MockService_UseItem_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int, targetUsername string)) *MockService_UseItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int), args[6].(string))
	})
	return _c
}

func (_c *MockService_UseItem_Call) Return(_a0 string, _a1 error) *MockService_UseItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UseItem_Call) RunAndReturn(run func(context.Context, string, string, string, string, int, string) (string, error)) *MockService_UseItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
