// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockNamingResolver is an autogenerated mock type for the Resolver type
type MockNamingResolver struct {
	mock.Mock
}

type MockNamingResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNamingResolver) EXPECT() *MockNamingResolver_Expecter {
	return &MockNamingResolver_Expecter{mock: &_m.Mock}
}

// GetActiveTheme provides a mock function with no fields
func (_m *MockNamingResolver) GetActiveTheme() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActiveTheme")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockNamingResolver_GetActiveTheme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveTheme'
type MockNamingResolver_GetActiveTheme_Call struct {
	*mock.Call
}

// GetActiveTheme is a helper method to define mock.On call
func (_e *MockNamingResolver_Expecter) GetActiveTheme() *MockNamingResolver_GetActiveTheme_Call {
	return &MockNamingResolver_GetActiveTheme_Call{Call: _e.mock.On("GetActiveTheme")}
}

func (_c *MockNamingResolver_GetActiveTheme_Call) Run(run func()) *MockNamingResolver_GetActiveTheme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNamingResolver_GetActiveTheme_Call) Return(_a0 string) *MockNamingResolver_GetActiveTheme_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNamingResolver_GetActiveTheme_Call) RunAndReturn(run func() string) *MockNamingResolver_GetActiveTheme_Call {
	_c.Call.Return(run)
	return _c
}

// GetDisplayName provides a mock function with given fields: internalName, shineLevel
func (_m *MockNamingResolver) GetDisplayName(internalName string, shineLevel domain.ShineLevel) string {
	ret := _m.Called(internalName, shineLevel)

	if len(ret) == 0 {
		panic("no return value specified for GetDisplayName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, domain.ShineLevel) string); ok {
		r0 = rf(internalName, shineLevel)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockNamingResolver_GetDisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDisplayName'
type MockNamingResolver_GetDisplayName_Call struct {
	*mock.Call
}

// GetDisplayName is a helper method to define mock.On call
//   - internalName string
//   - shineLevel domain.ShineLevel
func (_e *MockNamingResolver_Expecter) GetDisplayName(internalName interface{}, shineLevel interface{}) *MockNamingResolver_GetDisplayName_Call {
	return &MockNamingResolver_GetDisplayName_Call{Call: _e.mock.On("GetDisplayName", internalName, shineLevel)}
}

func (_c *MockNamingResolver_GetDisplayName_Call) Run(run func(internalName string, shineLevel domain.ShineLevel)) *MockNamingResolver_GetDisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(domain.ShineLevel))
	})
	return _c
}

func (_c *MockNamingResolver_GetDisplayName_Call) Return(_a0 string) *MockNamingResolver_GetDisplayName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNamingResolver_GetDisplayName_Call) RunAndReturn(run func(string, domain.ShineLevel) string) *MockNamingResolver_GetDisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterItem provides a mock function with given fields: internalName, publicName
func (_m *MockNamingResolver) RegisterItem(internalName string, publicName string) {
	_m.Called(internalName, publicName)
}

// MockNamingResolver_RegisterItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterItem'
type MockNamingResolver_RegisterItem_Call struct {
	*mock.Call
}

// RegisterItem is a helper method to define mock.On call
//   - internalName string
//   - publicName string
func (_e *MockNamingResolver_Expecter) RegisterItem(internalName interface{}, publicName interface{}) *MockNamingResolver_RegisterItem_Call {
	return &MockNamingResolver_RegisterItem_Call{Call: _e.mock.On("RegisterItem", internalName, publicName)}
}

func (_c *MockNamingResolver_RegisterItem_Call) Run(run func(internalName string, publicName string)) *MockNamingResolver_RegisterItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockNamingResolver_RegisterItem_Call) Return() *MockNamingResolver_RegisterItem_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNamingResolver_RegisterItem_Call) RunAndReturn(run func(string, string)) *MockNamingResolver_RegisterItem_Call {
	_c.Run(run)
	return _c
}

// Reload provides a mock function with no fields
func (_m *MockNamingResolver) Reload() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNamingResolver_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type MockNamingResolver_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
func (_e *MockNamingResolver_Expecter) Reload() *MockNamingResolver_Reload_Call {
	return &MockNamingResolver_Reload_Call{Call: _e.mock.On("Reload")}
}

func (_c *MockNamingResolver_Reload_Call) Run(run func()) *MockNamingResolver_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNamingResolver_Reload_Call) Return(_a0 error) *MockNamingResolver_Reload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNamingResolver_Reload_Call) RunAndReturn(run func() error) *MockNamingResolver_Reload_Call {
	_c.Call.Return(run)
	return _c
}

// ResolvePublicName provides a mock function with given fields: publicName
func (_m *MockNamingResolver) ResolvePublicName(publicName string) (string, bool) {
	ret := _m.Called(publicName)

	if len(ret) == 0 {
		panic("no return value specified for ResolvePublicName")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(publicName)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(publicName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(publicName)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockNamingResolver_ResolvePublicName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvePublicName'
type MockNamingResolver_ResolvePublicName_Call struct {
	*mock.Call
}

// ResolvePublicName is a helper method to define mock.On call
//   - publicName string
func (_e *MockNamingResolver_Expecter) ResolvePublicName(publicName interface{}) *MockNamingResolver_ResolvePublicName_Call {
	return &MockNamingResolver_ResolvePublicName_Call{Call: _e.mock.On("ResolvePublicName", publicName)}
}

func (_c *MockNamingResolver_ResolvePublicName_Call) Run(run func(publicName string)) *MockNamingResolver_ResolvePublicName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockNamingResolver_ResolvePublicName_Call) Return(internalName string, ok bool) *MockNamingResolver_ResolvePublicName_Call {
	_c.Call.Return(internalName, ok)
	return _c
}

func (_c *MockNamingResolver_ResolvePublicName_Call) RunAndReturn(run func(string) (string, bool)) *MockNamingResolver_ResolvePublicName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNamingResolver creates a new instance of MockNamingResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNamingResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNamingResolver {
	mock := &MockNamingResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
