// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepositoryGambleTx is an autogenerated mock type for the GambleTx type
type MockRepositoryGambleTx struct {
	mock.Mock
}

type MockRepositoryGambleTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryGambleTx) EXPECT() *MockRepositoryGambleTx_Expecter {
	return &MockRepositoryGambleTx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields: ctx
func (_m *MockRepositoryGambleTx) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryGambleTx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockRepositoryGambleTx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryGambleTx_Expecter) Commit(ctx interface{}) *MockRepositoryGambleTx_Commit_Call {
	return &MockRepositoryGambleTx_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockRepositoryGambleTx_Commit_Call) Run(run func(ctx context.Context)) *MockRepositoryGambleTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryGambleTx_Commit_Call) Return(_a0 error) *MockRepositoryGambleTx_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryGambleTx_Commit_Call) RunAndReturn(run func(context.Context) error) *MockRepositoryGambleTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteGamble provides a mock function with given fields: ctx, result
func (_m *MockRepositoryGambleTx) CompleteGamble(ctx context.Context, result *domain.GambleResult) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for CompleteGamble")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GambleResult) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryGambleTx_CompleteGamble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteGamble'
type MockRepositoryGambleTx_CompleteGamble_Call struct {
	*mock.Call
}

// CompleteGamble is a helper method to define mock.On call
//   - ctx context.Context
//   - result *domain.GambleResult
func (_e *MockRepositoryGambleTx_Expecter) CompleteGamble(ctx interface{}, result interface{}) *MockRepositoryGambleTx_CompleteGamble_Call {
	return &MockRepositoryGambleTx_CompleteGamble_Call{Call: _e.mock.On("CompleteGamble", ctx, result)}
}

func (_c *MockRepositoryGambleTx_CompleteGamble_Call) Run(run func(ctx context.Context, result *domain.GambleResult)) *MockRepositoryGambleTx_CompleteGamble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.GambleResult))
	})
	return _c
}

func (_c *MockRepositoryGambleTx_CompleteGamble_Call) Return(_a0 error) *MockRepositoryGambleTx_CompleteGamble_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryGambleTx_CompleteGamble_Call) RunAndReturn(run func(context.Context, *domain.GambleResult) error) *MockRepositoryGambleTx_CompleteGamble_Call {
	_c.Call.Return(run)
	return _c
}

// GetInventory provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryGambleTx) GetInventory(ctx context.Context, userID string) (*domain.Inventory, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 *domain.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Inventory, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Inventory); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryGambleTx_GetInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventory'
type MockRepositoryGambleTx_GetInventory_Call struct {
	*mock.Call
}

// GetInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryGambleTx_Expecter) GetInventory(ctx interface{}, userID interface{}) *MockRepositoryGambleTx_GetInventory_Call {
	return &MockRepositoryGambleTx_GetInventory_Call{Call: _e.mock.On("GetInventory", ctx, userID)}
}

func (_c *MockRepositoryGambleTx_GetInventory_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryGambleTx_GetInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryGambleTx_GetInventory_Call) Return(_a0 *domain.Inventory, _a1 error) *MockRepositoryGambleTx_GetInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryGambleTx_GetInventory_Call) RunAndReturn(run func(context.Context, string) (*domain.Inventory, error)) *MockRepositoryGambleTx_GetInventory_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockRepositoryGambleTx) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryGambleTx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockRepositoryGambleTx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryGambleTx_Expecter) Rollback(ctx interface{}) *MockRepositoryGambleTx_Rollback_Call {
	return &MockRepositoryGambleTx_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockRepositoryGambleTx_Rollback_Call) Run(run func(ctx context.Context)) *MockRepositoryGambleTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryGambleTx_Rollback_Call) Return(_a0 error) *MockRepositoryGambleTx_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryGambleTx_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockRepositoryGambleTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOpenedItems provides a mock function with given fields: ctx, items
func (_m *MockRepositoryGambleTx) SaveOpenedItems(ctx context.Context, items []domain.GambleOpenedItem) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for SaveOpenedItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.GambleOpenedItem) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryGambleTx_SaveOpenedItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOpenedItems'
type MockRepositoryGambleTx_SaveOpenedItems_Call struct {
	*mock.Call
}

// SaveOpenedItems is a helper method to define mock.On call
//   - ctx context.Context
//   - items []domain.GambleOpenedItem
func (_e *MockRepositoryGambleTx_Expecter) SaveOpenedItems(ctx interface{}, items interface{}) *MockRepositoryGambleTx_SaveOpenedItems_Call {
	return &MockRepositoryGambleTx_SaveOpenedItems_Call{Call: _e.mock.On("SaveOpenedItems", ctx, items)}
}

func (_c *MockRepositoryGambleTx_SaveOpenedItems_Call) Run(run func(ctx context.Context, items []domain.GambleOpenedItem)) *MockRepositoryGambleTx_SaveOpenedItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.GambleOpenedItem))
	})
	return _c
}

func (_c *MockRepositoryGambleTx_SaveOpenedItems_Call) Return(_a0 error) *MockRepositoryGambleTx_SaveOpenedItems_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryGambleTx_SaveOpenedItems_Call) RunAndReturn(run func(context.Context, []domain.GambleOpenedItem) error) *MockRepositoryGambleTx_SaveOpenedItems_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGambleStateIfMatches provides a mock function with given fields: ctx, id, expectedState, newState
func (_m *MockRepositoryGambleTx) UpdateGambleStateIfMatches(ctx context.Context, id uuid.UUID, expectedState domain.GambleState, newState domain.GambleState) (int64, error) {
	ret := _m.Called(ctx, id, expectedState, newState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGambleStateIfMatches")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.GambleState, domain.GambleState) (int64, error)); ok {
		return rf(ctx, id, expectedState, newState)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.GambleState, domain.GambleState) int64); ok {
		r0 = rf(ctx, id, expectedState, newState)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.GambleState, domain.GambleState) error); ok {
		r1 = rf(ctx, id, expectedState, newState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryGambleTx_UpdateGambleStateIfMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGambleStateIfMatches'
type MockRepositoryGambleTx_UpdateGambleStateIfMatches_Call struct {
	*mock.Call
}

// UpdateGambleStateIfMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - expectedState domain.GambleState
//   - newState domain.GambleState
func (_e *MockRepositoryGambleTx_Expecter) UpdateGambleStateIfMatches(ctx interface{}, id interface{}, expectedState interface{}, newState interface{}) *MockRepositoryGambleTx_UpdateGambleStateIfMatches_Call {
	return &MockRepositoryGambleTx_UpdateGambleStateIfMatches_Call{Call: _e.mock.On("UpdateGambleStateIfMatches", ctx, id, expectedState, newState)}
}

func (_c *MockRepositoryGambleTx_UpdateGambleStateIfMatches_Call) Run(run func(ctx context.Context, id uuid.UUID, expectedState domain.GambleState, newState domain.GambleState)) *MockRepositoryGambleTx_UpdateGambleStateIfMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.GambleState), args[3].(domain.GambleState))
	})
	return _c
}

func (_c *MockRepositoryGambleTx_UpdateGambleStateIfMatches_Call) Return(_a0 int64, _a1 error) *MockRepositoryGambleTx_UpdateGambleStateIfMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryGambleTx_UpdateGambleStateIfMatches_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.GambleState, domain.GambleState) (int64, error)) *MockRepositoryGambleTx_UpdateGambleStateIfMatches_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInventory provides a mock function with given fields: ctx, userID, inventory
func (_m *MockRepositoryGambleTx) UpdateInventory(ctx context.Context, userID string, inventory domain.Inventory) error {
	ret := _m.Called(ctx, userID, inventory)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Inventory) error); ok {
		r0 = rf(ctx, userID, inventory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryGambleTx_UpdateInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInventory'
type MockRepositoryGambleTx_UpdateInventory_Call struct {
	*mock.Call
}

// UpdateInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inventory domain.Inventory
func (_e *MockRepositoryGambleTx_Expecter) UpdateInventory(ctx interface{}, userID interface{}, inventory interface{}) *MockRepositoryGambleTx_UpdateInventory_Call {
	return &MockRepositoryGambleTx_UpdateInventory_Call{Call: _e.mock.On("UpdateInventory", ctx, userID, inventory)}
}

func (_c *MockRepositoryGambleTx_UpdateInventory_Call) Run(run func(ctx context.Context, userID string, inventory domain.Inventory)) *MockRepositoryGambleTx_UpdateInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Inventory))
	})
	return _c
}

func (_c *MockRepositoryGambleTx_UpdateInventory_Call) Return(_a0 error) *MockRepositoryGambleTx_UpdateInventory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryGambleTx_UpdateInventory_Call) RunAndReturn(run func(context.Context, string, domain.Inventory) error) *MockRepositoryGambleTx_UpdateInventory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryGambleTx creates a new instance of MockRepositoryGambleTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryGambleTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryGambleTx {
	mock := &MockRepositoryGambleTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
