// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/osse101/BrandishBot_Go/internal/event"

	mock "github.com/stretchr/testify/mock"
)

// MockEventlogService is an autogenerated mock type for the Service type
type MockEventlogService struct {
	mock.Mock
}

type MockEventlogService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventlogService) EXPECT() *MockEventlogService_Expecter {
	return &MockEventlogService_Expecter{mock: &_m.Mock}
}

// CleanupOldEvents provides a mock function with given fields: ctx, retentionDays
func (_m *MockEventlogService) CleanupOldEvents(ctx context.Context, retentionDays int) (int64, error) {
	ret := _m.Called(ctx, retentionDays)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOldEvents")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return rf(ctx, retentionDays)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, retentionDays)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, retentionDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventlogService_CleanupOldEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupOldEvents'
type MockEventlogService_CleanupOldEvents_Call struct {
	*mock.Call
}

// CleanupOldEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - retentionDays int
func (_e *MockEventlogService_Expecter) CleanupOldEvents(ctx interface{}, retentionDays interface{}) *MockEventlogService_CleanupOldEvents_Call {
	return &MockEventlogService_CleanupOldEvents_Call{Call: _e.mock.On("CleanupOldEvents", ctx, retentionDays)}
}

func (_c *MockEventlogService_CleanupOldEvents_Call) Run(run func(ctx context.Context, retentionDays int)) *MockEventlogService_CleanupOldEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockEventlogService_CleanupOldEvents_Call) Return(_a0 int64, _a1 error) *MockEventlogService_CleanupOldEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventlogService_CleanupOldEvents_Call) RunAndReturn(run func(context.Context, int) (int64, error)) *MockEventlogService_CleanupOldEvents_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: bus
func (_m *MockEventlogService) Subscribe(bus event.Bus) error {
	ret := _m.Called(bus)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(event.Bus) error); ok {
		r0 = rf(bus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventlogService_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventlogService_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - bus event.Bus
func (_e *MockEventlogService_Expecter) Subscribe(bus interface{}) *MockEventlogService_Subscribe_Call {
	return &MockEventlogService_Subscribe_Call{Call: _e.mock.On("Subscribe", bus)}
}

func (_c *MockEventlogService_Subscribe_Call) Run(run func(bus event.Bus)) *MockEventlogService_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(event.Bus))
	})
	return _c
}

func (_c *MockEventlogService_Subscribe_Call) Return(_a0 error) *MockEventlogService_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventlogService_Subscribe_Call) RunAndReturn(run func(event.Bus) error) *MockEventlogService_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventlogService creates a new instance of MockEventlogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventlogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventlogService {
	mock := &MockEventlogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
