// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/osse101/BrandishBot_Go/internal/repository"

	time "time"
)

// MockRepositoryUser is an autogenerated mock type for the User type
type MockRepositoryUser struct {
	mock.Mock
}

type MockRepositoryUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryUser) EXPECT() *MockRepositoryUser_Expecter {
	return &MockRepositoryUser_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx
func (_m *MockRepositoryUser) BeginTx(ctx context.Context) (repository.UserTx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.UserTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.UserTx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.UserTx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockRepositoryUser_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryUser_Expecter) BeginTx(ctx interface{}) *MockRepositoryUser_BeginTx_Call {
	return &MockRepositoryUser_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockRepositoryUser_BeginTx_Call) Run(run func(ctx context.Context)) *MockRepositoryUser_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryUser_BeginTx_Call) Return(_a0 repository.UserTx, _a1 error) *MockRepositoryUser_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_BeginTx_Call) RunAndReturn(run func(context.Context) (repository.UserTx, error)) *MockRepositoryUser_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInventory provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryUser) DeleteInventory(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryUser_DeleteInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInventory'
type MockRepositoryUser_DeleteInventory_Call struct {
	*mock.Call
}

// DeleteInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryUser_Expecter) DeleteInventory(ctx interface{}, userID interface{}) *MockRepositoryUser_DeleteInventory_Call {
	return &MockRepositoryUser_DeleteInventory_Call{Call: _e.mock.On("DeleteInventory", ctx, userID)}
}

func (_c *MockRepositoryUser_DeleteInventory_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryUser_DeleteInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryUser_DeleteInventory_Call) Return(_a0 error) *MockRepositoryUser_DeleteInventory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryUser_DeleteInventory_Call) RunAndReturn(run func(context.Context, string) error) *MockRepositoryUser_DeleteInventory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryUser) DeleteUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryUser_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockRepositoryUser_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryUser_Expecter) DeleteUser(ctx interface{}, userID interface{}) *MockRepositoryUser_DeleteUser_Call {
	return &MockRepositoryUser_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userID)}
}

func (_c *MockRepositoryUser_DeleteUser_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryUser_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryUser_DeleteUser_Call) Return(_a0 error) *MockRepositoryUser_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryUser_DeleteUser_Call) RunAndReturn(run func(context.Context, string) error) *MockRepositoryUser_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllItems provides a mock function with given fields: ctx
func (_m *MockRepositoryUser) GetAllItems(ctx context.Context) ([]domain.Item, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllItems")
	}

	var r0 []domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Item, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Item); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetAllItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllItems'
type MockRepositoryUser_GetAllItems_Call struct {
	*mock.Call
}

// GetAllItems is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryUser_Expecter) GetAllItems(ctx interface{}) *MockRepositoryUser_GetAllItems_Call {
	return &MockRepositoryUser_GetAllItems_Call{Call: _e.mock.On("GetAllItems", ctx)}
}

func (_c *MockRepositoryUser_GetAllItems_Call) Run(run func(ctx context.Context)) *MockRepositoryUser_GetAllItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryUser_GetAllItems_Call) Return(_a0 []domain.Item, _a1 error) *MockRepositoryUser_GetAllItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetAllItems_Call) RunAndReturn(run func(context.Context) ([]domain.Item, error)) *MockRepositoryUser_GetAllItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetInventory provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryUser) GetInventory(ctx context.Context, userID string) (*domain.Inventory, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 *domain.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Inventory, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Inventory); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventory'
type MockRepositoryUser_GetInventory_Call struct {
	*mock.Call
}

// GetInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryUser_Expecter) GetInventory(ctx interface{}, userID interface{}) *MockRepositoryUser_GetInventory_Call {
	return &MockRepositoryUser_GetInventory_Call{Call: _e.mock.On("GetInventory", ctx, userID)}
}

func (_c *MockRepositoryUser_GetInventory_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryUser_GetInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryUser_GetInventory_Call) Return(_a0 *domain.Inventory, _a1 error) *MockRepositoryUser_GetInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetInventory_Call) RunAndReturn(run func(context.Context, string) (*domain.Inventory, error)) *MockRepositoryUser_GetInventory_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByID provides a mock function with given fields: ctx, id
func (_m *MockRepositoryUser) GetItemByID(ctx context.Context, id int) (*domain.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByID'
type MockRepositoryUser_GetItemByID_Call struct {
	*mock.Call
}

// GetItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepositoryUser_Expecter) GetItemByID(ctx interface{}, id interface{}) *MockRepositoryUser_GetItemByID_Call {
	return &MockRepositoryUser_GetItemByID_Call{Call: _e.mock.On("GetItemByID", ctx, id)}
}

func (_c *MockRepositoryUser_GetItemByID_Call) Run(run func(ctx context.Context, id int)) *MockRepositoryUser_GetItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepositoryUser_GetItemByID_Call) Return(_a0 *domain.Item, _a1 error) *MockRepositoryUser_GetItemByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetItemByID_Call) RunAndReturn(run func(context.Context, int) (*domain.Item, error)) *MockRepositoryUser_GetItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByName provides a mock function with given fields: ctx, itemName
func (_m *MockRepositoryUser) GetItemByName(ctx context.Context, itemName string) (*domain.Item, error) {
	ret := _m.Called(ctx, itemName)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByName")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Item, error)); ok {
		return rf(ctx, itemName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Item); ok {
		r0 = rf(ctx, itemName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, itemName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetItemByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByName'
type MockRepositoryUser_GetItemByName_Call struct {
	*mock.Call
}

// GetItemByName is a helper method to define mock.On call
//   - ctx context.Context
//   - itemName string
func (_e *MockRepositoryUser_Expecter) GetItemByName(ctx interface{}, itemName interface{}) *MockRepositoryUser_GetItemByName_Call {
	return &MockRepositoryUser_GetItemByName_Call{Call: _e.mock.On("GetItemByName", ctx, itemName)}
}

func (_c *MockRepositoryUser_GetItemByName_Call) Run(run func(ctx context.Context, itemName string)) *MockRepositoryUser_GetItemByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryUser_GetItemByName_Call) Return(_a0 *domain.Item, _a1 error) *MockRepositoryUser_GetItemByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetItemByName_Call) RunAndReturn(run func(context.Context, string) (*domain.Item, error)) *MockRepositoryUser_GetItemByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemsByIDs provides a mock function with given fields: ctx, itemIDs
func (_m *MockRepositoryUser) GetItemsByIDs(ctx context.Context, itemIDs []int) ([]domain.Item, error) {
	ret := _m.Called(ctx, itemIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetItemsByIDs")
	}

	var r0 []domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) ([]domain.Item, error)); ok {
		return rf(ctx, itemIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int) []domain.Item); ok {
		r0 = rf(ctx, itemIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, itemIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetItemsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemsByIDs'
type MockRepositoryUser_GetItemsByIDs_Call struct {
	*mock.Call
}

// GetItemsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - itemIDs []int
func (_e *MockRepositoryUser_Expecter) GetItemsByIDs(ctx interface{}, itemIDs interface{}) *MockRepositoryUser_GetItemsByIDs_Call {
	return &MockRepositoryUser_GetItemsByIDs_Call{Call: _e.mock.On("GetItemsByIDs", ctx, itemIDs)}
}

func (_c *MockRepositoryUser_GetItemsByIDs_Call) Run(run func(ctx context.Context, itemIDs []int)) *MockRepositoryUser_GetItemsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int))
	})
	return _c
}

func (_c *MockRepositoryUser_GetItemsByIDs_Call) Return(_a0 []domain.Item, _a1 error) *MockRepositoryUser_GetItemsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetItemsByIDs_Call) RunAndReturn(run func(context.Context, []int) ([]domain.Item, error)) *MockRepositoryUser_GetItemsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemsByNames provides a mock function with given fields: ctx, names
func (_m *MockRepositoryUser) GetItemsByNames(ctx context.Context, names []string) ([]domain.Item, error) {
	ret := _m.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for GetItemsByNames")
	}

	var r0 []domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]domain.Item, error)); ok {
		return rf(ctx, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []domain.Item); ok {
		r0 = rf(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, names)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetItemsByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemsByNames'
type MockRepositoryUser_GetItemsByNames_Call struct {
	*mock.Call
}

// GetItemsByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
func (_e *MockRepositoryUser_Expecter) GetItemsByNames(ctx interface{}, names interface{}) *MockRepositoryUser_GetItemsByNames_Call {
	return &MockRepositoryUser_GetItemsByNames_Call{Call: _e.mock.On("GetItemsByNames", ctx, names)}
}

func (_c *MockRepositoryUser_GetItemsByNames_Call) Run(run func(ctx context.Context, names []string)) *MockRepositoryUser_GetItemsByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockRepositoryUser_GetItemsByNames_Call) Return(_a0 []domain.Item, _a1 error) *MockRepositoryUser_GetItemsByNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetItemsByNames_Call) RunAndReturn(run func(context.Context, []string) ([]domain.Item, error)) *MockRepositoryUser_GetItemsByNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastCooldown provides a mock function with given fields: ctx, userID, action
func (_m *MockRepositoryUser) GetLastCooldown(ctx context.Context, userID string, action string) (*time.Time, error) {
	ret := _m.Called(ctx, userID, action)

	if len(ret) == 0 {
		panic("no return value specified for GetLastCooldown")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*time.Time, error)); ok {
		return rf(ctx, userID, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *time.Time); ok {
		r0 = rf(ctx, userID, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetLastCooldown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastCooldown'
type MockRepositoryUser_GetLastCooldown_Call struct {
	*mock.Call
}

// GetLastCooldown is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - action string
func (_e *MockRepositoryUser_Expecter) GetLastCooldown(ctx interface{}, userID interface{}, action interface{}) *MockRepositoryUser_GetLastCooldown_Call {
	return &MockRepositoryUser_GetLastCooldown_Call{Call: _e.mock.On("GetLastCooldown", ctx, userID, action)}
}

func (_c *MockRepositoryUser_GetLastCooldown_Call) Run(run func(ctx context.Context, userID string, action string)) *MockRepositoryUser_GetLastCooldown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepositoryUser_GetLastCooldown_Call) Return(_a0 *time.Time, _a1 error) *MockRepositoryUser_GetLastCooldown_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetLastCooldown_Call) RunAndReturn(run func(context.Context, string, string) (*time.Time, error)) *MockRepositoryUser_GetLastCooldown_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentlyActiveUsers provides a mock function with given fields: ctx, limit
func (_m *MockRepositoryUser) GetRecentlyActiveUsers(ctx context.Context, limit int) ([]domain.User, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentlyActiveUsers")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.User, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.User); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetRecentlyActiveUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentlyActiveUsers'
type MockRepositoryUser_GetRecentlyActiveUsers_Call struct {
	*mock.Call
}

// GetRecentlyActiveUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockRepositoryUser_Expecter) GetRecentlyActiveUsers(ctx interface{}, limit interface{}) *MockRepositoryUser_GetRecentlyActiveUsers_Call {
	return &MockRepositoryUser_GetRecentlyActiveUsers_Call{Call: _e.mock.On("GetRecentlyActiveUsers", ctx, limit)}
}

func (_c *MockRepositoryUser_GetRecentlyActiveUsers_Call) Run(run func(ctx context.Context, limit int)) *MockRepositoryUser_GetRecentlyActiveUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepositoryUser_GetRecentlyActiveUsers_Call) Return(_a0 []domain.User, _a1 error) *MockRepositoryUser_GetRecentlyActiveUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetRecentlyActiveUsers_Call) RunAndReturn(run func(context.Context, int) ([]domain.User, error)) *MockRepositoryUser_GetRecentlyActiveUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryUser) GetUserByID(ctx context.Context, userID string) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockRepositoryUser_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryUser_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockRepositoryUser_GetUserByID_Call {
	return &MockRepositoryUser_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockRepositoryUser_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryUser_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryUser_GetUserByID_Call) Return(_a0 *domain.User, _a1 error) *MockRepositoryUser_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockRepositoryUser_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByPlatformID provides a mock function with given fields: ctx, platform, platformID
func (_m *MockRepositoryUser) GetUserByPlatformID(ctx context.Context, platform string, platformID string) (*domain.User, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByPlatformID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetUserByPlatformID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPlatformID'
type MockRepositoryUser_GetUserByPlatformID_Call struct {
	*mock.Call
}

// GetUserByPlatformID is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockRepositoryUser_Expecter) GetUserByPlatformID(ctx interface{}, platform interface{}, platformID interface{}) *MockRepositoryUser_GetUserByPlatformID_Call {
	return &MockRepositoryUser_GetUserByPlatformID_Call{Call: _e.mock.On("GetUserByPlatformID", ctx, platform, platformID)}
}

func (_c *MockRepositoryUser_GetUserByPlatformID_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockRepositoryUser_GetUserByPlatformID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepositoryUser_GetUserByPlatformID_Call) Return(_a0 *domain.User, _a1 error) *MockRepositoryUser_GetUserByPlatformID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetUserByPlatformID_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockRepositoryUser_GetUserByPlatformID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByPlatformUsername provides a mock function with given fields: ctx, platform, username
func (_m *MockRepositoryUser) GetUserByPlatformUsername(ctx context.Context, platform string, username string) (*domain.User, error) {
	ret := _m.Called(ctx, platform, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByPlatformUsername")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, platform, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, platform, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryUser_GetUserByPlatformUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPlatformUsername'
type MockRepositoryUser_GetUserByPlatformUsername_Call struct {
	*mock.Call
}

// GetUserByPlatformUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - username string
func (_e *MockRepositoryUser_Expecter) GetUserByPlatformUsername(ctx interface{}, platform interface{}, username interface{}) *MockRepositoryUser_GetUserByPlatformUsername_Call {
	return &MockRepositoryUser_GetUserByPlatformUsername_Call{Call: _e.mock.On("GetUserByPlatformUsername", ctx, platform, username)}
}

func (_c *MockRepositoryUser_GetUserByPlatformUsername_Call) Run(run func(ctx context.Context, platform string, username string)) *MockRepositoryUser_GetUserByPlatformUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepositoryUser_GetUserByPlatformUsername_Call) Return(_a0 *domain.User, _a1 error) *MockRepositoryUser_GetUserByPlatformUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryUser_GetUserByPlatformUsername_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockRepositoryUser_GetUserByPlatformUsername_Call {
	_c.Call.Return(run)
	return _c
}

// MergeUsersInTransaction provides a mock function with given fields: ctx, primaryUserID, secondaryUserID, mergedUser, mergedInventory
func (_m *MockRepositoryUser) MergeUsersInTransaction(ctx context.Context, primaryUserID string, secondaryUserID string, mergedUser domain.User, mergedInventory domain.Inventory) error {
	ret := _m.Called(ctx, primaryUserID, secondaryUserID, mergedUser, mergedInventory)

	if len(ret) == 0 {
		panic("no return value specified for MergeUsersInTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.User, domain.Inventory) error); ok {
		r0 = rf(ctx, primaryUserID, secondaryUserID, mergedUser, mergedInventory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryUser_MergeUsersInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeUsersInTransaction'
type MockRepositoryUser_MergeUsersInTransaction_Call struct {
	*mock.Call
}

// MergeUsersInTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - primaryUserID string
//   - secondaryUserID string
//   - mergedUser domain.User
//   - mergedInventory domain.Inventory
func (_e *MockRepositoryUser_Expecter) MergeUsersInTransaction(ctx interface{}, primaryUserID interface{}, secondaryUserID interface{}, mergedUser interface{}, mergedInventory interface{}) *MockRepositoryUser_MergeUsersInTransaction_Call {
	return &MockRepositoryUser_MergeUsersInTransaction_Call{Call: _e.mock.On("MergeUsersInTransaction", ctx, primaryUserID, secondaryUserID, mergedUser, mergedInventory)}
}

func (_c *MockRepositoryUser_MergeUsersInTransaction_Call) Run(run func(ctx context.Context, primaryUserID string, secondaryUserID string, mergedUser domain.User, mergedInventory domain.Inventory)) *MockRepositoryUser_MergeUsersInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(domain.User), args[4].(domain.Inventory))
	})
	return _c
}

func (_c *MockRepositoryUser_MergeUsersInTransaction_Call) Return(_a0 error) *MockRepositoryUser_MergeUsersInTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryUser_MergeUsersInTransaction_Call) RunAndReturn(run func(context.Context, string, string, domain.User, domain.Inventory) error) *MockRepositoryUser_MergeUsersInTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCooldown provides a mock function with given fields: ctx, userID, action, timestamp
func (_m *MockRepositoryUser) UpdateCooldown(ctx context.Context, userID string, action string, timestamp time.Time) error {
	ret := _m.Called(ctx, userID, action, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCooldown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, userID, action, timestamp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryUser_UpdateCooldown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCooldown'
type MockRepositoryUser_UpdateCooldown_Call struct {
	*mock.Call
}

// UpdateCooldown is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - action string
//   - timestamp time.Time
func (_e *MockRepositoryUser_Expecter) UpdateCooldown(ctx interface{}, userID interface{}, action interface{}, timestamp interface{}) *MockRepositoryUser_UpdateCooldown_Call {
	return &MockRepositoryUser_UpdateCooldown_Call{Call: _e.mock.On("UpdateCooldown", ctx, userID, action, timestamp)}
}

func (_c *MockRepositoryUser_UpdateCooldown_Call) Run(run func(ctx context.Context, userID string, action string, timestamp time.Time)) *MockRepositoryUser_UpdateCooldown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepositoryUser_UpdateCooldown_Call) Return(_a0 error) *MockRepositoryUser_UpdateCooldown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryUser_UpdateCooldown_Call) RunAndReturn(run func(context.Context, string, string, time.Time) error) *MockRepositoryUser_UpdateCooldown_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInventory provides a mock function with given fields: ctx, userID, inventory
func (_m *MockRepositoryUser) UpdateInventory(ctx context.Context, userID string, inventory domain.Inventory) error {
	ret := _m.Called(ctx, userID, inventory)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Inventory) error); ok {
		r0 = rf(ctx, userID, inventory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryUser_UpdateInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInventory'
type MockRepositoryUser_UpdateInventory_Call struct {
	*mock.Call
}

// UpdateInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inventory domain.Inventory
func (_e *MockRepositoryUser_Expecter) UpdateInventory(ctx interface{}, userID interface{}, inventory interface{}) *MockRepositoryUser_UpdateInventory_Call {
	return &MockRepositoryUser_UpdateInventory_Call{Call: _e.mock.On("UpdateInventory", ctx, userID, inventory)}
}

func (_c *MockRepositoryUser_UpdateInventory_Call) Run(run func(ctx context.Context, userID string, inventory domain.Inventory)) *MockRepositoryUser_UpdateInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Inventory))
	})
	return _c
}

func (_c *MockRepositoryUser_UpdateInventory_Call) Return(_a0 error) *MockRepositoryUser_UpdateInventory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryUser_UpdateInventory_Call) RunAndReturn(run func(context.Context, string, domain.Inventory) error) *MockRepositoryUser_UpdateInventory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *MockRepositoryUser) UpdateUser(ctx context.Context, user domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryUser_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockRepositoryUser_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockRepositoryUser_Expecter) UpdateUser(ctx interface{}, user interface{}) *MockRepositoryUser_UpdateUser_Call {
	return &MockRepositoryUser_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *MockRepositoryUser_UpdateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockRepositoryUser_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockRepositoryUser_UpdateUser_Call) Return(_a0 error) *MockRepositoryUser_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryUser_UpdateUser_Call) RunAndReturn(run func(context.Context, domain.User) error) *MockRepositoryUser_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUser provides a mock function with given fields: ctx, user
func (_m *MockRepositoryUser) UpsertUser(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryUser_UpsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUser'
type MockRepositoryUser_UpsertUser_Call struct {
	*mock.Call
}

// UpsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockRepositoryUser_Expecter) UpsertUser(ctx interface{}, user interface{}) *MockRepositoryUser_UpsertUser_Call {
	return &MockRepositoryUser_UpsertUser_Call{Call: _e.mock.On("UpsertUser", ctx, user)}
}

func (_c *MockRepositoryUser_UpsertUser_Call) Run(run func(ctx context.Context, user *domain.User)) *MockRepositoryUser_UpsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockRepositoryUser_UpsertUser_Call) Return(_a0 error) *MockRepositoryUser_UpsertUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryUser_UpsertUser_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockRepositoryUser_UpsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryUser creates a new instance of MockRepositoryUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryUser {
	mock := &MockRepositoryUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
