// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
)

// MockJobService is an autogenerated mock type for the Service type
type MockJobService struct {
	mock.Mock
}

type MockJobService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobService) EXPECT() *MockJobService_Expecter {
	return &MockJobService_Expecter{mock: &_m.Mock}
}

// AwardXP provides a mock function with given fields: ctx, userID, jobKey, baseAmount, source, metadata
func (_m *MockJobService) AwardXP(ctx context.Context, userID string, jobKey string, baseAmount int, source string, metadata map[string]interface{}) (*domain.XPAwardResult, error) {
	ret := _m.Called(ctx, userID, jobKey, baseAmount, source, metadata)

	if len(ret) == 0 {
		panic("no return value specified for AwardXP")
	}

	var r0 *domain.XPAwardResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string, map[string]interface{}) (*domain.XPAwardResult, error)); ok {
		return rf(ctx, userID, jobKey, baseAmount, source, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string, map[string]interface{}) *domain.XPAwardResult); ok {
		r0 = rf(ctx, userID, jobKey, baseAmount, source, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.XPAwardResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, userID, jobKey, baseAmount, source, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobService_AwardXP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AwardXP'
type MockJobService_AwardXP_Call struct {
	*mock.Call
}

// AwardXP is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - jobKey string
//   - baseAmount int
//   - source string
//   - metadata map[string]interface{}
func (_e *MockJobService_Expecter) AwardXP(ctx interface{}, userID interface{}, jobKey interface{}, baseAmount interface{}, source interface{}, metadata interface{}) *MockJobService_AwardXP_Call {
	return &MockJobService_AwardXP_Call{Call: _e.mock.On("AwardXP", ctx, userID, jobKey, baseAmount, source, metadata)}
}

func (_c *MockJobService_AwardXP_Call) Run(run func(ctx context.Context, userID string, jobKey string, baseAmount int, source string, metadata map[string]interface{})) *MockJobService_AwardXP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(string), args[5].(map[string]interface{}))
	})
	return _c
}

func (_c *MockJobService_AwardXP_Call) Return(_a0 *domain.XPAwardResult, _a1 error) *MockJobService_AwardXP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobService_AwardXP_Call) RunAndReturn(run func(context.Context, string, string, int, string, map[string]interface{}) (*domain.XPAwardResult, error)) *MockJobService_AwardXP_Call {
	_c.Call.Return(run)
	return _c
}

// CalculateLevel provides a mock function with given fields: totalXP
func (_m *MockJobService) CalculateLevel(totalXP int64) int {
	ret := _m.Called(totalXP)

	if len(ret) == 0 {
		panic("no return value specified for CalculateLevel")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int64) int); ok {
		r0 = rf(totalXP)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockJobService_CalculateLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateLevel'
type MockJobService_CalculateLevel_Call struct {
	*mock.Call
}

// CalculateLevel is a helper method to define mock.On call
//   - totalXP int64
func (_e *MockJobService_Expecter) CalculateLevel(totalXP interface{}) *MockJobService_CalculateLevel_Call {
	return &MockJobService_CalculateLevel_Call{Call: _e.mock.On("CalculateLevel", totalXP)}
}

func (_c *MockJobService_CalculateLevel_Call) Run(run func(totalXP int64)) *MockJobService_CalculateLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockJobService_CalculateLevel_Call) Return(_a0 int) *MockJobService_CalculateLevel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobService_CalculateLevel_Call) RunAndReturn(run func(int64) int) *MockJobService_CalculateLevel_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllJobs provides a mock function with given fields: ctx
func (_m *MockJobService) GetAllJobs(ctx context.Context) ([]domain.Job, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllJobs")
	}

	var r0 []domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Job, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Job); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobService_GetAllJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllJobs'
type MockJobService_GetAllJobs_Call struct {
	*mock.Call
}

// GetAllJobs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockJobService_Expecter) GetAllJobs(ctx interface{}) *MockJobService_GetAllJobs_Call {
	return &MockJobService_GetAllJobs_Call{Call: _e.mock.On("GetAllJobs", ctx)}
}

func (_c *MockJobService_GetAllJobs_Call) Run(run func(ctx context.Context)) *MockJobService_GetAllJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockJobService_GetAllJobs_Call) Return(_a0 []domain.Job, _a1 error) *MockJobService_GetAllJobs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobService_GetAllJobs_Call) RunAndReturn(run func(context.Context) ([]domain.Job, error)) *MockJobService_GetAllJobs_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobBonus provides a mock function with given fields: ctx, userID, jobKey, bonusType
func (_m *MockJobService) GetJobBonus(ctx context.Context, userID string, jobKey string, bonusType string) (float64, error) {
	ret := _m.Called(ctx, userID, jobKey, bonusType)

	if len(ret) == 0 {
		panic("no return value specified for GetJobBonus")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (float64, error)); ok {
		return rf(ctx, userID, jobKey, bonusType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) float64); ok {
		r0 = rf(ctx, userID, jobKey, bonusType)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, jobKey, bonusType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobService_GetJobBonus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobBonus'
type MockJobService_GetJobBonus_Call struct {
	*mock.Call
}

// GetJobBonus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - jobKey string
//   - bonusType string
func (_e *MockJobService_Expecter) GetJobBonus(ctx interface{}, userID interface{}, jobKey interface{}, bonusType interface{}) *MockJobService_GetJobBonus_Call {
	return &MockJobService_GetJobBonus_Call{Call: _e.mock.On("GetJobBonus", ctx, userID, jobKey, bonusType)}
}

func (_c *MockJobService_GetJobBonus_Call) Run(run func(ctx context.Context, userID string, jobKey string, bonusType string)) *MockJobService_GetJobBonus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockJobService_GetJobBonus_Call) Return(_a0 float64, _a1 error) *MockJobService_GetJobBonus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobService_GetJobBonus_Call) RunAndReturn(run func(context.Context, string, string, string) (float64, error)) *MockJobService_GetJobBonus_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobLevel provides a mock function with given fields: ctx, userID, jobKey
func (_m *MockJobService) GetJobLevel(ctx context.Context, userID string, jobKey string) (int, error) {
	ret := _m.Called(ctx, userID, jobKey)

	if len(ret) == 0 {
		panic("no return value specified for GetJobLevel")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int, error)); ok {
		return rf(ctx, userID, jobKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = rf(ctx, userID, jobKey)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, jobKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobService_GetJobLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobLevel'
type MockJobService_GetJobLevel_Call struct {
	*mock.Call
}

// GetJobLevel is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - jobKey string
func (_e *MockJobService_Expecter) GetJobLevel(ctx interface{}, userID interface{}, jobKey interface{}) *MockJobService_GetJobLevel_Call {
	return &MockJobService_GetJobLevel_Call{Call: _e.mock.On("GetJobLevel", ctx, userID, jobKey)}
}

func (_c *MockJobService_GetJobLevel_Call) Run(run func(ctx context.Context, userID string, jobKey string)) *MockJobService_GetJobLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockJobService_GetJobLevel_Call) Return(_a0 int, _a1 error) *MockJobService_GetJobLevel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobService_GetJobLevel_Call) RunAndReturn(run func(context.Context, string, string) (int, error)) *MockJobService_GetJobLevel_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrimaryJob provides a mock function with given fields: ctx, userID
func (_m *MockJobService) GetPrimaryJob(ctx context.Context, userID string) (*domain.UserJobInfo, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrimaryJob")
	}

	var r0 *domain.UserJobInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserJobInfo, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserJobInfo); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserJobInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobService_GetPrimaryJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrimaryJob'
type MockJobService_GetPrimaryJob_Call struct {
	*mock.Call
}

// GetPrimaryJob is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockJobService_Expecter) GetPrimaryJob(ctx interface{}, userID interface{}) *MockJobService_GetPrimaryJob_Call {
	return &MockJobService_GetPrimaryJob_Call{Call: _e.mock.On("GetPrimaryJob", ctx, userID)}
}

func (_c *MockJobService_GetPrimaryJob_Call) Run(run func(ctx context.Context, userID string)) *MockJobService_GetPrimaryJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockJobService_GetPrimaryJob_Call) Return(_a0 *domain.UserJobInfo, _a1 error) *MockJobService_GetPrimaryJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobService_GetPrimaryJob_Call) RunAndReturn(run func(context.Context, string) (*domain.UserJobInfo, error)) *MockJobService_GetPrimaryJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserJobs provides a mock function with given fields: ctx, userID
func (_m *MockJobService) GetUserJobs(ctx context.Context, userID string) ([]domain.UserJobInfo, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserJobs")
	}

	var r0 []domain.UserJobInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.UserJobInfo, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.UserJobInfo); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserJobInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobService_GetUserJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserJobs'
type MockJobService_GetUserJobs_Call struct {
	*mock.Call
}

// GetUserJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockJobService_Expecter) GetUserJobs(ctx interface{}, userID interface{}) *MockJobService_GetUserJobs_Call {
	return &MockJobService_GetUserJobs_Call{Call: _e.mock.On("GetUserJobs", ctx, userID)}
}

func (_c *MockJobService_GetUserJobs_Call) Run(run func(ctx context.Context, userID string)) *MockJobService_GetUserJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockJobService_GetUserJobs_Call) Return(_a0 []domain.UserJobInfo, _a1 error) *MockJobService_GetUserJobs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobService_GetUserJobs_Call) RunAndReturn(run func(context.Context, string) ([]domain.UserJobInfo, error)) *MockJobService_GetUserJobs_Call {
	_c.Call.Return(run)
	return _c
}

// GetXPForLevel provides a mock function with given fields: level
func (_m *MockJobService) GetXPForLevel(level int) int64 {
	ret := _m.Called(level)

	if len(ret) == 0 {
		panic("no return value specified for GetXPForLevel")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(int) int64); ok {
		r0 = rf(level)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockJobService_GetXPForLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetXPForLevel'
type MockJobService_GetXPForLevel_Call struct {
	*mock.Call
}

// GetXPForLevel is a helper method to define mock.On call
//   - level int
func (_e *MockJobService_Expecter) GetXPForLevel(level interface{}) *MockJobService_GetXPForLevel_Call {
	return &MockJobService_GetXPForLevel_Call{Call: _e.mock.On("GetXPForLevel", level)}
}

func (_c *MockJobService_GetXPForLevel_Call) Run(run func(level int)) *MockJobService_GetXPForLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockJobService_GetXPForLevel_Call) Return(_a0 int64) *MockJobService_GetXPForLevel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobService_GetXPForLevel_Call) RunAndReturn(run func(int) int64) *MockJobService_GetXPForLevel_Call {
	_c.Call.Return(run)
	return _c
}

// GetXPProgress provides a mock function with given fields: currentXP
func (_m *MockJobService) GetXPProgress(currentXP int64) (int, int64) {
	ret := _m.Called(currentXP)

	if len(ret) == 0 {
		panic("no return value specified for GetXPProgress")
	}

	var r0 int
	var r1 int64
	if rf, ok := ret.Get(0).(func(int64) (int, int64)); ok {
		return rf(currentXP)
	}
	if rf, ok := ret.Get(0).(func(int64) int); ok {
		r0 = rf(currentXP)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int64) int64); ok {
		r1 = rf(currentXP)
	} else {
		r1 = ret.Get(1).(int64)
	}

	return r0, r1
}

// MockJobService_GetXPProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetXPProgress'
type MockJobService_GetXPProgress_Call struct {
	*mock.Call
}

// GetXPProgress is a helper method to define mock.On call
//   - currentXP int64
func (_e *MockJobService_Expecter) GetXPProgress(currentXP interface{}) *MockJobService_GetXPProgress_Call {
	return &MockJobService_GetXPProgress_Call{Call: _e.mock.On("GetXPProgress", currentXP)}
}

func (_c *MockJobService_GetXPProgress_Call) Run(run func(currentXP int64)) *MockJobService_GetXPProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockJobService_GetXPProgress_Call) Return(currentLevel int, xpToNext int64) *MockJobService_GetXPProgress_Call {
	_c.Call.Return(currentLevel, xpToNext)
	return _c
}

func (_c *MockJobService_GetXPProgress_Call) RunAndReturn(run func(int64) (int, int64)) *MockJobService_GetXPProgress_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobService creates a new instance of MockJobService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobService {
	mock := &MockJobService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
