// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDBPool is an autogenerated mock type for the Pool type
type MockDBPool struct {
	mock.Mock
}

type MockDBPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBPool) EXPECT() *MockDBPool_Expecter {
	return &MockDBPool_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockDBPool) Close() {
	_m.Called()
}

// MockDBPool_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDBPool_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDBPool_Expecter) Close() *MockDBPool_Close_Call {
	return &MockDBPool_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDBPool_Close_Call) Run(run func()) *MockDBPool_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBPool_Close_Call) Return() *MockDBPool_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDBPool_Close_Call) RunAndReturn(run func()) *MockDBPool_Close_Call {
	_c.Run(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockDBPool) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDBPool_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDBPool_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDBPool_Expecter) Ping(ctx interface{}) *MockDBPool_Ping_Call {
	return &MockDBPool_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockDBPool_Ping_Call) Run(run func(ctx context.Context)) *MockDBPool_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDBPool_Ping_Call) Return(_a0 error) *MockDBPool_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBPool_Ping_Call) RunAndReturn(run func(context.Context) error) *MockDBPool_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBPool creates a new instance of MockDBPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBPool {
	mock := &MockDBPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
