// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/osse101/BrandishBot_Go/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockEventLogRepository is an autogenerated mock type for the EventLog type
type MockEventLogRepository struct {
	mock.Mock
}

type MockEventLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventLogRepository) EXPECT() *MockEventLogRepository_Expecter {
	return &MockEventLogRepository_Expecter{mock: &_m.Mock}
}

// CleanupOldEvents provides a mock function with given fields: ctx, retentionDays
func (_m *MockEventLogRepository) CleanupOldEvents(ctx context.Context, retentionDays int) (int64, error) {
	ret := _m.Called(ctx, retentionDays)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOldEvents")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return rf(ctx, retentionDays)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, retentionDays)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, retentionDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventLogRepository_CleanupOldEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupOldEvents'
type MockEventLogRepository_CleanupOldEvents_Call struct {
	*mock.Call
}

// CleanupOldEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - retentionDays int
func (_e *MockEventLogRepository_Expecter) CleanupOldEvents(ctx interface{}, retentionDays interface{}) *MockEventLogRepository_CleanupOldEvents_Call {
	return &MockEventLogRepository_CleanupOldEvents_Call{Call: _e.mock.On("CleanupOldEvents", ctx, retentionDays)}
}

func (_c *MockEventLogRepository_CleanupOldEvents_Call) Run(run func(ctx context.Context, retentionDays int)) *MockEventLogRepository_CleanupOldEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockEventLogRepository_CleanupOldEvents_Call) Return(_a0 int64, _a1 error) *MockEventLogRepository_CleanupOldEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventLogRepository_CleanupOldEvents_Call) RunAndReturn(run func(context.Context, int) (int64, error)) *MockEventLogRepository_CleanupOldEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvents provides a mock function with given fields: ctx, filter
func (_m *MockEventLogRepository) GetEvents(ctx context.Context, filter repository.EventLogFilter) ([]repository.EventLogEntry, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 []repository.EventLogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.EventLogFilter) ([]repository.EventLogEntry, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.EventLogFilter) []repository.EventLogEntry); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.EventLogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.EventLogFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventLogRepository_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type MockEventLogRepository_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.EventLogFilter
func (_e *MockEventLogRepository_Expecter) GetEvents(ctx interface{}, filter interface{}) *MockEventLogRepository_GetEvents_Call {
	return &MockEventLogRepository_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx, filter)}
}

func (_c *MockEventLogRepository_GetEvents_Call) Run(run func(ctx context.Context, filter repository.EventLogFilter)) *MockEventLogRepository_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.EventLogFilter))
	})
	return _c
}

func (_c *MockEventLogRepository_GetEvents_Call) Return(_a0 []repository.EventLogEntry, _a1 error) *MockEventLogRepository_GetEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventLogRepository_GetEvents_Call) RunAndReturn(run func(context.Context, repository.EventLogFilter) ([]repository.EventLogEntry, error)) *MockEventLogRepository_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsByType provides a mock function with given fields: ctx, eventType, limit
func (_m *MockEventLogRepository) GetEventsByType(ctx context.Context, eventType string, limit int) ([]repository.EventLogEntry, error) {
	ret := _m.Called(ctx, eventType, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByType")
	}

	var r0 []repository.EventLogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]repository.EventLogEntry, error)); ok {
		return rf(ctx, eventType, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []repository.EventLogEntry); ok {
		r0 = rf(ctx, eventType, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.EventLogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, eventType, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventLogRepository_GetEventsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsByType'
type MockEventLogRepository_GetEventsByType_Call struct {
	*mock.Call
}

// GetEventsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType string
//   - limit int
func (_e *MockEventLogRepository_Expecter) GetEventsByType(ctx interface{}, eventType interface{}, limit interface{}) *MockEventLogRepository_GetEventsByType_Call {
	return &MockEventLogRepository_GetEventsByType_Call{Call: _e.mock.On("GetEventsByType", ctx, eventType, limit)}
}

func (_c *MockEventLogRepository_GetEventsByType_Call) Run(run func(ctx context.Context, eventType string, limit int)) *MockEventLogRepository_GetEventsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockEventLogRepository_GetEventsByType_Call) Return(_a0 []repository.EventLogEntry, _a1 error) *MockEventLogRepository_GetEventsByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventLogRepository_GetEventsByType_Call) RunAndReturn(run func(context.Context, string, int) ([]repository.EventLogEntry, error)) *MockEventLogRepository_GetEventsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsByUser provides a mock function with given fields: ctx, userID, limit
func (_m *MockEventLogRepository) GetEventsByUser(ctx context.Context, userID string, limit int) ([]repository.EventLogEntry, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByUser")
	}

	var r0 []repository.EventLogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]repository.EventLogEntry, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []repository.EventLogEntry); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.EventLogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventLogRepository_GetEventsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsByUser'
type MockEventLogRepository_GetEventsByUser_Call struct {
	*mock.Call
}

// GetEventsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
func (_e *MockEventLogRepository_Expecter) GetEventsByUser(ctx interface{}, userID interface{}, limit interface{}) *MockEventLogRepository_GetEventsByUser_Call {
	return &MockEventLogRepository_GetEventsByUser_Call{Call: _e.mock.On("GetEventsByUser", ctx, userID, limit)}
}

func (_c *MockEventLogRepository_GetEventsByUser_Call) Run(run func(ctx context.Context, userID string, limit int)) *MockEventLogRepository_GetEventsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockEventLogRepository_GetEventsByUser_Call) Return(_a0 []repository.EventLogEntry, _a1 error) *MockEventLogRepository_GetEventsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventLogRepository_GetEventsByUser_Call) RunAndReturn(run func(context.Context, string, int) ([]repository.EventLogEntry, error)) *MockEventLogRepository_GetEventsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// LogEvent provides a mock function with given fields: ctx, eventType, userID, payload, metadata
func (_m *MockEventLogRepository) LogEvent(ctx context.Context, eventType string, userID *string, payload map[string]interface{}, metadata map[string]interface{}) error {
	ret := _m.Called(ctx, eventType, userID, payload, metadata)

	if len(ret) == 0 {
		panic("no return value specified for LogEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, map[string]interface{}, map[string]interface{}) error); ok {
		r0 = rf(ctx, eventType, userID, payload, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventLogRepository_LogEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogEvent'
type MockEventLogRepository_LogEvent_Call struct {
	*mock.Call
}

// LogEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType string
//   - userID *string
//   - payload map[string]interface{}
//   - metadata map[string]interface{}
func (_e *MockEventLogRepository_Expecter) LogEvent(ctx interface{}, eventType interface{}, userID interface{}, payload interface{}, metadata interface{}) *MockEventLogRepository_LogEvent_Call {
	return &MockEventLogRepository_LogEvent_Call{Call: _e.mock.On("LogEvent", ctx, eventType, userID, payload, metadata)}
}

func (_c *MockEventLogRepository_LogEvent_Call) Run(run func(ctx context.Context, eventType string, userID *string, payload map[string]interface{}, metadata map[string]interface{})) *MockEventLogRepository_LogEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(map[string]interface{}), args[4].(map[string]interface{}))
	})
	return _c
}

func (_c *MockEventLogRepository_LogEvent_Call) Return(_a0 error) *MockEventLogRepository_LogEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventLogRepository_LogEvent_Call) RunAndReturn(run func(context.Context, string, *string, map[string]interface{}, map[string]interface{}) error) *MockEventLogRepository_LogEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventLogRepository creates a new instance of MockEventLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventLogRepository {
	mock := &MockEventLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
