// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/osse101/BrandishBot_Go/internal/repository"
)

// MockRepositoryCompostRepository is an autogenerated mock type for the CompostRepository type
type MockRepositoryCompostRepository struct {
	mock.Mock
}

type MockRepositoryCompostRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryCompostRepository) EXPECT() *MockRepositoryCompostRepository_Expecter {
	return &MockRepositoryCompostRepository_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx
func (_m *MockRepositoryCompostRepository) BeginTx(ctx context.Context) (repository.CompostTx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.CompostTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.CompostTx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.CompostTx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.CompostTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCompostRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockRepositoryCompostRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryCompostRepository_Expecter) BeginTx(ctx interface{}) *MockRepositoryCompostRepository_BeginTx_Call {
	return &MockRepositoryCompostRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockRepositoryCompostRepository_BeginTx_Call) Run(run func(ctx context.Context)) *MockRepositoryCompostRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryCompostRepository_BeginTx_Call) Return(_a0 repository.CompostTx, _a1 error) *MockRepositoryCompostRepository_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCompostRepository_BeginTx_Call) RunAndReturn(run func(context.Context) (repository.CompostTx, error)) *MockRepositoryCompostRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBin provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryCompostRepository) CreateBin(ctx context.Context, userID string) (*domain.CompostBin, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBin")
	}

	var r0 *domain.CompostBin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.CompostBin, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.CompostBin); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CompostBin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCompostRepository_CreateBin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBin'
type MockRepositoryCompostRepository_CreateBin_Call struct {
	*mock.Call
}

// CreateBin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryCompostRepository_Expecter) CreateBin(ctx interface{}, userID interface{}) *MockRepositoryCompostRepository_CreateBin_Call {
	return &MockRepositoryCompostRepository_CreateBin_Call{Call: _e.mock.On("CreateBin", ctx, userID)}
}

func (_c *MockRepositoryCompostRepository_CreateBin_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryCompostRepository_CreateBin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryCompostRepository_CreateBin_Call) Return(_a0 *domain.CompostBin, _a1 error) *MockRepositoryCompostRepository_CreateBin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCompostRepository_CreateBin_Call) RunAndReturn(run func(context.Context, string) (*domain.CompostBin, error)) *MockRepositoryCompostRepository_CreateBin_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllItems provides a mock function with given fields: ctx
func (_m *MockRepositoryCompostRepository) GetAllItems(ctx context.Context) ([]domain.Item, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllItems")
	}

	var r0 []domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Item, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Item); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCompostRepository_GetAllItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllItems'
type MockRepositoryCompostRepository_GetAllItems_Call struct {
	*mock.Call
}

// GetAllItems is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryCompostRepository_Expecter) GetAllItems(ctx interface{}) *MockRepositoryCompostRepository_GetAllItems_Call {
	return &MockRepositoryCompostRepository_GetAllItems_Call{Call: _e.mock.On("GetAllItems", ctx)}
}

func (_c *MockRepositoryCompostRepository_GetAllItems_Call) Run(run func(ctx context.Context)) *MockRepositoryCompostRepository_GetAllItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryCompostRepository_GetAllItems_Call) Return(_a0 []domain.Item, _a1 error) *MockRepositoryCompostRepository_GetAllItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCompostRepository_GetAllItems_Call) RunAndReturn(run func(context.Context) ([]domain.Item, error)) *MockRepositoryCompostRepository_GetAllItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetBin provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryCompostRepository) GetBin(ctx context.Context, userID string) (*domain.CompostBin, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBin")
	}

	var r0 *domain.CompostBin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.CompostBin, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.CompostBin); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CompostBin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCompostRepository_GetBin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBin'
type MockRepositoryCompostRepository_GetBin_Call struct {
	*mock.Call
}

// GetBin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryCompostRepository_Expecter) GetBin(ctx interface{}, userID interface{}) *MockRepositoryCompostRepository_GetBin_Call {
	return &MockRepositoryCompostRepository_GetBin_Call{Call: _e.mock.On("GetBin", ctx, userID)}
}

func (_c *MockRepositoryCompostRepository_GetBin_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryCompostRepository_GetBin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryCompostRepository_GetBin_Call) Return(_a0 *domain.CompostBin, _a1 error) *MockRepositoryCompostRepository_GetBin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCompostRepository_GetBin_Call) RunAndReturn(run func(context.Context, string) (*domain.CompostBin, error)) *MockRepositoryCompostRepository_GetBin_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByPlatformID provides a mock function with given fields: ctx, platform, platformID
func (_m *MockRepositoryCompostRepository) GetUserByPlatformID(ctx context.Context, platform string, platformID string) (*domain.User, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByPlatformID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCompostRepository_GetUserByPlatformID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPlatformID'
type MockRepositoryCompostRepository_GetUserByPlatformID_Call struct {
	*mock.Call
}

// GetUserByPlatformID is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockRepositoryCompostRepository_Expecter) GetUserByPlatformID(ctx interface{}, platform interface{}, platformID interface{}) *MockRepositoryCompostRepository_GetUserByPlatformID_Call {
	return &MockRepositoryCompostRepository_GetUserByPlatformID_Call{Call: _e.mock.On("GetUserByPlatformID", ctx, platform, platformID)}
}

func (_c *MockRepositoryCompostRepository_GetUserByPlatformID_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockRepositoryCompostRepository_GetUserByPlatformID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepositoryCompostRepository_GetUserByPlatformID_Call) Return(_a0 *domain.User, _a1 error) *MockRepositoryCompostRepository_GetUserByPlatformID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCompostRepository_GetUserByPlatformID_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockRepositoryCompostRepository_GetUserByPlatformID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryCompostRepository creates a new instance of MockRepositoryCompostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryCompostRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryCompostRepository {
	mock := &MockRepositoryCompostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
