// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// BuyItem provides a mock function with given fields: ctx, platform, platformID, username, itemName, quantity
func (_m *MockService) BuyItem(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int) (int, error) {
	ret := _m.Called(ctx, platform, platformID, username, itemName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for BuyItem")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) (int, error)); ok {
		return rf(ctx, platform, platformID, username, itemName, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) int); ok {
		r0 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int) error); ok {
		r1 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_BuyItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuyItem'
type MockService_BuyItem_Call struct {
	*mock.Call
}

// BuyItem is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - itemName string
//   - quantity int
func (_e *MockService_Expecter) BuyItem(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, itemName interface{}, quantity interface{}) *MockService_BuyItem_Call {
	return &MockService_BuyItem_Call{Call: _e.mock.On("BuyItem", ctx, platform, platformID, username, itemName, quantity)}
}

func (_c *MockService_BuyItem_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int)) *MockService_BuyItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockService_BuyItem_Call) Return(_a0 int, _a1 error) *MockService_BuyItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_BuyItem_Call) RunAndReturn(run func(context.Context, string, string, string, string, int) (int, error)) *MockService_BuyItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetBuyablePrices provides a mock function with given fields: ctx
func (_m *MockService) GetBuyablePrices(ctx context.Context) ([]domain.Item, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBuyablePrices")
	}

	var r0 []domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Item, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Item); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetBuyablePrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuyablePrices'
type MockService_GetBuyablePrices_Call struct {
	*mock.Call
}

// GetBuyablePrices is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetBuyablePrices(ctx interface{}) *MockService_GetBuyablePrices_Call {
	return &MockService_GetBuyablePrices_Call{Call: _e.mock.On("GetBuyablePrices", ctx)}
}

func (_c *MockService_GetBuyablePrices_Call) Run(run func(ctx context.Context)) *MockService_GetBuyablePrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetBuyablePrices_Call) Return(_a0 []domain.Item, _a1 error) *MockService_GetBuyablePrices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetBuyablePrices_Call) RunAndReturn(run func(context.Context) ([]domain.Item, error)) *MockService_GetBuyablePrices_Call {
	_c.Call.Return(run)
	return _c
}

// GetSellablePrices provides a mock function with given fields: ctx
func (_m *MockService) GetSellablePrices(ctx context.Context) ([]domain.Item, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSellablePrices")
	}

	var r0 []domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Item, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Item); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetSellablePrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSellablePrices'
type MockService_GetSellablePrices_Call struct {
	*mock.Call
}

// GetSellablePrices is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetSellablePrices(ctx interface{}) *MockService_GetSellablePrices_Call {
	return &MockService_GetSellablePrices_Call{Call: _e.mock.On("GetSellablePrices", ctx)}
}

func (_c *MockService_GetSellablePrices_Call) Run(run func(ctx context.Context)) *MockService_GetSellablePrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetSellablePrices_Call) Return(_a0 []domain.Item, _a1 error) *MockService_GetSellablePrices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetSellablePrices_Call) RunAndReturn(run func(context.Context) ([]domain.Item, error)) *MockService_GetSellablePrices_Call {
	_c.Call.Return(run)
	return _c
}

// SellItem provides a mock function with given fields: ctx, platform, platformID, username, itemName, quantity
func (_m *MockService) SellItem(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int) (int, int, error) {
	ret := _m.Called(ctx, platform, platformID, username, itemName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for SellItem")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) (int, int, error)); ok {
		return rf(ctx, platform, platformID, username, itemName, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) int); ok {
		r0 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int) int); ok {
		r1 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, string, int) error); ok {
		r2 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_SellItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SellItem'
type MockService_SellItem_Call struct {
	*mock.Call
}

// SellItem is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - itemName string
//   - quantity int
func (_e *MockService_Expecter) SellItem(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, itemName interface{}, quantity interface{}) *MockService_SellItem_Call {
	return &MockService_SellItem_Call{Call: _e.mock.On("SellItem", ctx, platform, platformID, username, itemName, quantity)}
}

func (_c *MockService_SellItem_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int)) *MockService_SellItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockService_SellItem_Call) Return(_a0 int, _a1 int, _a2 error) *MockService_SellItem_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_SellItem_Call) RunAndReturn(run func(context.Context, string, string, string, string, int) (int, int, error)) *MockService_SellItem_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockService) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Shutdown(ctx interface{}) *MockService_Shutdown_Call {
	return &MockService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockService_Shutdown_Call) Run(run func(ctx context.Context)) *MockService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Shutdown_Call) Return(_a0 error) *MockService_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Shutdown_Call) RunAndReturn(run func(context.Context) error) *MockService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
