// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/osse101/BrandishBot_Go/internal/repository"
)

// MockRepositoryHarvestRepository is an autogenerated mock type for the HarvestRepository type
type MockRepositoryHarvestRepository struct {
	mock.Mock
}

type MockRepositoryHarvestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryHarvestRepository) EXPECT() *MockRepositoryHarvestRepository_Expecter {
	return &MockRepositoryHarvestRepository_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx
func (_m *MockRepositoryHarvestRepository) BeginTx(ctx context.Context) (repository.HarvestTx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.HarvestTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.HarvestTx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.HarvestTx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.HarvestTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryHarvestRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockRepositoryHarvestRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryHarvestRepository_Expecter) BeginTx(ctx interface{}) *MockRepositoryHarvestRepository_BeginTx_Call {
	return &MockRepositoryHarvestRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockRepositoryHarvestRepository_BeginTx_Call) Run(run func(ctx context.Context)) *MockRepositoryHarvestRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryHarvestRepository_BeginTx_Call) Return(_a0 repository.HarvestTx, _a1 error) *MockRepositoryHarvestRepository_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryHarvestRepository_BeginTx_Call) RunAndReturn(run func(context.Context) (repository.HarvestTx, error)) *MockRepositoryHarvestRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateHarvestState provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryHarvestRepository) CreateHarvestState(ctx context.Context, userID string) (*domain.HarvestState, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateHarvestState")
	}

	var r0 *domain.HarvestState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.HarvestState, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.HarvestState); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HarvestState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryHarvestRepository_CreateHarvestState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHarvestState'
type MockRepositoryHarvestRepository_CreateHarvestState_Call struct {
	*mock.Call
}

// CreateHarvestState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryHarvestRepository_Expecter) CreateHarvestState(ctx interface{}, userID interface{}) *MockRepositoryHarvestRepository_CreateHarvestState_Call {
	return &MockRepositoryHarvestRepository_CreateHarvestState_Call{Call: _e.mock.On("CreateHarvestState", ctx, userID)}
}

func (_c *MockRepositoryHarvestRepository_CreateHarvestState_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryHarvestRepository_CreateHarvestState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryHarvestRepository_CreateHarvestState_Call) Return(_a0 *domain.HarvestState, _a1 error) *MockRepositoryHarvestRepository_CreateHarvestState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryHarvestRepository_CreateHarvestState_Call) RunAndReturn(run func(context.Context, string) (*domain.HarvestState, error)) *MockRepositoryHarvestRepository_CreateHarvestState_Call {
	_c.Call.Return(run)
	return _c
}

// GetHarvestState provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryHarvestRepository) GetHarvestState(ctx context.Context, userID string) (*domain.HarvestState, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetHarvestState")
	}

	var r0 *domain.HarvestState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.HarvestState, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.HarvestState); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HarvestState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryHarvestRepository_GetHarvestState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHarvestState'
type MockRepositoryHarvestRepository_GetHarvestState_Call struct {
	*mock.Call
}

// GetHarvestState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryHarvestRepository_Expecter) GetHarvestState(ctx interface{}, userID interface{}) *MockRepositoryHarvestRepository_GetHarvestState_Call {
	return &MockRepositoryHarvestRepository_GetHarvestState_Call{Call: _e.mock.On("GetHarvestState", ctx, userID)}
}

func (_c *MockRepositoryHarvestRepository_GetHarvestState_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryHarvestRepository_GetHarvestState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryHarvestRepository_GetHarvestState_Call) Return(_a0 *domain.HarvestState, _a1 error) *MockRepositoryHarvestRepository_GetHarvestState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryHarvestRepository_GetHarvestState_Call) RunAndReturn(run func(context.Context, string) (*domain.HarvestState, error)) *MockRepositoryHarvestRepository_GetHarvestState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryHarvestRepository creates a new instance of MockRepositoryHarvestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryHarvestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryHarvestRepository {
	mock := &MockRepositoryHarvestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
