// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	crafting "github.com/osse101/BrandishBot_Go/internal/crafting"
	mock "github.com/stretchr/testify/mock"
)

// MockCraftingService is an autogenerated mock type for the Service type
type MockCraftingService struct {
	mock.Mock
}

type MockCraftingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCraftingService) EXPECT() *MockCraftingService_Expecter {
	return &MockCraftingService_Expecter{mock: &_m.Mock}
}

// DisassembleItem provides a mock function with given fields: ctx, platform, platformID, username, itemName, quantity
func (_m *MockCraftingService) DisassembleItem(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int) (map[string]int, int, error) {
	ret := _m.Called(ctx, platform, platformID, username, itemName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DisassembleItem")
	}

	var r0 map[string]int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) (map[string]int, int, error)); ok {
		return rf(ctx, platform, platformID, username, itemName, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) map[string]int); ok {
		r0 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int) int); ok {
		r1 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, string, int) error); ok {
		r2 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCraftingService_DisassembleItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisassembleItem'
type MockCraftingService_DisassembleItem_Call struct {
	*mock.Call
}

// DisassembleItem is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - itemName string
//   - quantity int
func (_e *MockCraftingService_Expecter) DisassembleItem(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, itemName interface{}, quantity interface{}) *MockCraftingService_DisassembleItem_Call {
	return &MockCraftingService_DisassembleItem_Call{Call: _e.mock.On("DisassembleItem", ctx, platform, platformID, username, itemName, quantity)}
}

func (_c *MockCraftingService_DisassembleItem_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int)) *MockCraftingService_DisassembleItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockCraftingService_DisassembleItem_Call) Return(_a0 map[string]int, _a1 int, _a2 error) *MockCraftingService_DisassembleItem_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCraftingService_DisassembleItem_Call) RunAndReturn(run func(context.Context, string, string, string, string, int) (map[string]int, int, error)) *MockCraftingService_DisassembleItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecipe provides a mock function with given fields: ctx, itemName, platform, platformID, username
func (_m *MockCraftingService) GetRecipe(ctx context.Context, itemName string, platform string, platformID string, username string) (*crafting.RecipeInfo, error) {
	ret := _m.Called(ctx, itemName, platform, platformID, username)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipe")
	}

	var r0 *crafting.RecipeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*crafting.RecipeInfo, error)); ok {
		return rf(ctx, itemName, platform, platformID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *crafting.RecipeInfo); ok {
		r0 = rf(ctx, itemName, platform, platformID, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crafting.RecipeInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, itemName, platform, platformID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCraftingService_GetRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecipe'
type MockCraftingService_GetRecipe_Call struct {
	*mock.Call
}

// GetRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - itemName string
//   - platform string
//   - platformID string
//   - username string
func (_e *MockCraftingService_Expecter) GetRecipe(ctx interface{}, itemName interface{}, platform interface{}, platformID interface{}, username interface{}) *MockCraftingService_GetRecipe_Call {
	return &MockCraftingService_GetRecipe_Call{Call: _e.mock.On("GetRecipe", ctx, itemName, platform, platformID, username)}
}

func (_c *MockCraftingService_GetRecipe_Call) Run(run func(ctx context.Context, itemName string, platform string, platformID string, username string)) *MockCraftingService_GetRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockCraftingService_GetRecipe_Call) Return(_a0 *crafting.RecipeInfo, _a1 error) *MockCraftingService_GetRecipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCraftingService_GetRecipe_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*crafting.RecipeInfo, error)) *MockCraftingService_GetRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnlockedRecipes provides a mock function with given fields: ctx, platform, platformID, username
func (_m *MockCraftingService) GetUnlockedRecipes(ctx context.Context, platform string, platformID string, username string) ([]crafting.UnlockedRecipeInfo, error) {
	ret := _m.Called(ctx, platform, platformID, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUnlockedRecipes")
	}

	var r0 []crafting.UnlockedRecipeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]crafting.UnlockedRecipeInfo, error)); ok {
		return rf(ctx, platform, platformID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []crafting.UnlockedRecipeInfo); ok {
		r0 = rf(ctx, platform, platformID, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]crafting.UnlockedRecipeInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, platform, platformID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCraftingService_GetUnlockedRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnlockedRecipes'
type MockCraftingService_GetUnlockedRecipes_Call struct {
	*mock.Call
}

// GetUnlockedRecipes is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
func (_e *MockCraftingService_Expecter) GetUnlockedRecipes(ctx interface{}, platform interface{}, platformID interface{}, username interface{}) *MockCraftingService_GetUnlockedRecipes_Call {
	return &MockCraftingService_GetUnlockedRecipes_Call{Call: _e.mock.On("GetUnlockedRecipes", ctx, platform, platformID, username)}
}

func (_c *MockCraftingService_GetUnlockedRecipes_Call) Run(run func(ctx context.Context, platform string, platformID string, username string)) *MockCraftingService_GetUnlockedRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCraftingService_GetUnlockedRecipes_Call) Return(_a0 []crafting.UnlockedRecipeInfo, _a1 error) *MockCraftingService_GetUnlockedRecipes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCraftingService_GetUnlockedRecipes_Call) RunAndReturn(run func(context.Context, string, string, string) ([]crafting.UnlockedRecipeInfo, error)) *MockCraftingService_GetUnlockedRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockCraftingService) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCraftingService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockCraftingService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCraftingService_Expecter) Shutdown(ctx interface{}) *MockCraftingService_Shutdown_Call {
	return &MockCraftingService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockCraftingService_Shutdown_Call) Run(run func(ctx context.Context)) *MockCraftingService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCraftingService_Shutdown_Call) Return(_a0 error) *MockCraftingService_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCraftingService_Shutdown_Call) RunAndReturn(run func(context.Context) error) *MockCraftingService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// UpgradeItem provides a mock function with given fields: ctx, platform, platformID, username, itemName, quantity
func (_m *MockCraftingService) UpgradeItem(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int) (string, int, error) {
	ret := _m.Called(ctx, platform, platformID, username, itemName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpgradeItem")
	}

	var r0 string
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) (string, int, error)); ok {
		return rf(ctx, platform, platformID, username, itemName, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) string); ok {
		r0 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int) int); ok {
		r1 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, string, int) error); ok {
		r2 = rf(ctx, platform, platformID, username, itemName, quantity)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCraftingService_UpgradeItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpgradeItem'
type MockCraftingService_UpgradeItem_Call struct {
	*mock.Call
}

// UpgradeItem is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - itemName string
//   - quantity int
func (_e *MockCraftingService_Expecter) UpgradeItem(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, itemName interface{}, quantity interface{}) *MockCraftingService_UpgradeItem_Call {
	return &MockCraftingService_UpgradeItem_Call{Call: _e.mock.On("UpgradeItem", ctx, platform, platformID, username, itemName, quantity)}
}

func (_c *MockCraftingService_UpgradeItem_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, itemName string, quantity int)) *MockCraftingService_UpgradeItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockCraftingService_UpgradeItem_Call) Return(_a0 string, _a1 int, _a2 error) *MockCraftingService_UpgradeItem_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCraftingService_UpgradeItem_Call) RunAndReturn(run func(context.Context, string, string, string, string, int) (string, int, error)) *MockCraftingService_UpgradeItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCraftingService creates a new instance of MockCraftingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCraftingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCraftingService {
	mock := &MockCraftingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
