// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockHarvestService is an autogenerated mock type for the Service type
type MockHarvestService struct {
	mock.Mock
}

type MockHarvestService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHarvestService) EXPECT() *MockHarvestService_Expecter {
	return &MockHarvestService_Expecter{mock: &_m.Mock}
}

// Harvest provides a mock function with given fields: ctx, platform, platformID, username
func (_m *MockHarvestService) Harvest(ctx context.Context, platform string, platformID string, username string) (*domain.HarvestResponse, error) {
	ret := _m.Called(ctx, platform, platformID, username)

	if len(ret) == 0 {
		panic("no return value specified for Harvest")
	}

	var r0 *domain.HarvestResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.HarvestResponse, error)); ok {
		return rf(ctx, platform, platformID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.HarvestResponse); ok {
		r0 = rf(ctx, platform, platformID, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HarvestResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, platform, platformID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHarvestService_Harvest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Harvest'
type MockHarvestService_Harvest_Call struct {
	*mock.Call
}

// Harvest is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
func (_e *MockHarvestService_Expecter) Harvest(ctx interface{}, platform interface{}, platformID interface{}, username interface{}) *MockHarvestService_Harvest_Call {
	return &MockHarvestService_Harvest_Call{Call: _e.mock.On("Harvest", ctx, platform, platformID, username)}
}

func (_c *MockHarvestService_Harvest_Call) Run(run func(ctx context.Context, platform string, platformID string, username string)) *MockHarvestService_Harvest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockHarvestService_Harvest_Call) Return(_a0 *domain.HarvestResponse, _a1 error) *MockHarvestService_Harvest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHarvestService_Harvest_Call) RunAndReturn(run func(context.Context, string, string, string) (*domain.HarvestResponse, error)) *MockHarvestService_Harvest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHarvestService creates a new instance of MockHarvestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHarvestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHarvestService {
	mock := &MockHarvestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
