// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockQuestService is an autogenerated mock type for the Service type
type MockQuestService struct {
	mock.Mock
}

type MockQuestService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuestService) EXPECT() *MockQuestService_Expecter {
	return &MockQuestService_Expecter{mock: &_m.Mock}
}

// ClaimQuestReward provides a mock function with given fields: ctx, userID, questID
func (_m *MockQuestService) ClaimQuestReward(ctx context.Context, userID string, questID int) (int, error) {
	ret := _m.Called(ctx, userID, questID)

	if len(ret) == 0 {
		panic("no return value specified for ClaimQuestReward")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (int, error)); ok {
		return rf(ctx, userID, questID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) int); ok {
		r0 = rf(ctx, userID, questID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, questID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuestService_ClaimQuestReward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimQuestReward'
type MockQuestService_ClaimQuestReward_Call struct {
	*mock.Call
}

// ClaimQuestReward is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - questID int
func (_e *MockQuestService_Expecter) ClaimQuestReward(ctx interface{}, userID interface{}, questID interface{}) *MockQuestService_ClaimQuestReward_Call {
	return &MockQuestService_ClaimQuestReward_Call{Call: _e.mock.On("ClaimQuestReward", ctx, userID, questID)}
}

func (_c *MockQuestService_ClaimQuestReward_Call) Run(run func(ctx context.Context, userID string, questID int)) *MockQuestService_ClaimQuestReward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockQuestService_ClaimQuestReward_Call) Return(money int, err error) *MockQuestService_ClaimQuestReward_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *MockQuestService_ClaimQuestReward_Call) RunAndReturn(run func(context.Context, string, int) (int, error)) *MockQuestService_ClaimQuestReward_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateWeeklyQuests provides a mock function with given fields: ctx, year, weekNumber
func (_m *MockQuestService) GenerateWeeklyQuests(ctx context.Context, year int, weekNumber int) error {
	ret := _m.Called(ctx, year, weekNumber)

	if len(ret) == 0 {
		panic("no return value specified for GenerateWeeklyQuests")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, year, weekNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuestService_GenerateWeeklyQuests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateWeeklyQuests'
type MockQuestService_GenerateWeeklyQuests_Call struct {
	*mock.Call
}

// GenerateWeeklyQuests is a helper method to define mock.On call
//   - ctx context.Context
//   - year int
//   - weekNumber int
func (_e *MockQuestService_Expecter) GenerateWeeklyQuests(ctx interface{}, year interface{}, weekNumber interface{}) *MockQuestService_GenerateWeeklyQuests_Call {
	return &MockQuestService_GenerateWeeklyQuests_Call{Call: _e.mock.On("GenerateWeeklyQuests", ctx, year, weekNumber)}
}

func (_c *MockQuestService_GenerateWeeklyQuests_Call) Run(run func(ctx context.Context, year int, weekNumber int)) *MockQuestService_GenerateWeeklyQuests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockQuestService_GenerateWeeklyQuests_Call) Return(_a0 error) *MockQuestService_GenerateWeeklyQuests_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuestService_GenerateWeeklyQuests_Call) RunAndReturn(run func(context.Context, int, int) error) *MockQuestService_GenerateWeeklyQuests_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveQuests provides a mock function with given fields: ctx
func (_m *MockQuestService) GetActiveQuests(ctx context.Context) ([]domain.Quest, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveQuests")
	}

	var r0 []domain.Quest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Quest, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Quest); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Quest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuestService_GetActiveQuests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveQuests'
type MockQuestService_GetActiveQuests_Call struct {
	*mock.Call
}

// GetActiveQuests is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuestService_Expecter) GetActiveQuests(ctx interface{}) *MockQuestService_GetActiveQuests_Call {
	return &MockQuestService_GetActiveQuests_Call{Call: _e.mock.On("GetActiveQuests", ctx)}
}

func (_c *MockQuestService_GetActiveQuests_Call) Run(run func(ctx context.Context)) *MockQuestService_GetActiveQuests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuestService_GetActiveQuests_Call) Return(_a0 []domain.Quest, _a1 error) *MockQuestService_GetActiveQuests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuestService_GetActiveQuests_Call) RunAndReturn(run func(context.Context) ([]domain.Quest, error)) *MockQuestService_GetActiveQuests_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserQuestProgress provides a mock function with given fields: ctx, userID
func (_m *MockQuestService) GetUserQuestProgress(ctx context.Context, userID string) ([]domain.QuestProgress, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserQuestProgress")
	}

	var r0 []domain.QuestProgress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.QuestProgress, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.QuestProgress); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.QuestProgress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuestService_GetUserQuestProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserQuestProgress'
type MockQuestService_GetUserQuestProgress_Call struct {
	*mock.Call
}

// GetUserQuestProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockQuestService_Expecter) GetUserQuestProgress(ctx interface{}, userID interface{}) *MockQuestService_GetUserQuestProgress_Call {
	return &MockQuestService_GetUserQuestProgress_Call{Call: _e.mock.On("GetUserQuestProgress", ctx, userID)}
}

func (_c *MockQuestService_GetUserQuestProgress_Call) Run(run func(ctx context.Context, userID string)) *MockQuestService_GetUserQuestProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuestService_GetUserQuestProgress_Call) Return(_a0 []domain.QuestProgress, _a1 error) *MockQuestService_GetUserQuestProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuestService_GetUserQuestProgress_Call) RunAndReturn(run func(context.Context, string) ([]domain.QuestProgress, error)) *MockQuestService_GetUserQuestProgress_Call {
	_c.Call.Return(run)
	return _c
}

// OnItemBought provides a mock function with given fields: ctx, userID, itemCategory, quantity
func (_m *MockQuestService) OnItemBought(ctx context.Context, userID string, itemCategory string, quantity int) error {
	ret := _m.Called(ctx, userID, itemCategory, quantity)

	if len(ret) == 0 {
		panic("no return value specified for OnItemBought")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, userID, itemCategory, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuestService_OnItemBought_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnItemBought'
type MockQuestService_OnItemBought_Call struct {
	*mock.Call
}

// OnItemBought is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - itemCategory string
//   - quantity int
func (_e *MockQuestService_Expecter) OnItemBought(ctx interface{}, userID interface{}, itemCategory interface{}, quantity interface{}) *MockQuestService_OnItemBought_Call {
	return &MockQuestService_OnItemBought_Call{Call: _e.mock.On("OnItemBought", ctx, userID, itemCategory, quantity)}
}

func (_c *MockQuestService_OnItemBought_Call) Run(run func(ctx context.Context, userID string, itemCategory string, quantity int)) *MockQuestService_OnItemBought_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockQuestService_OnItemBought_Call) Return(_a0 error) *MockQuestService_OnItemBought_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuestService_OnItemBought_Call) RunAndReturn(run func(context.Context, string, string, int) error) *MockQuestService_OnItemBought_Call {
	_c.Call.Return(run)
	return _c
}

// OnItemSold provides a mock function with given fields: ctx, userID, itemCategory, quantity, moneyEarned
func (_m *MockQuestService) OnItemSold(ctx context.Context, userID string, itemCategory string, quantity int, moneyEarned int) error {
	ret := _m.Called(ctx, userID, itemCategory, quantity, moneyEarned)

	if len(ret) == 0 {
		panic("no return value specified for OnItemSold")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) error); ok {
		r0 = rf(ctx, userID, itemCategory, quantity, moneyEarned)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuestService_OnItemSold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnItemSold'
type MockQuestService_OnItemSold_Call struct {
	*mock.Call
}

// OnItemSold is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - itemCategory string
//   - quantity int
//   - moneyEarned int
func (_e *MockQuestService_Expecter) OnItemSold(ctx interface{}, userID interface{}, itemCategory interface{}, quantity interface{}, moneyEarned interface{}) *MockQuestService_OnItemSold_Call {
	return &MockQuestService_OnItemSold_Call{Call: _e.mock.On("OnItemSold", ctx, userID, itemCategory, quantity, moneyEarned)}
}

func (_c *MockQuestService_OnItemSold_Call) Run(run func(ctx context.Context, userID string, itemCategory string, quantity int, moneyEarned int)) *MockQuestService_OnItemSold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockQuestService_OnItemSold_Call) Return(_a0 error) *MockQuestService_OnItemSold_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuestService_OnItemSold_Call) RunAndReturn(run func(context.Context, string, string, int, int) error) *MockQuestService_OnItemSold_Call {
	_c.Call.Return(run)
	return _c
}

// OnRecipeCrafted provides a mock function with given fields: ctx, userID, recipeKey, quantity
func (_m *MockQuestService) OnRecipeCrafted(ctx context.Context, userID string, recipeKey string, quantity int) error {
	ret := _m.Called(ctx, userID, recipeKey, quantity)

	if len(ret) == 0 {
		panic("no return value specified for OnRecipeCrafted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, userID, recipeKey, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuestService_OnRecipeCrafted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnRecipeCrafted'
type MockQuestService_OnRecipeCrafted_Call struct {
	*mock.Call
}

// OnRecipeCrafted is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - recipeKey string
//   - quantity int
func (_e *MockQuestService_Expecter) OnRecipeCrafted(ctx interface{}, userID interface{}, recipeKey interface{}, quantity interface{}) *MockQuestService_OnRecipeCrafted_Call {
	return &MockQuestService_OnRecipeCrafted_Call{Call: _e.mock.On("OnRecipeCrafted", ctx, userID, recipeKey, quantity)}
}

func (_c *MockQuestService_OnRecipeCrafted_Call) Run(run func(ctx context.Context, userID string, recipeKey string, quantity int)) *MockQuestService_OnRecipeCrafted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockQuestService_OnRecipeCrafted_Call) Return(_a0 error) *MockQuestService_OnRecipeCrafted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuestService_OnRecipeCrafted_Call) RunAndReturn(run func(context.Context, string, string, int) error) *MockQuestService_OnRecipeCrafted_Call {
	_c.Call.Return(run)
	return _c
}

// OnSearch provides a mock function with given fields: ctx, userID
func (_m *MockQuestService) OnSearch(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for OnSearch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuestService_OnSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnSearch'
type MockQuestService_OnSearch_Call struct {
	*mock.Call
}

// OnSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockQuestService_Expecter) OnSearch(ctx interface{}, userID interface{}) *MockQuestService_OnSearch_Call {
	return &MockQuestService_OnSearch_Call{Call: _e.mock.On("OnSearch", ctx, userID)}
}

func (_c *MockQuestService_OnSearch_Call) Run(run func(ctx context.Context, userID string)) *MockQuestService_OnSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuestService_OnSearch_Call) Return(_a0 error) *MockQuestService_OnSearch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuestService_OnSearch_Call) RunAndReturn(run func(context.Context, string) error) *MockQuestService_OnSearch_Call {
	_c.Call.Return(run)
	return _c
}

// ResetWeeklyQuests provides a mock function with given fields: ctx
func (_m *MockQuestService) ResetWeeklyQuests(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetWeeklyQuests")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuestService_ResetWeeklyQuests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetWeeklyQuests'
type MockQuestService_ResetWeeklyQuests_Call struct {
	*mock.Call
}

// ResetWeeklyQuests is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuestService_Expecter) ResetWeeklyQuests(ctx interface{}) *MockQuestService_ResetWeeklyQuests_Call {
	return &MockQuestService_ResetWeeklyQuests_Call{Call: _e.mock.On("ResetWeeklyQuests", ctx)}
}

func (_c *MockQuestService_ResetWeeklyQuests_Call) Run(run func(ctx context.Context)) *MockQuestService_ResetWeeklyQuests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuestService_ResetWeeklyQuests_Call) Return(_a0 error) *MockQuestService_ResetWeeklyQuests_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuestService_ResetWeeklyQuests_Call) RunAndReturn(run func(context.Context) error) *MockQuestService_ResetWeeklyQuests_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockQuestService) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuestService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockQuestService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuestService_Expecter) Shutdown(ctx interface{}) *MockQuestService_Shutdown_Call {
	return &MockQuestService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockQuestService_Shutdown_Call) Run(run func(ctx context.Context)) *MockQuestService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuestService_Shutdown_Call) Return(_a0 error) *MockQuestService_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuestService_Shutdown_Call) RunAndReturn(run func(context.Context) error) *MockQuestService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuestService creates a new instance of MockQuestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuestService {
	mock := &MockQuestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
