// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryTx is an autogenerated mock type for the Tx type
type MockRepositoryTx struct {
	mock.Mock
}

type MockRepositoryTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryTx) EXPECT() *MockRepositoryTx_Expecter {
	return &MockRepositoryTx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields: ctx
func (_m *MockRepositoryTx) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryTx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockRepositoryTx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryTx_Expecter) Commit(ctx interface{}) *MockRepositoryTx_Commit_Call {
	return &MockRepositoryTx_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockRepositoryTx_Commit_Call) Run(run func(ctx context.Context)) *MockRepositoryTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryTx_Commit_Call) Return(_a0 error) *MockRepositoryTx_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryTx_Commit_Call) RunAndReturn(run func(context.Context) error) *MockRepositoryTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// GetInventory provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryTx) GetInventory(ctx context.Context, userID string) (*domain.Inventory, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 *domain.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Inventory, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Inventory); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryTx_GetInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventory'
type MockRepositoryTx_GetInventory_Call struct {
	*mock.Call
}

// GetInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryTx_Expecter) GetInventory(ctx interface{}, userID interface{}) *MockRepositoryTx_GetInventory_Call {
	return &MockRepositoryTx_GetInventory_Call{Call: _e.mock.On("GetInventory", ctx, userID)}
}

func (_c *MockRepositoryTx_GetInventory_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryTx_GetInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryTx_GetInventory_Call) Return(_a0 *domain.Inventory, _a1 error) *MockRepositoryTx_GetInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryTx_GetInventory_Call) RunAndReturn(run func(context.Context, string) (*domain.Inventory, error)) *MockRepositoryTx_GetInventory_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockRepositoryTx) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryTx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockRepositoryTx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryTx_Expecter) Rollback(ctx interface{}) *MockRepositoryTx_Rollback_Call {
	return &MockRepositoryTx_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockRepositoryTx_Rollback_Call) Run(run func(ctx context.Context)) *MockRepositoryTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryTx_Rollback_Call) Return(_a0 error) *MockRepositoryTx_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryTx_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockRepositoryTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInventory provides a mock function with given fields: ctx, userID, inventory
func (_m *MockRepositoryTx) UpdateInventory(ctx context.Context, userID string, inventory domain.Inventory) error {
	ret := _m.Called(ctx, userID, inventory)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Inventory) error); ok {
		r0 = rf(ctx, userID, inventory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryTx_UpdateInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInventory'
type MockRepositoryTx_UpdateInventory_Call struct {
	*mock.Call
}

// UpdateInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inventory domain.Inventory
func (_e *MockRepositoryTx_Expecter) UpdateInventory(ctx interface{}, userID interface{}, inventory interface{}) *MockRepositoryTx_UpdateInventory_Call {
	return &MockRepositoryTx_UpdateInventory_Call{Call: _e.mock.On("UpdateInventory", ctx, userID, inventory)}
}

func (_c *MockRepositoryTx_UpdateInventory_Call) Run(run func(ctx context.Context, userID string, inventory domain.Inventory)) *MockRepositoryTx_UpdateInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Inventory))
	})
	return _c
}

func (_c *MockRepositoryTx_UpdateInventory_Call) Return(_a0 error) *MockRepositoryTx_UpdateInventory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryTx_UpdateInventory_Call) RunAndReturn(run func(context.Context, string, domain.Inventory) error) *MockRepositoryTx_UpdateInventory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryTx creates a new instance of MockRepositoryTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryTx {
	mock := &MockRepositoryTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
