// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/osse101/BrandishBot_Go/internal/repository"

	uuid "github.com/google/uuid"
)

// MockGambleRepository is an autogenerated mock type for the Gamble type
type MockGambleRepository struct {
	mock.Mock
}

type MockGambleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGambleRepository) EXPECT() *MockGambleRepository_Expecter {
	return &MockGambleRepository_Expecter{mock: &_m.Mock}
}

// BeginGambleTx provides a mock function with given fields: ctx
func (_m *MockGambleRepository) BeginGambleTx(ctx context.Context) (repository.GambleTx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginGambleTx")
	}

	var r0 repository.GambleTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.GambleTx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.GambleTx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.GambleTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGambleRepository_BeginGambleTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginGambleTx'
type MockGambleRepository_BeginGambleTx_Call struct {
	*mock.Call
}

// BeginGambleTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGambleRepository_Expecter) BeginGambleTx(ctx interface{}) *MockGambleRepository_BeginGambleTx_Call {
	return &MockGambleRepository_BeginGambleTx_Call{Call: _e.mock.On("BeginGambleTx", ctx)}
}

func (_c *MockGambleRepository_BeginGambleTx_Call) Run(run func(ctx context.Context)) *MockGambleRepository_BeginGambleTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGambleRepository_BeginGambleTx_Call) Return(_a0 repository.GambleTx, _a1 error) *MockGambleRepository_BeginGambleTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGambleRepository_BeginGambleTx_Call) RunAndReturn(run func(context.Context) (repository.GambleTx, error)) *MockGambleRepository_BeginGambleTx_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function with given fields: ctx
func (_m *MockGambleRepository) BeginTx(ctx context.Context) (repository.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGambleRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockGambleRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGambleRepository_Expecter) BeginTx(ctx interface{}) *MockGambleRepository_BeginTx_Call {
	return &MockGambleRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockGambleRepository_BeginTx_Call) Run(run func(ctx context.Context)) *MockGambleRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGambleRepository_BeginTx_Call) Return(_a0 repository.Tx, _a1 error) *MockGambleRepository_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGambleRepository_BeginTx_Call) RunAndReturn(run func(context.Context) (repository.Tx, error)) *MockGambleRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteGamble provides a mock function with given fields: ctx, result
func (_m *MockGambleRepository) CompleteGamble(ctx context.Context, result *domain.GambleResult) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for CompleteGamble")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GambleResult) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGambleRepository_CompleteGamble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteGamble'
type MockGambleRepository_CompleteGamble_Call struct {
	*mock.Call
}

// CompleteGamble is a helper method to define mock.On call
//   - ctx context.Context
//   - result *domain.GambleResult
func (_e *MockGambleRepository_Expecter) CompleteGamble(ctx interface{}, result interface{}) *MockGambleRepository_CompleteGamble_Call {
	return &MockGambleRepository_CompleteGamble_Call{Call: _e.mock.On("CompleteGamble", ctx, result)}
}

func (_c *MockGambleRepository_CompleteGamble_Call) Run(run func(ctx context.Context, result *domain.GambleResult)) *MockGambleRepository_CompleteGamble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.GambleResult))
	})
	return _c
}

func (_c *MockGambleRepository_CompleteGamble_Call) Return(_a0 error) *MockGambleRepository_CompleteGamble_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGambleRepository_CompleteGamble_Call) RunAndReturn(run func(context.Context, *domain.GambleResult) error) *MockGambleRepository_CompleteGamble_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGamble provides a mock function with given fields: ctx, gamble
func (_m *MockGambleRepository) CreateGamble(ctx context.Context, gamble *domain.Gamble) error {
	ret := _m.Called(ctx, gamble)

	if len(ret) == 0 {
		panic("no return value specified for CreateGamble")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Gamble) error); ok {
		r0 = rf(ctx, gamble)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGambleRepository_CreateGamble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGamble'
type MockGambleRepository_CreateGamble_Call struct {
	*mock.Call
}

// CreateGamble is a helper method to define mock.On call
//   - ctx context.Context
//   - gamble *domain.Gamble
func (_e *MockGambleRepository_Expecter) CreateGamble(ctx interface{}, gamble interface{}) *MockGambleRepository_CreateGamble_Call {
	return &MockGambleRepository_CreateGamble_Call{Call: _e.mock.On("CreateGamble", ctx, gamble)}
}

func (_c *MockGambleRepository_CreateGamble_Call) Run(run func(ctx context.Context, gamble *domain.Gamble)) *MockGambleRepository_CreateGamble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Gamble))
	})
	return _c
}

func (_c *MockGambleRepository_CreateGamble_Call) Return(_a0 error) *MockGambleRepository_CreateGamble_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGambleRepository_CreateGamble_Call) RunAndReturn(run func(context.Context, *domain.Gamble) error) *MockGambleRepository_CreateGamble_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGamble provides a mock function with given fields: ctx
func (_m *MockGambleRepository) GetActiveGamble(ctx context.Context) (*domain.Gamble, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGamble")
	}

	var r0 *domain.Gamble
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Gamble, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Gamble); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Gamble)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGambleRepository_GetActiveGamble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGamble'
type MockGambleRepository_GetActiveGamble_Call struct {
	*mock.Call
}

// GetActiveGamble is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGambleRepository_Expecter) GetActiveGamble(ctx interface{}) *MockGambleRepository_GetActiveGamble_Call {
	return &MockGambleRepository_GetActiveGamble_Call{Call: _e.mock.On("GetActiveGamble", ctx)}
}

func (_c *MockGambleRepository_GetActiveGamble_Call) Run(run func(ctx context.Context)) *MockGambleRepository_GetActiveGamble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGambleRepository_GetActiveGamble_Call) Return(_a0 *domain.Gamble, _a1 error) *MockGambleRepository_GetActiveGamble_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGambleRepository_GetActiveGamble_Call) RunAndReturn(run func(context.Context) (*domain.Gamble, error)) *MockGambleRepository_GetActiveGamble_Call {
	_c.Call.Return(run)
	return _c
}

// GetGamble provides a mock function with given fields: ctx, id
func (_m *MockGambleRepository) GetGamble(ctx context.Context, id uuid.UUID) (*domain.Gamble, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGamble")
	}

	var r0 *domain.Gamble
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Gamble, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Gamble); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Gamble)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGambleRepository_GetGamble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGamble'
type MockGambleRepository_GetGamble_Call struct {
	*mock.Call
}

// GetGamble is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGambleRepository_Expecter) GetGamble(ctx interface{}, id interface{}) *MockGambleRepository_GetGamble_Call {
	return &MockGambleRepository_GetGamble_Call{Call: _e.mock.On("GetGamble", ctx, id)}
}

func (_c *MockGambleRepository_GetGamble_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGambleRepository_GetGamble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGambleRepository_GetGamble_Call) Return(_a0 *domain.Gamble, _a1 error) *MockGambleRepository_GetGamble_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGambleRepository_GetGamble_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Gamble, error)) *MockGambleRepository_GetGamble_Call {
	_c.Call.Return(run)
	return _c
}

// GetInventory provides a mock function with given fields: ctx, userID
func (_m *MockGambleRepository) GetInventory(ctx context.Context, userID string) (*domain.Inventory, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 *domain.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Inventory, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Inventory); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGambleRepository_GetInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventory'
type MockGambleRepository_GetInventory_Call struct {
	*mock.Call
}

// GetInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockGambleRepository_Expecter) GetInventory(ctx interface{}, userID interface{}) *MockGambleRepository_GetInventory_Call {
	return &MockGambleRepository_GetInventory_Call{Call: _e.mock.On("GetInventory", ctx, userID)}
}

func (_c *MockGambleRepository_GetInventory_Call) Run(run func(ctx context.Context, userID string)) *MockGambleRepository_GetInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGambleRepository_GetInventory_Call) Return(_a0 *domain.Inventory, _a1 error) *MockGambleRepository_GetInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGambleRepository_GetInventory_Call) RunAndReturn(run func(context.Context, string) (*domain.Inventory, error)) *MockGambleRepository_GetInventory_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByID provides a mock function with given fields: ctx, id
func (_m *MockGambleRepository) GetItemByID(ctx context.Context, id int) (*domain.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGambleRepository_GetItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByID'
type MockGambleRepository_GetItemByID_Call struct {
	*mock.Call
}

// GetItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockGambleRepository_Expecter) GetItemByID(ctx interface{}, id interface{}) *MockGambleRepository_GetItemByID_Call {
	return &MockGambleRepository_GetItemByID_Call{Call: _e.mock.On("GetItemByID", ctx, id)}
}

func (_c *MockGambleRepository_GetItemByID_Call) Run(run func(ctx context.Context, id int)) *MockGambleRepository_GetItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockGambleRepository_GetItemByID_Call) Return(_a0 *domain.Item, _a1 error) *MockGambleRepository_GetItemByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGambleRepository_GetItemByID_Call) RunAndReturn(run func(context.Context, int) (*domain.Item, error)) *MockGambleRepository_GetItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByPlatformID provides a mock function with given fields: ctx, platform, platformID
func (_m *MockGambleRepository) GetUserByPlatformID(ctx context.Context, platform string, platformID string) (*domain.User, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByPlatformID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGambleRepository_GetUserByPlatformID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPlatformID'
type MockGambleRepository_GetUserByPlatformID_Call struct {
	*mock.Call
}

// GetUserByPlatformID is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockGambleRepository_Expecter) GetUserByPlatformID(ctx interface{}, platform interface{}, platformID interface{}) *MockGambleRepository_GetUserByPlatformID_Call {
	return &MockGambleRepository_GetUserByPlatformID_Call{Call: _e.mock.On("GetUserByPlatformID", ctx, platform, platformID)}
}

func (_c *MockGambleRepository_GetUserByPlatformID_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockGambleRepository_GetUserByPlatformID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGambleRepository_GetUserByPlatformID_Call) Return(_a0 *domain.User, _a1 error) *MockGambleRepository_GetUserByPlatformID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGambleRepository_GetUserByPlatformID_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockGambleRepository_GetUserByPlatformID_Call {
	_c.Call.Return(run)
	return _c
}

// JoinGamble provides a mock function with given fields: ctx, participant
func (_m *MockGambleRepository) JoinGamble(ctx context.Context, participant *domain.Participant) error {
	ret := _m.Called(ctx, participant)

	if len(ret) == 0 {
		panic("no return value specified for JoinGamble")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Participant) error); ok {
		r0 = rf(ctx, participant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGambleRepository_JoinGamble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinGamble'
type MockGambleRepository_JoinGamble_Call struct {
	*mock.Call
}

// JoinGamble is a helper method to define mock.On call
//   - ctx context.Context
//   - participant *domain.Participant
func (_e *MockGambleRepository_Expecter) JoinGamble(ctx interface{}, participant interface{}) *MockGambleRepository_JoinGamble_Call {
	return &MockGambleRepository_JoinGamble_Call{Call: _e.mock.On("JoinGamble", ctx, participant)}
}

func (_c *MockGambleRepository_JoinGamble_Call) Run(run func(ctx context.Context, participant *domain.Participant)) *MockGambleRepository_JoinGamble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Participant))
	})
	return _c
}

func (_c *MockGambleRepository_JoinGamble_Call) Return(_a0 error) *MockGambleRepository_JoinGamble_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGambleRepository_JoinGamble_Call) RunAndReturn(run func(context.Context, *domain.Participant) error) *MockGambleRepository_JoinGamble_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOpenedItems provides a mock function with given fields: ctx, items
func (_m *MockGambleRepository) SaveOpenedItems(ctx context.Context, items []domain.GambleOpenedItem) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for SaveOpenedItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.GambleOpenedItem) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGambleRepository_SaveOpenedItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOpenedItems'
type MockGambleRepository_SaveOpenedItems_Call struct {
	*mock.Call
}

// SaveOpenedItems is a helper method to define mock.On call
//   - ctx context.Context
//   - items []domain.GambleOpenedItem
func (_e *MockGambleRepository_Expecter) SaveOpenedItems(ctx interface{}, items interface{}) *MockGambleRepository_SaveOpenedItems_Call {
	return &MockGambleRepository_SaveOpenedItems_Call{Call: _e.mock.On("SaveOpenedItems", ctx, items)}
}

func (_c *MockGambleRepository_SaveOpenedItems_Call) Run(run func(ctx context.Context, items []domain.GambleOpenedItem)) *MockGambleRepository_SaveOpenedItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.GambleOpenedItem))
	})
	return _c
}

func (_c *MockGambleRepository_SaveOpenedItems_Call) Return(_a0 error) *MockGambleRepository_SaveOpenedItems_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGambleRepository_SaveOpenedItems_Call) RunAndReturn(run func(context.Context, []domain.GambleOpenedItem) error) *MockGambleRepository_SaveOpenedItems_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGambleState provides a mock function with given fields: ctx, id, state
func (_m *MockGambleRepository) UpdateGambleState(ctx context.Context, id uuid.UUID, state domain.GambleState) error {
	ret := _m.Called(ctx, id, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGambleState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.GambleState) error); ok {
		r0 = rf(ctx, id, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGambleRepository_UpdateGambleState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGambleState'
type MockGambleRepository_UpdateGambleState_Call struct {
	*mock.Call
}

// UpdateGambleState is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - state domain.GambleState
func (_e *MockGambleRepository_Expecter) UpdateGambleState(ctx interface{}, id interface{}, state interface{}) *MockGambleRepository_UpdateGambleState_Call {
	return &MockGambleRepository_UpdateGambleState_Call{Call: _e.mock.On("UpdateGambleState", ctx, id, state)}
}

func (_c *MockGambleRepository_UpdateGambleState_Call) Run(run func(ctx context.Context, id uuid.UUID, state domain.GambleState)) *MockGambleRepository_UpdateGambleState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.GambleState))
	})
	return _c
}

func (_c *MockGambleRepository_UpdateGambleState_Call) Return(_a0 error) *MockGambleRepository_UpdateGambleState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGambleRepository_UpdateGambleState_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.GambleState) error) *MockGambleRepository_UpdateGambleState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGambleStateIfMatches provides a mock function with given fields: ctx, id, expectedState, newState
func (_m *MockGambleRepository) UpdateGambleStateIfMatches(ctx context.Context, id uuid.UUID, expectedState domain.GambleState, newState domain.GambleState) (int64, error) {
	ret := _m.Called(ctx, id, expectedState, newState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGambleStateIfMatches")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.GambleState, domain.GambleState) (int64, error)); ok {
		return rf(ctx, id, expectedState, newState)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.GambleState, domain.GambleState) int64); ok {
		r0 = rf(ctx, id, expectedState, newState)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.GambleState, domain.GambleState) error); ok {
		r1 = rf(ctx, id, expectedState, newState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGambleRepository_UpdateGambleStateIfMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGambleStateIfMatches'
type MockGambleRepository_UpdateGambleStateIfMatches_Call struct {
	*mock.Call
}

// UpdateGambleStateIfMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - expectedState domain.GambleState
//   - newState domain.GambleState
func (_e *MockGambleRepository_Expecter) UpdateGambleStateIfMatches(ctx interface{}, id interface{}, expectedState interface{}, newState interface{}) *MockGambleRepository_UpdateGambleStateIfMatches_Call {
	return &MockGambleRepository_UpdateGambleStateIfMatches_Call{Call: _e.mock.On("UpdateGambleStateIfMatches", ctx, id, expectedState, newState)}
}

func (_c *MockGambleRepository_UpdateGambleStateIfMatches_Call) Run(run func(ctx context.Context, id uuid.UUID, expectedState domain.GambleState, newState domain.GambleState)) *MockGambleRepository_UpdateGambleStateIfMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.GambleState), args[3].(domain.GambleState))
	})
	return _c
}

func (_c *MockGambleRepository_UpdateGambleStateIfMatches_Call) Return(_a0 int64, _a1 error) *MockGambleRepository_UpdateGambleStateIfMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGambleRepository_UpdateGambleStateIfMatches_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.GambleState, domain.GambleState) (int64, error)) *MockGambleRepository_UpdateGambleStateIfMatches_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInventory provides a mock function with given fields: ctx, userID, inventory
func (_m *MockGambleRepository) UpdateInventory(ctx context.Context, userID string, inventory domain.Inventory) error {
	ret := _m.Called(ctx, userID, inventory)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Inventory) error); ok {
		r0 = rf(ctx, userID, inventory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGambleRepository_UpdateInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInventory'
type MockGambleRepository_UpdateInventory_Call struct {
	*mock.Call
}

// UpdateInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inventory domain.Inventory
func (_e *MockGambleRepository_Expecter) UpdateInventory(ctx interface{}, userID interface{}, inventory interface{}) *MockGambleRepository_UpdateInventory_Call {
	return &MockGambleRepository_UpdateInventory_Call{Call: _e.mock.On("UpdateInventory", ctx, userID, inventory)}
}

func (_c *MockGambleRepository_UpdateInventory_Call) Run(run func(ctx context.Context, userID string, inventory domain.Inventory)) *MockGambleRepository_UpdateInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Inventory))
	})
	return _c
}

func (_c *MockGambleRepository_UpdateInventory_Call) Return(_a0 error) *MockGambleRepository_UpdateInventory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGambleRepository_UpdateInventory_Call) RunAndReturn(run func(context.Context, string, domain.Inventory) error) *MockGambleRepository_UpdateInventory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGambleRepository creates a new instance of MockGambleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGambleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGambleRepository {
	mock := &MockGambleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
