// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CheckCooldown provides a mock function with given fields: ctx, userID, action
func (_m *MockService) CheckCooldown(ctx context.Context, userID string, action string) (bool, time.Duration, error) {
	ret := _m.Called(ctx, userID, action)

	if len(ret) == 0 {
		panic("no return value specified for CheckCooldown")
	}

	var r0 bool
	var r1 time.Duration
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, time.Duration, error)); ok {
		return rf(ctx, userID, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userID, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) time.Duration); ok {
		r1 = rf(ctx, userID, action)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, userID, action)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_CheckCooldown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckCooldown'
type MockService_CheckCooldown_Call struct {
	*mock.Call
}

// CheckCooldown is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - action string
func (_e *MockService_Expecter) CheckCooldown(ctx interface{}, userID interface{}, action interface{}) *MockService_CheckCooldown_Call {
	return &MockService_CheckCooldown_Call{Call: _e.mock.On("CheckCooldown", ctx, userID, action)}
}

func (_c *MockService_CheckCooldown_Call) Run(run func(ctx context.Context, userID string, action string)) *MockService_CheckCooldown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_CheckCooldown_Call) Return(_a0 bool, _a1 time.Duration, _a2 error) *MockService_CheckCooldown_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_CheckCooldown_Call) RunAndReturn(run func(context.Context, string, string) (bool, time.Duration, error)) *MockService_CheckCooldown_Call {
	_c.Call.Return(run)
	return _c
}

// EnforceCooldown provides a mock function with given fields: ctx, userID, action, fn
func (_m *MockService) EnforceCooldown(ctx context.Context, userID string, action string, fn func() error) error {
	ret := _m.Called(ctx, userID, action, fn)

	if len(ret) == 0 {
		panic("no return value specified for EnforceCooldown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, func() error) error); ok {
		r0 = rf(ctx, userID, action, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_EnforceCooldown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnforceCooldown'
type MockService_EnforceCooldown_Call struct {
	*mock.Call
}

// EnforceCooldown is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - action string
//   - fn func() error
func (_e *MockService_Expecter) EnforceCooldown(ctx interface{}, userID interface{}, action interface{}, fn interface{}) *MockService_EnforceCooldown_Call {
	return &MockService_EnforceCooldown_Call{Call: _e.mock.On("EnforceCooldown", ctx, userID, action, fn)}
}

func (_c *MockService_EnforceCooldown_Call) Run(run func(ctx context.Context, userID string, action string, fn func() error)) *MockService_EnforceCooldown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(func() error))
	})
	return _c
}

func (_c *MockService_EnforceCooldown_Call) Return(_a0 error) *MockService_EnforceCooldown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_EnforceCooldown_Call) RunAndReturn(run func(context.Context, string, string, func() error) error) *MockService_EnforceCooldown_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastUsed provides a mock function with given fields: ctx, userID, action
func (_m *MockService) GetLastUsed(ctx context.Context, userID string, action string) (*time.Time, error) {
	ret := _m.Called(ctx, userID, action)

	if len(ret) == 0 {
		panic("no return value specified for GetLastUsed")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*time.Time, error)); ok {
		return rf(ctx, userID, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *time.Time); ok {
		r0 = rf(ctx, userID, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastUsed'
type MockService_GetLastUsed_Call struct {
	*mock.Call
}

// GetLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - action string
func (_e *MockService_Expecter) GetLastUsed(ctx interface{}, userID interface{}, action interface{}) *MockService_GetLastUsed_Call {
	return &MockService_GetLastUsed_Call{Call: _e.mock.On("GetLastUsed", ctx, userID, action)}
}

func (_c *MockService_GetLastUsed_Call) Run(run func(ctx context.Context, userID string, action string)) *MockService_GetLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetLastUsed_Call) Return(_a0 *time.Time, _a1 error) *MockService_GetLastUsed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetLastUsed_Call) RunAndReturn(run func(context.Context, string, string) (*time.Time, error)) *MockService_GetLastUsed_Call {
	_c.Call.Return(run)
	return _c
}

// ResetCooldown provides a mock function with given fields: ctx, userID, action
func (_m *MockService) ResetCooldown(ctx context.Context, userID string, action string) error {
	ret := _m.Called(ctx, userID, action)

	if len(ret) == 0 {
		panic("no return value specified for ResetCooldown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ResetCooldown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetCooldown'
type MockService_ResetCooldown_Call struct {
	*mock.Call
}

// ResetCooldown is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - action string
func (_e *MockService_Expecter) ResetCooldown(ctx interface{}, userID interface{}, action interface{}) *MockService_ResetCooldown_Call {
	return &MockService_ResetCooldown_Call{Call: _e.mock.On("ResetCooldown", ctx, userID, action)}
}

func (_c *MockService_ResetCooldown_Call) Run(run func(ctx context.Context, userID string, action string)) *MockService_ResetCooldown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_ResetCooldown_Call) Return(_a0 error) *MockService_ResetCooldown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ResetCooldown_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_ResetCooldown_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
