// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPool is an autogenerated mock type for the Pool type
type MockPool struct {
	mock.Mock
}

type MockPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPool) EXPECT() *MockPool_Expecter {
	return &MockPool_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockPool) Close() {
	_m.Called()
}

// MockPool_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPool_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPool_Expecter) Close() *MockPool_Close_Call {
	return &MockPool_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPool_Close_Call) Run(run func()) *MockPool_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_Close_Call) Return() *MockPool_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPool_Close_Call) RunAndReturn(run func()) *MockPool_Close_Call {
	_c.Run(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockPool) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPool_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPool_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPool_Expecter) Ping(ctx interface{}) *MockPool_Ping_Call {
	return &MockPool_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockPool_Ping_Call) Run(run func(ctx context.Context)) *MockPool_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPool_Ping_Call) Return(_a0 error) *MockPool_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_Ping_Call) RunAndReturn(run func(context.Context) error) *MockPool_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPool creates a new instance of MockPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPool {
	mock := &MockPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
