// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	lootbox "github.com/osse101/BrandishBot_Go/internal/lootbox"
	mock "github.com/stretchr/testify/mock"
)

// MockLootboxService is an autogenerated mock type for the Service type
type MockLootboxService struct {
	mock.Mock
}

type MockLootboxService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLootboxService) EXPECT() *MockLootboxService_Expecter {
	return &MockLootboxService_Expecter{mock: &_m.Mock}
}

// OpenLootbox provides a mock function with given fields: ctx, lootboxName, quantity
func (_m *MockLootboxService) OpenLootbox(ctx context.Context, lootboxName string, quantity int) ([]lootbox.DroppedItem, error) {
	ret := _m.Called(ctx, lootboxName, quantity)

	if len(ret) == 0 {
		panic("no return value specified for OpenLootbox")
	}

	var r0 []lootbox.DroppedItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]lootbox.DroppedItem, error)); ok {
		return rf(ctx, lootboxName, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []lootbox.DroppedItem); ok {
		r0 = rf(ctx, lootboxName, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lootbox.DroppedItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, lootboxName, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLootboxService_OpenLootbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenLootbox'
type MockLootboxService_OpenLootbox_Call struct {
	*mock.Call
}

// OpenLootbox is a helper method to define mock.On call
//   - ctx context.Context
//   - lootboxName string
//   - quantity int
func (_e *MockLootboxService_Expecter) OpenLootbox(ctx interface{}, lootboxName interface{}, quantity interface{}) *MockLootboxService_OpenLootbox_Call {
	return &MockLootboxService_OpenLootbox_Call{Call: _e.mock.On("OpenLootbox", ctx, lootboxName, quantity)}
}

func (_c *MockLootboxService_OpenLootbox_Call) Run(run func(ctx context.Context, lootboxName string, quantity int)) *MockLootboxService_OpenLootbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockLootboxService_OpenLootbox_Call) Return(_a0 []lootbox.DroppedItem, _a1 error) *MockLootboxService_OpenLootbox_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLootboxService_OpenLootbox_Call) RunAndReturn(run func(context.Context, string, int) ([]lootbox.DroppedItem, error)) *MockLootboxService_OpenLootbox_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLootboxService creates a new instance of MockLootboxService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLootboxService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLootboxService {
	mock := &MockLootboxService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
