// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockExpeditionService is an autogenerated mock type for the Service type
type MockExpeditionService struct {
	mock.Mock
}

type MockExpeditionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpeditionService) EXPECT() *MockExpeditionService_Expecter {
	return &MockExpeditionService_Expecter{mock: &_m.Mock}
}

// ExecuteExpedition provides a mock function with given fields: ctx, expeditionID
func (_m *MockExpeditionService) ExecuteExpedition(ctx context.Context, expeditionID uuid.UUID) error {
	ret := _m.Called(ctx, expeditionID)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteExpedition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, expeditionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpeditionService_ExecuteExpedition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteExpedition'
type MockExpeditionService_ExecuteExpedition_Call struct {
	*mock.Call
}

// ExecuteExpedition is a helper method to define mock.On call
//   - ctx context.Context
//   - expeditionID uuid.UUID
func (_e *MockExpeditionService_Expecter) ExecuteExpedition(ctx interface{}, expeditionID interface{}) *MockExpeditionService_ExecuteExpedition_Call {
	return &MockExpeditionService_ExecuteExpedition_Call{Call: _e.mock.On("ExecuteExpedition", ctx, expeditionID)}
}

func (_c *MockExpeditionService_ExecuteExpedition_Call) Run(run func(ctx context.Context, expeditionID uuid.UUID)) *MockExpeditionService_ExecuteExpedition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockExpeditionService_ExecuteExpedition_Call) Return(_a0 error) *MockExpeditionService_ExecuteExpedition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpeditionService_ExecuteExpedition_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockExpeditionService_ExecuteExpedition_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveExpedition provides a mock function with given fields: ctx
func (_m *MockExpeditionService) GetActiveExpedition(ctx context.Context) (*domain.ExpeditionDetails, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveExpedition")
	}

	var r0 *domain.ExpeditionDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.ExpeditionDetails, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.ExpeditionDetails); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ExpeditionDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpeditionService_GetActiveExpedition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveExpedition'
type MockExpeditionService_GetActiveExpedition_Call struct {
	*mock.Call
}

// GetActiveExpedition is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExpeditionService_Expecter) GetActiveExpedition(ctx interface{}) *MockExpeditionService_GetActiveExpedition_Call {
	return &MockExpeditionService_GetActiveExpedition_Call{Call: _e.mock.On("GetActiveExpedition", ctx)}
}

func (_c *MockExpeditionService_GetActiveExpedition_Call) Run(run func(ctx context.Context)) *MockExpeditionService_GetActiveExpedition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockExpeditionService_GetActiveExpedition_Call) Return(_a0 *domain.ExpeditionDetails, _a1 error) *MockExpeditionService_GetActiveExpedition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpeditionService_GetActiveExpedition_Call) RunAndReturn(run func(context.Context) (*domain.ExpeditionDetails, error)) *MockExpeditionService_GetActiveExpedition_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpedition provides a mock function with given fields: ctx, expeditionID
func (_m *MockExpeditionService) GetExpedition(ctx context.Context, expeditionID uuid.UUID) (*domain.ExpeditionDetails, error) {
	ret := _m.Called(ctx, expeditionID)

	if len(ret) == 0 {
		panic("no return value specified for GetExpedition")
	}

	var r0 *domain.ExpeditionDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.ExpeditionDetails, error)); ok {
		return rf(ctx, expeditionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.ExpeditionDetails); ok {
		r0 = rf(ctx, expeditionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ExpeditionDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, expeditionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpeditionService_GetExpedition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpedition'
type MockExpeditionService_GetExpedition_Call struct {
	*mock.Call
}

// GetExpedition is a helper method to define mock.On call
//   - ctx context.Context
//   - expeditionID uuid.UUID
func (_e *MockExpeditionService_Expecter) GetExpedition(ctx interface{}, expeditionID interface{}) *MockExpeditionService_GetExpedition_Call {
	return &MockExpeditionService_GetExpedition_Call{Call: _e.mock.On("GetExpedition", ctx, expeditionID)}
}

func (_c *MockExpeditionService_GetExpedition_Call) Run(run func(ctx context.Context, expeditionID uuid.UUID)) *MockExpeditionService_GetExpedition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockExpeditionService_GetExpedition_Call) Return(_a0 *domain.ExpeditionDetails, _a1 error) *MockExpeditionService_GetExpedition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpeditionService_GetExpedition_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.ExpeditionDetails, error)) *MockExpeditionService_GetExpedition_Call {
	_c.Call.Return(run)
	return _c
}

// GetJournal provides a mock function with given fields: ctx, expeditionID
func (_m *MockExpeditionService) GetJournal(ctx context.Context, expeditionID uuid.UUID) ([]domain.ExpeditionJournalEntry, error) {
	ret := _m.Called(ctx, expeditionID)

	if len(ret) == 0 {
		panic("no return value specified for GetJournal")
	}

	var r0 []domain.ExpeditionJournalEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.ExpeditionJournalEntry, error)); ok {
		return rf(ctx, expeditionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.ExpeditionJournalEntry); ok {
		r0 = rf(ctx, expeditionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ExpeditionJournalEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, expeditionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpeditionService_GetJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJournal'
type MockExpeditionService_GetJournal_Call struct {
	*mock.Call
}

// GetJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - expeditionID uuid.UUID
func (_e *MockExpeditionService_Expecter) GetJournal(ctx interface{}, expeditionID interface{}) *MockExpeditionService_GetJournal_Call {
	return &MockExpeditionService_GetJournal_Call{Call: _e.mock.On("GetJournal", ctx, expeditionID)}
}

func (_c *MockExpeditionService_GetJournal_Call) Run(run func(ctx context.Context, expeditionID uuid.UUID)) *MockExpeditionService_GetJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockExpeditionService_GetJournal_Call) Return(_a0 []domain.ExpeditionJournalEntry, _a1 error) *MockExpeditionService_GetJournal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpeditionService_GetJournal_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.ExpeditionJournalEntry, error)) *MockExpeditionService_GetJournal_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: ctx
func (_m *MockExpeditionService) GetStatus(ctx context.Context) (*domain.ExpeditionStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *domain.ExpeditionStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.ExpeditionStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.ExpeditionStatus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ExpeditionStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpeditionService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockExpeditionService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExpeditionService_Expecter) GetStatus(ctx interface{}) *MockExpeditionService_GetStatus_Call {
	return &MockExpeditionService_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx)}
}

func (_c *MockExpeditionService_GetStatus_Call) Run(run func(ctx context.Context)) *MockExpeditionService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockExpeditionService_GetStatus_Call) Return(_a0 *domain.ExpeditionStatus, _a1 error) *MockExpeditionService_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpeditionService_GetStatus_Call) RunAndReturn(run func(context.Context) (*domain.ExpeditionStatus, error)) *MockExpeditionService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// JoinExpedition provides a mock function with given fields: ctx, platform, platformID, username, expeditionID
func (_m *MockExpeditionService) JoinExpedition(ctx context.Context, platform string, platformID string, username string, expeditionID uuid.UUID) error {
	ret := _m.Called(ctx, platform, platformID, username, expeditionID)

	if len(ret) == 0 {
		panic("no return value specified for JoinExpedition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, uuid.UUID) error); ok {
		r0 = rf(ctx, platform, platformID, username, expeditionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpeditionService_JoinExpedition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinExpedition'
type MockExpeditionService_JoinExpedition_Call struct {
	*mock.Call
}

// JoinExpedition is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - expeditionID uuid.UUID
func (_e *MockExpeditionService_Expecter) JoinExpedition(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, expeditionID interface{}) *MockExpeditionService_JoinExpedition_Call {
	return &MockExpeditionService_JoinExpedition_Call{Call: _e.mock.On("JoinExpedition", ctx, platform, platformID, username, expeditionID)}
}

func (_c *MockExpeditionService_JoinExpedition_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, expeditionID uuid.UUID)) *MockExpeditionService_JoinExpedition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(uuid.UUID))
	})
	return _c
}

func (_c *MockExpeditionService_JoinExpedition_Call) Return(_a0 error) *MockExpeditionService_JoinExpedition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpeditionService_JoinExpedition_Call) RunAndReturn(run func(context.Context, string, string, string, uuid.UUID) error) *MockExpeditionService_JoinExpedition_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockExpeditionService) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpeditionService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockExpeditionService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExpeditionService_Expecter) Shutdown(ctx interface{}) *MockExpeditionService_Shutdown_Call {
	return &MockExpeditionService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockExpeditionService_Shutdown_Call) Run(run func(ctx context.Context)) *MockExpeditionService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockExpeditionService_Shutdown_Call) Return(_a0 error) *MockExpeditionService_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpeditionService_Shutdown_Call) RunAndReturn(run func(context.Context) error) *MockExpeditionService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// StartExpedition provides a mock function with given fields: ctx, platform, platformID, username, expeditionType
func (_m *MockExpeditionService) StartExpedition(ctx context.Context, platform string, platformID string, username string, expeditionType string) (*domain.Expedition, error) {
	ret := _m.Called(ctx, platform, platformID, username, expeditionType)

	if len(ret) == 0 {
		panic("no return value specified for StartExpedition")
	}

	var r0 *domain.Expedition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*domain.Expedition, error)); ok {
		return rf(ctx, platform, platformID, username, expeditionType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *domain.Expedition); ok {
		r0 = rf(ctx, platform, platformID, username, expeditionType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Expedition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, platform, platformID, username, expeditionType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpeditionService_StartExpedition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartExpedition'
type MockExpeditionService_StartExpedition_Call struct {
	*mock.Call
}

// StartExpedition is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
//   - username string
//   - expeditionType string
func (_e *MockExpeditionService_Expecter) StartExpedition(ctx interface{}, platform interface{}, platformID interface{}, username interface{}, expeditionType interface{}) *MockExpeditionService_StartExpedition_Call {
	return &MockExpeditionService_StartExpedition_Call{Call: _e.mock.On("StartExpedition", ctx, platform, platformID, username, expeditionType)}
}

func (_c *MockExpeditionService_StartExpedition_Call) Run(run func(ctx context.Context, platform string, platformID string, username string, expeditionType string)) *MockExpeditionService_StartExpedition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockExpeditionService_StartExpedition_Call) Return(_a0 *domain.Expedition, _a1 error) *MockExpeditionService_StartExpedition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpeditionService_StartExpedition_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*domain.Expedition, error)) *MockExpeditionService_StartExpedition_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpeditionService creates a new instance of MockExpeditionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpeditionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpeditionService {
	mock := &MockExpeditionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
