// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// GetActiveTheme provides a mock function with no fields
func (_m *MockResolver) GetActiveTheme() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActiveTheme")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockResolver_GetActiveTheme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveTheme'
type MockResolver_GetActiveTheme_Call struct {
	*mock.Call
}

// GetActiveTheme is a helper method to define mock.On call
func (_e *MockResolver_Expecter) GetActiveTheme() *MockResolver_GetActiveTheme_Call {
	return &MockResolver_GetActiveTheme_Call{Call: _e.mock.On("GetActiveTheme")}
}

func (_c *MockResolver_GetActiveTheme_Call) Run(run func()) *MockResolver_GetActiveTheme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolver_GetActiveTheme_Call) Return(_a0 string) *MockResolver_GetActiveTheme_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolver_GetActiveTheme_Call) RunAndReturn(run func() string) *MockResolver_GetActiveTheme_Call {
	_c.Call.Return(run)
	return _c
}

// GetDisplayName provides a mock function with given fields: internalName, shineLevel
func (_m *MockResolver) GetDisplayName(internalName string, shineLevel string) string {
	ret := _m.Called(internalName, shineLevel)

	if len(ret) == 0 {
		panic("no return value specified for GetDisplayName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(internalName, shineLevel)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockResolver_GetDisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDisplayName'
type MockResolver_GetDisplayName_Call struct {
	*mock.Call
}

// GetDisplayName is a helper method to define mock.On call
//   - internalName string
//   - shineLevel string
func (_e *MockResolver_Expecter) GetDisplayName(internalName interface{}, shineLevel interface{}) *MockResolver_GetDisplayName_Call {
	return &MockResolver_GetDisplayName_Call{Call: _e.mock.On("GetDisplayName", internalName, shineLevel)}
}

func (_c *MockResolver_GetDisplayName_Call) Run(run func(internalName string, shineLevel string)) *MockResolver_GetDisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockResolver_GetDisplayName_Call) Return(_a0 string) *MockResolver_GetDisplayName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolver_GetDisplayName_Call) RunAndReturn(run func(string, string) string) *MockResolver_GetDisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterItem provides a mock function with given fields: internalName, publicName
func (_m *MockResolver) RegisterItem(internalName string, publicName string) {
	_m.Called(internalName, publicName)
}

// MockResolver_RegisterItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterItem'
type MockResolver_RegisterItem_Call struct {
	*mock.Call
}

// RegisterItem is a helper method to define mock.On call
//   - internalName string
//   - publicName string
func (_e *MockResolver_Expecter) RegisterItem(internalName interface{}, publicName interface{}) *MockResolver_RegisterItem_Call {
	return &MockResolver_RegisterItem_Call{Call: _e.mock.On("RegisterItem", internalName, publicName)}
}

func (_c *MockResolver_RegisterItem_Call) Run(run func(internalName string, publicName string)) *MockResolver_RegisterItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockResolver_RegisterItem_Call) Return() *MockResolver_RegisterItem_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResolver_RegisterItem_Call) RunAndReturn(run func(string, string)) *MockResolver_RegisterItem_Call {
	_c.Run(run)
	return _c
}

// Reload provides a mock function with no fields
func (_m *MockResolver) Reload() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResolver_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type MockResolver_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
func (_e *MockResolver_Expecter) Reload() *MockResolver_Reload_Call {
	return &MockResolver_Reload_Call{Call: _e.mock.On("Reload")}
}

func (_c *MockResolver_Reload_Call) Run(run func()) *MockResolver_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolver_Reload_Call) Return(_a0 error) *MockResolver_Reload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolver_Reload_Call) RunAndReturn(run func() error) *MockResolver_Reload_Call {
	_c.Call.Return(run)
	return _c
}

// ResolvePublicName provides a mock function with given fields: publicName
func (_m *MockResolver) ResolvePublicName(publicName string) (string, bool) {
	ret := _m.Called(publicName)

	if len(ret) == 0 {
		panic("no return value specified for ResolvePublicName")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(publicName)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(publicName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(publicName)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockResolver_ResolvePublicName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvePublicName'
type MockResolver_ResolvePublicName_Call struct {
	*mock.Call
}

// ResolvePublicName is a helper method to define mock.On call
//   - publicName string
func (_e *MockResolver_Expecter) ResolvePublicName(publicName interface{}) *MockResolver_ResolvePublicName_Call {
	return &MockResolver_ResolvePublicName_Call{Call: _e.mock.On("ResolvePublicName", publicName)}
}

func (_c *MockResolver_ResolvePublicName_Call) Run(run func(publicName string)) *MockResolver_ResolvePublicName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockResolver_ResolvePublicName_Call) Return(internalName string, ok bool) *MockResolver_ResolvePublicName_Call {
	_c.Call.Return(internalName, ok)
	return _c
}

func (_c *MockResolver_ResolvePublicName_Call) RunAndReturn(run func(string) (string, bool)) *MockResolver_ResolvePublicName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
