// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryCompostTx is an autogenerated mock type for the CompostTx type
type MockRepositoryCompostTx struct {
	mock.Mock
}

type MockRepositoryCompostTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryCompostTx) EXPECT() *MockRepositoryCompostTx_Expecter {
	return &MockRepositoryCompostTx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields: ctx
func (_m *MockRepositoryCompostTx) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryCompostTx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockRepositoryCompostTx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryCompostTx_Expecter) Commit(ctx interface{}) *MockRepositoryCompostTx_Commit_Call {
	return &MockRepositoryCompostTx_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockRepositoryCompostTx_Commit_Call) Run(run func(ctx context.Context)) *MockRepositoryCompostTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryCompostTx_Commit_Call) Return(_a0 error) *MockRepositoryCompostTx_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryCompostTx_Commit_Call) RunAndReturn(run func(context.Context) error) *MockRepositoryCompostTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// GetBinForUpdate provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryCompostTx) GetBinForUpdate(ctx context.Context, userID string) (*domain.CompostBin, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBinForUpdate")
	}

	var r0 *domain.CompostBin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.CompostBin, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.CompostBin); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CompostBin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCompostTx_GetBinForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBinForUpdate'
type MockRepositoryCompostTx_GetBinForUpdate_Call struct {
	*mock.Call
}

// GetBinForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryCompostTx_Expecter) GetBinForUpdate(ctx interface{}, userID interface{}) *MockRepositoryCompostTx_GetBinForUpdate_Call {
	return &MockRepositoryCompostTx_GetBinForUpdate_Call{Call: _e.mock.On("GetBinForUpdate", ctx, userID)}
}

func (_c *MockRepositoryCompostTx_GetBinForUpdate_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryCompostTx_GetBinForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryCompostTx_GetBinForUpdate_Call) Return(_a0 *domain.CompostBin, _a1 error) *MockRepositoryCompostTx_GetBinForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCompostTx_GetBinForUpdate_Call) RunAndReturn(run func(context.Context, string) (*domain.CompostBin, error)) *MockRepositoryCompostTx_GetBinForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetInventory provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryCompostTx) GetInventory(ctx context.Context, userID string) (*domain.Inventory, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 *domain.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Inventory, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Inventory); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryCompostTx_GetInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventory'
type MockRepositoryCompostTx_GetInventory_Call struct {
	*mock.Call
}

// GetInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryCompostTx_Expecter) GetInventory(ctx interface{}, userID interface{}) *MockRepositoryCompostTx_GetInventory_Call {
	return &MockRepositoryCompostTx_GetInventory_Call{Call: _e.mock.On("GetInventory", ctx, userID)}
}

func (_c *MockRepositoryCompostTx_GetInventory_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryCompostTx_GetInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryCompostTx_GetInventory_Call) Return(_a0 *domain.Inventory, _a1 error) *MockRepositoryCompostTx_GetInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryCompostTx_GetInventory_Call) RunAndReturn(run func(context.Context, string) (*domain.Inventory, error)) *MockRepositoryCompostTx_GetInventory_Call {
	_c.Call.Return(run)
	return _c
}

// ResetBin provides a mock function with given fields: ctx, userID
func (_m *MockRepositoryCompostTx) ResetBin(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResetBin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryCompostTx_ResetBin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetBin'
type MockRepositoryCompostTx_ResetBin_Call struct {
	*mock.Call
}

// ResetBin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepositoryCompostTx_Expecter) ResetBin(ctx interface{}, userID interface{}) *MockRepositoryCompostTx_ResetBin_Call {
	return &MockRepositoryCompostTx_ResetBin_Call{Call: _e.mock.On("ResetBin", ctx, userID)}
}

func (_c *MockRepositoryCompostTx_ResetBin_Call) Run(run func(ctx context.Context, userID string)) *MockRepositoryCompostTx_ResetBin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryCompostTx_ResetBin_Call) Return(_a0 error) *MockRepositoryCompostTx_ResetBin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryCompostTx_ResetBin_Call) RunAndReturn(run func(context.Context, string) error) *MockRepositoryCompostTx_ResetBin_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockRepositoryCompostTx) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryCompostTx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockRepositoryCompostTx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryCompostTx_Expecter) Rollback(ctx interface{}) *MockRepositoryCompostTx_Rollback_Call {
	return &MockRepositoryCompostTx_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockRepositoryCompostTx_Rollback_Call) Run(run func(ctx context.Context)) *MockRepositoryCompostTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryCompostTx_Rollback_Call) Return(_a0 error) *MockRepositoryCompostTx_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryCompostTx_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockRepositoryCompostTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBin provides a mock function with given fields: ctx, bin
func (_m *MockRepositoryCompostTx) UpdateBin(ctx context.Context, bin *domain.CompostBin) error {
	ret := _m.Called(ctx, bin)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CompostBin) error); ok {
		r0 = rf(ctx, bin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryCompostTx_UpdateBin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBin'
type MockRepositoryCompostTx_UpdateBin_Call struct {
	*mock.Call
}

// UpdateBin is a helper method to define mock.On call
//   - ctx context.Context
//   - bin *domain.CompostBin
func (_e *MockRepositoryCompostTx_Expecter) UpdateBin(ctx interface{}, bin interface{}) *MockRepositoryCompostTx_UpdateBin_Call {
	return &MockRepositoryCompostTx_UpdateBin_Call{Call: _e.mock.On("UpdateBin", ctx, bin)}
}

func (_c *MockRepositoryCompostTx_UpdateBin_Call) Run(run func(ctx context.Context, bin *domain.CompostBin)) *MockRepositoryCompostTx_UpdateBin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CompostBin))
	})
	return _c
}

func (_c *MockRepositoryCompostTx_UpdateBin_Call) Return(_a0 error) *MockRepositoryCompostTx_UpdateBin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryCompostTx_UpdateBin_Call) RunAndReturn(run func(context.Context, *domain.CompostBin) error) *MockRepositoryCompostTx_UpdateBin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInventory provides a mock function with given fields: ctx, userID, inv
func (_m *MockRepositoryCompostTx) UpdateInventory(ctx context.Context, userID string, inv domain.Inventory) error {
	ret := _m.Called(ctx, userID, inv)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Inventory) error); ok {
		r0 = rf(ctx, userID, inv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryCompostTx_UpdateInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInventory'
type MockRepositoryCompostTx_UpdateInventory_Call struct {
	*mock.Call
}

// UpdateInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inv domain.Inventory
func (_e *MockRepositoryCompostTx_Expecter) UpdateInventory(ctx interface{}, userID interface{}, inv interface{}) *MockRepositoryCompostTx_UpdateInventory_Call {
	return &MockRepositoryCompostTx_UpdateInventory_Call{Call: _e.mock.On("UpdateInventory", ctx, userID, inv)}
}

func (_c *MockRepositoryCompostTx_UpdateInventory_Call) Run(run func(ctx context.Context, userID string, inv domain.Inventory)) *MockRepositoryCompostTx_UpdateInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Inventory))
	})
	return _c
}

func (_c *MockRepositoryCompostTx_UpdateInventory_Call) Return(_a0 error) *MockRepositoryCompostTx_UpdateInventory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryCompostTx_UpdateInventory_Call) RunAndReturn(run func(context.Context, string, domain.Inventory) error) *MockRepositoryCompostTx_UpdateInventory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryCompostTx creates a new instance of MockRepositoryCompostTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryCompostTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryCompostTx {
	mock := &MockRepositoryCompostTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
