// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockJobService is an autogenerated mock type for the JobService type
type MockJobService struct {
	mock.Mock
}

type MockJobService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobService) EXPECT() *MockJobService_Expecter {
	return &MockJobService_Expecter{mock: &_m.Mock}
}

// AwardXP provides a mock function with given fields: ctx, userID, jobKey, baseAmount, source, metadata
func (_m *MockJobService) AwardXP(ctx context.Context, userID string, jobKey string, baseAmount int, source string, metadata map[string]interface{}) (*domain.XPAwardResult, error) {
	ret := _m.Called(ctx, userID, jobKey, baseAmount, source, metadata)

	if len(ret) == 0 {
		panic("no return value specified for AwardXP")
	}

	var r0 *domain.XPAwardResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string, map[string]interface{}) (*domain.XPAwardResult, error)); ok {
		return rf(ctx, userID, jobKey, baseAmount, source, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string, map[string]interface{}) *domain.XPAwardResult); ok {
		r0 = rf(ctx, userID, jobKey, baseAmount, source, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.XPAwardResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, userID, jobKey, baseAmount, source, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobService_AwardXP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AwardXP'
type MockJobService_AwardXP_Call struct {
	*mock.Call
}

// AwardXP is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - jobKey string
//   - baseAmount int
//   - source string
//   - metadata map[string]interface{}
func (_e *MockJobService_Expecter) AwardXP(ctx interface{}, userID interface{}, jobKey interface{}, baseAmount interface{}, source interface{}, metadata interface{}) *MockJobService_AwardXP_Call {
	return &MockJobService_AwardXP_Call{Call: _e.mock.On("AwardXP", ctx, userID, jobKey, baseAmount, source, metadata)}
}

func (_c *MockJobService_AwardXP_Call) Run(run func(ctx context.Context, userID string, jobKey string, baseAmount int, source string, metadata map[string]interface{})) *MockJobService_AwardXP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(string), args[5].(map[string]interface{}))
	})
	return _c
}

func (_c *MockJobService_AwardXP_Call) Return(_a0 *domain.XPAwardResult, _a1 error) *MockJobService_AwardXP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobService_AwardXP_Call) RunAndReturn(run func(context.Context, string, string, int, string, map[string]interface{}) (*domain.XPAwardResult, error)) *MockJobService_AwardXP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobService creates a new instance of MockJobService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobService {
	mock := &MockJobService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
