// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// FindUserByPlatformID provides a mock function with given fields: ctx, platform, platformID
func (_m *MockUserService) FindUserByPlatformID(ctx context.Context, platform string, platformID string) (*domain.User, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByPlatformID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_FindUserByPlatformID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByPlatformID'
type MockUserService_FindUserByPlatformID_Call struct {
	*mock.Call
}

// FindUserByPlatformID is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockUserService_Expecter) FindUserByPlatformID(ctx interface{}, platform interface{}, platformID interface{}) *MockUserService_FindUserByPlatformID_Call {
	return &MockUserService_FindUserByPlatformID_Call{Call: _e.mock.On("FindUserByPlatformID", ctx, platform, platformID)}
}

func (_c *MockUserService_FindUserByPlatformID_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockUserService_FindUserByPlatformID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_FindUserByPlatformID_Call) Return(_a0 *domain.User, _a1 error) *MockUserService_FindUserByPlatformID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_FindUserByPlatformID_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockUserService_FindUserByPlatformID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkedPlatforms provides a mock function with given fields: ctx, platform, platformID
func (_m *MockUserService) GetLinkedPlatforms(ctx context.Context, platform string, platformID string) ([]string, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkedPlatforms")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetLinkedPlatforms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkedPlatforms'
type MockUserService_GetLinkedPlatforms_Call struct {
	*mock.Call
}

// GetLinkedPlatforms is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockUserService_Expecter) GetLinkedPlatforms(ctx interface{}, platform interface{}, platformID interface{}) *MockUserService_GetLinkedPlatforms_Call {
	return &MockUserService_GetLinkedPlatforms_Call{Call: _e.mock.On("GetLinkedPlatforms", ctx, platform, platformID)}
}

func (_c *MockUserService_GetLinkedPlatforms_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockUserService_GetLinkedPlatforms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_GetLinkedPlatforms_Call) Return(_a0 []string, _a1 error) *MockUserService_GetLinkedPlatforms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetLinkedPlatforms_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *MockUserService_GetLinkedPlatforms_Call {
	_c.Call.Return(run)
	return _c
}

// MergeUsers provides a mock function with given fields: ctx, primaryUserID, secondaryUserID
func (_m *MockUserService) MergeUsers(ctx context.Context, primaryUserID string, secondaryUserID string) error {
	ret := _m.Called(ctx, primaryUserID, secondaryUserID)

	if len(ret) == 0 {
		panic("no return value specified for MergeUsers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, primaryUserID, secondaryUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_MergeUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeUsers'
type MockUserService_MergeUsers_Call struct {
	*mock.Call
}

// MergeUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - primaryUserID string
//   - secondaryUserID string
func (_e *MockUserService_Expecter) MergeUsers(ctx interface{}, primaryUserID interface{}, secondaryUserID interface{}) *MockUserService_MergeUsers_Call {
	return &MockUserService_MergeUsers_Call{Call: _e.mock.On("MergeUsers", ctx, primaryUserID, secondaryUserID)}
}

func (_c *MockUserService_MergeUsers_Call) Run(run func(ctx context.Context, primaryUserID string, secondaryUserID string)) *MockUserService_MergeUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_MergeUsers_Call) Return(_a0 error) *MockUserService_MergeUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_MergeUsers_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserService_MergeUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, user
func (_m *MockUserService) RegisterUser(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockUserService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockUserService_Expecter) RegisterUser(ctx interface{}, user interface{}) *MockUserService_RegisterUser_Call {
	return &MockUserService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, user)}
}

func (_c *MockUserService_RegisterUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockUserService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockUserService_RegisterUser_Call) Return(_a0 domain.User, _a1 error) *MockUserService_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_RegisterUser_Call) RunAndReturn(run func(context.Context, domain.User) (domain.User, error)) *MockUserService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnlinkPlatform provides a mock function with given fields: ctx, userID, platform
func (_m *MockUserService) UnlinkPlatform(ctx context.Context, userID string, platform string) error {
	ret := _m.Called(ctx, userID, platform)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkPlatform")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, platform)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_UnlinkPlatform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlinkPlatform'
type MockUserService_UnlinkPlatform_Call struct {
	*mock.Call
}

// UnlinkPlatform is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - platform string
func (_e *MockUserService_Expecter) UnlinkPlatform(ctx interface{}, userID interface{}, platform interface{}) *MockUserService_UnlinkPlatform_Call {
	return &MockUserService_UnlinkPlatform_Call{Call: _e.mock.On("UnlinkPlatform", ctx, userID, platform)}
}

func (_c *MockUserService_UnlinkPlatform_Call) Run(run func(ctx context.Context, userID string, platform string)) *MockUserService_UnlinkPlatform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_UnlinkPlatform_Call) Return(_a0 error) *MockUserService_UnlinkPlatform_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_UnlinkPlatform_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserService_UnlinkPlatform_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
