package main

import (
	"fmt"
	"os"
	"path/filepath"
)

type InstallHooksCommand struct{}

func (c *InstallHooksCommand) Name() string {
	return "install-hooks"
}

func (c *InstallHooksCommand) Description() string {
	return "Install git hooks (pre-commit)"
}

func (c *InstallHooksCommand) Run(args []string) error {
	PrintHeader("Installing Git Hooks")

	hookDir := filepath.Join(".git", "hooks")
	if _, err := os.Stat(hookDir); os.IsNotExist(err) {
		return fmt.Errorf("git hooks directory not found: %s (are you in the repo root?)", hookDir)
	}

	preCommitPath := filepath.Join(hookDir, "pre-commit")
	content := `#!/bin/sh
# Auto-generated by devtool
go run ./cmd/devtool pre-commit
`

	PrintInfo("Writing pre-commit hook to %s...", preCommitPath)
	//nolint:gosec // Git hooks must be executable
	if err := os.WriteFile(preCommitPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("failed to write pre-commit hook: %w", err)
	}

	PrintSuccess("Git hooks installed successfully!")
	return nil
}
