// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	domain "github.com/osse101/BrandishBot_Go/internal/domain"
	repository "github.com/osse101/BrandishBot_Go/internal/repository"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx
func (_m *MockRepository) BeginTx(ctx context.Context) (repository.CraftingTx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.CraftingTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.CraftingTx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.CraftingTx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.CraftingTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) BeginTx(ctx interface{}) *MockRepository_BeginTx_Call {
	return &MockRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockRepository_BeginTx_Call) Run(run func(ctx context.Context)) *MockRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_BeginTx_Call) Return(_a0 repository.CraftingTx, _a1 error) *MockRepository_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_BeginTx_Call) RunAndReturn(run func(context.Context) (repository.CraftingTx, error)) *MockRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// ClearDisassembleOutputs provides a mock function with given fields: ctx, recipeID
func (_m *MockRepository) ClearDisassembleOutputs(ctx context.Context, recipeID int) error {
	ret := _m.Called(ctx, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for ClearDisassembleOutputs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, recipeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ClearDisassembleOutputs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearDisassembleOutputs'
type MockRepository_ClearDisassembleOutputs_Call struct {
	*mock.Call
}

// ClearDisassembleOutputs is a helper method to define mock.On call
//   - ctx context.Context
//   - recipeID int
func (_e *MockRepository_Expecter) ClearDisassembleOutputs(ctx interface{}, recipeID interface{}) *MockRepository_ClearDisassembleOutputs_Call {
	return &MockRepository_ClearDisassembleOutputs_Call{Call: _e.mock.On("ClearDisassembleOutputs", ctx, recipeID)}
}

func (_c *MockRepository_ClearDisassembleOutputs_Call) Run(run func(ctx context.Context, recipeID int)) *MockRepository_ClearDisassembleOutputs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_ClearDisassembleOutputs_Call) Return(_a0 error) *MockRepository_ClearDisassembleOutputs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ClearDisassembleOutputs_Call) RunAndReturn(run func(context.Context, int) error) *MockRepository_ClearDisassembleOutputs_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCraftingRecipes provides a mock function with given fields: ctx
func (_m *MockRepository) GetAllCraftingRecipes(ctx context.Context) ([]domain.Recipe, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCraftingRecipes")
	}

	var r0 []domain.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Recipe, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Recipe); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAllCraftingRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCraftingRecipes'
type MockRepository_GetAllCraftingRecipes_Call struct {
	*mock.Call
}

// GetAllCraftingRecipes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetAllCraftingRecipes(ctx interface{}) *MockRepository_GetAllCraftingRecipes_Call {
	return &MockRepository_GetAllCraftingRecipes_Call{Call: _e.mock.On("GetAllCraftingRecipes", ctx)}
}

func (_c *MockRepository_GetAllCraftingRecipes_Call) Run(run func(ctx context.Context)) *MockRepository_GetAllCraftingRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetAllCraftingRecipes_Call) Return(_a0 []domain.Recipe, _a1 error) *MockRepository_GetAllCraftingRecipes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAllCraftingRecipes_Call) RunAndReturn(run func(context.Context) ([]domain.Recipe, error)) *MockRepository_GetAllCraftingRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDisassembleRecipes provides a mock function with given fields: ctx
func (_m *MockRepository) GetAllDisassembleRecipes(ctx context.Context) ([]domain.DisassembleRecipe, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDisassembleRecipes")
	}

	var r0 []domain.DisassembleRecipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.DisassembleRecipe, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.DisassembleRecipe); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DisassembleRecipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAllDisassembleRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDisassembleRecipes'
type MockRepository_GetAllDisassembleRecipes_Call struct {
	*mock.Call
}

// GetAllDisassembleRecipes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetAllDisassembleRecipes(ctx interface{}) *MockRepository_GetAllDisassembleRecipes_Call {
	return &MockRepository_GetAllDisassembleRecipes_Call{Call: _e.mock.On("GetAllDisassembleRecipes", ctx)}
}

func (_c *MockRepository_GetAllDisassembleRecipes_Call) Run(run func(ctx context.Context)) *MockRepository_GetAllDisassembleRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetAllDisassembleRecipes_Call) Return(_a0 []domain.DisassembleRecipe, _a1 error) *MockRepository_GetAllDisassembleRecipes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAllDisassembleRecipes_Call) RunAndReturn(run func(context.Context) ([]domain.DisassembleRecipe, error)) *MockRepository_GetAllDisassembleRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRecipes provides a mock function with given fields: ctx
func (_m *MockRepository) GetAllRecipes(ctx context.Context) ([]repository.RecipeListItem, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRecipes")
	}

	var r0 []repository.RecipeListItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]repository.RecipeListItem, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []repository.RecipeListItem); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.RecipeListItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAllRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRecipes'
type MockRepository_GetAllRecipes_Call struct {
	*mock.Call
}

// GetAllRecipes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetAllRecipes(ctx interface{}) *MockRepository_GetAllRecipes_Call {
	return &MockRepository_GetAllRecipes_Call{Call: _e.mock.On("GetAllRecipes", ctx)}
}

func (_c *MockRepository_GetAllRecipes_Call) Run(run func(ctx context.Context)) *MockRepository_GetAllRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetAllRecipes_Call) Return(_a0 []repository.RecipeListItem, _a1 error) *MockRepository_GetAllRecipes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAllRecipes_Call) RunAndReturn(run func(context.Context) ([]repository.RecipeListItem, error)) *MockRepository_GetAllRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssociatedUpgradeRecipeID provides a mock function with given fields: ctx, disassembleRecipeID
func (_m *MockRepository) GetAssociatedUpgradeRecipeID(ctx context.Context, disassembleRecipeID int) (int, error) {
	ret := _m.Called(ctx, disassembleRecipeID)

	if len(ret) == 0 {
		panic("no return value specified for GetAssociatedUpgradeRecipeID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, disassembleRecipeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, disassembleRecipeID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, disassembleRecipeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAssociatedUpgradeRecipeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssociatedUpgradeRecipeID'
type MockRepository_GetAssociatedUpgradeRecipeID_Call struct {
	*mock.Call
}

// GetAssociatedUpgradeRecipeID is a helper method to define mock.On call
//   - ctx context.Context
//   - disassembleRecipeID int
func (_e *MockRepository_Expecter) GetAssociatedUpgradeRecipeID(ctx interface{}, disassembleRecipeID interface{}) *MockRepository_GetAssociatedUpgradeRecipeID_Call {
	return &MockRepository_GetAssociatedUpgradeRecipeID_Call{Call: _e.mock.On("GetAssociatedUpgradeRecipeID", ctx, disassembleRecipeID)}
}

func (_c *MockRepository_GetAssociatedUpgradeRecipeID_Call) Run(run func(ctx context.Context, disassembleRecipeID int)) *MockRepository_GetAssociatedUpgradeRecipeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_GetAssociatedUpgradeRecipeID_Call) Return(_a0 int, _a1 error) *MockRepository_GetAssociatedUpgradeRecipeID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAssociatedUpgradeRecipeID_Call) RunAndReturn(run func(context.Context, int) (int, error)) *MockRepository_GetAssociatedUpgradeRecipeID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCraftingRecipeByKey provides a mock function with given fields: ctx, recipeKey
func (_m *MockRepository) GetCraftingRecipeByKey(ctx context.Context, recipeKey string) (*domain.Recipe, error) {
	ret := _m.Called(ctx, recipeKey)

	if len(ret) == 0 {
		panic("no return value specified for GetCraftingRecipeByKey")
	}

	var r0 *domain.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Recipe, error)); ok {
		return rf(ctx, recipeKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Recipe); ok {
		r0 = rf(ctx, recipeKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, recipeKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetCraftingRecipeByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCraftingRecipeByKey'
type MockRepository_GetCraftingRecipeByKey_Call struct {
	*mock.Call
}

// GetCraftingRecipeByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - recipeKey string
func (_e *MockRepository_Expecter) GetCraftingRecipeByKey(ctx interface{}, recipeKey interface{}) *MockRepository_GetCraftingRecipeByKey_Call {
	return &MockRepository_GetCraftingRecipeByKey_Call{Call: _e.mock.On("GetCraftingRecipeByKey", ctx, recipeKey)}
}

func (_c *MockRepository_GetCraftingRecipeByKey_Call) Run(run func(ctx context.Context, recipeKey string)) *MockRepository_GetCraftingRecipeByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetCraftingRecipeByKey_Call) Return(_a0 *domain.Recipe, _a1 error) *MockRepository_GetCraftingRecipeByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetCraftingRecipeByKey_Call) RunAndReturn(run func(context.Context, string) (*domain.Recipe, error)) *MockRepository_GetCraftingRecipeByKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetDisassembleRecipeByKey provides a mock function with given fields: ctx, recipeKey
func (_m *MockRepository) GetDisassembleRecipeByKey(ctx context.Context, recipeKey string) (*domain.DisassembleRecipe, error) {
	ret := _m.Called(ctx, recipeKey)

	if len(ret) == 0 {
		panic("no return value specified for GetDisassembleRecipeByKey")
	}

	var r0 *domain.DisassembleRecipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.DisassembleRecipe, error)); ok {
		return rf(ctx, recipeKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.DisassembleRecipe); ok {
		r0 = rf(ctx, recipeKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DisassembleRecipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, recipeKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetDisassembleRecipeByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDisassembleRecipeByKey'
type MockRepository_GetDisassembleRecipeByKey_Call struct {
	*mock.Call
}

// GetDisassembleRecipeByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - recipeKey string
func (_e *MockRepository_Expecter) GetDisassembleRecipeByKey(ctx interface{}, recipeKey interface{}) *MockRepository_GetDisassembleRecipeByKey_Call {
	return &MockRepository_GetDisassembleRecipeByKey_Call{Call: _e.mock.On("GetDisassembleRecipeByKey", ctx, recipeKey)}
}

func (_c *MockRepository_GetDisassembleRecipeByKey_Call) Run(run func(ctx context.Context, recipeKey string)) *MockRepository_GetDisassembleRecipeByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetDisassembleRecipeByKey_Call) Return(_a0 *domain.DisassembleRecipe, _a1 error) *MockRepository_GetDisassembleRecipeByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetDisassembleRecipeByKey_Call) RunAndReturn(run func(context.Context, string) (*domain.DisassembleRecipe, error)) *MockRepository_GetDisassembleRecipeByKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetDisassembleRecipeBySourceItemID provides a mock function with given fields: ctx, itemID
func (_m *MockRepository) GetDisassembleRecipeBySourceItemID(ctx context.Context, itemID int) (*domain.DisassembleRecipe, error) {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetDisassembleRecipeBySourceItemID")
	}

	var r0 *domain.DisassembleRecipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.DisassembleRecipe, error)); ok {
		return rf(ctx, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.DisassembleRecipe); ok {
		r0 = rf(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DisassembleRecipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetDisassembleRecipeBySourceItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDisassembleRecipeBySourceItemID'
type MockRepository_GetDisassembleRecipeBySourceItemID_Call struct {
	*mock.Call
}

// GetDisassembleRecipeBySourceItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID int
func (_e *MockRepository_Expecter) GetDisassembleRecipeBySourceItemID(ctx interface{}, itemID interface{}) *MockRepository_GetDisassembleRecipeBySourceItemID_Call {
	return &MockRepository_GetDisassembleRecipeBySourceItemID_Call{Call: _e.mock.On("GetDisassembleRecipeBySourceItemID", ctx, itemID)}
}

func (_c *MockRepository_GetDisassembleRecipeBySourceItemID_Call) Run(run func(ctx context.Context, itemID int)) *MockRepository_GetDisassembleRecipeBySourceItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_GetDisassembleRecipeBySourceItemID_Call) Return(_a0 *domain.DisassembleRecipe, _a1 error) *MockRepository_GetDisassembleRecipeBySourceItemID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetDisassembleRecipeBySourceItemID_Call) RunAndReturn(run func(context.Context, int) (*domain.DisassembleRecipe, error)) *MockRepository_GetDisassembleRecipeBySourceItemID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInventory provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetInventory(ctx context.Context, userID string) (*domain.Inventory, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 *domain.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Inventory, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Inventory); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventory'
type MockRepository_GetInventory_Call struct {
	*mock.Call
}

// GetInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetInventory(ctx interface{}, userID interface{}) *MockRepository_GetInventory_Call {
	return &MockRepository_GetInventory_Call{Call: _e.mock.On("GetInventory", ctx, userID)}
}

func (_c *MockRepository_GetInventory_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetInventory_Call) Return(_a0 *domain.Inventory, _a1 error) *MockRepository_GetInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetInventory_Call) RunAndReturn(run func(context.Context, string) (*domain.Inventory, error)) *MockRepository_GetInventory_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetItemByID(ctx context.Context, id int) (*domain.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByID'
type MockRepository_GetItemByID_Call struct {
	*mock.Call
}

// GetItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) GetItemByID(ctx interface{}, id interface{}) *MockRepository_GetItemByID_Call {
	return &MockRepository_GetItemByID_Call{Call: _e.mock.On("GetItemByID", ctx, id)}
}

func (_c *MockRepository_GetItemByID_Call) Run(run func(ctx context.Context, id int)) *MockRepository_GetItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_GetItemByID_Call) Return(_a0 *domain.Item, _a1 error) *MockRepository_GetItemByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetItemByID_Call) RunAndReturn(run func(context.Context, int) (*domain.Item, error)) *MockRepository_GetItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByName provides a mock function with given fields: ctx, itemName
func (_m *MockRepository) GetItemByName(ctx context.Context, itemName string) (*domain.Item, error) {
	ret := _m.Called(ctx, itemName)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByName")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Item, error)); ok {
		return rf(ctx, itemName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Item); ok {
		r0 = rf(ctx, itemName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, itemName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetItemByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByName'
type MockRepository_GetItemByName_Call struct {
	*mock.Call
}

// GetItemByName is a helper method to define mock.On call
//   - ctx context.Context
//   - itemName string
func (_e *MockRepository_Expecter) GetItemByName(ctx interface{}, itemName interface{}) *MockRepository_GetItemByName_Call {
	return &MockRepository_GetItemByName_Call{Call: _e.mock.On("GetItemByName", ctx, itemName)}
}

func (_c *MockRepository_GetItemByName_Call) Run(run func(ctx context.Context, itemName string)) *MockRepository_GetItemByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetItemByName_Call) Return(_a0 *domain.Item, _a1 error) *MockRepository_GetItemByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetItemByName_Call) RunAndReturn(run func(context.Context, string) (*domain.Item, error)) *MockRepository_GetItemByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemsByIDs provides a mock function with given fields: ctx, itemIDs
func (_m *MockRepository) GetItemsByIDs(ctx context.Context, itemIDs []int) ([]domain.Item, error) {
	ret := _m.Called(ctx, itemIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetItemsByIDs")
	}

	var r0 []domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) ([]domain.Item, error)); ok {
		return rf(ctx, itemIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int) []domain.Item); ok {
		r0 = rf(ctx, itemIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, itemIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetItemsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemsByIDs'
type MockRepository_GetItemsByIDs_Call struct {
	*mock.Call
}

// GetItemsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - itemIDs []int
func (_e *MockRepository_Expecter) GetItemsByIDs(ctx interface{}, itemIDs interface{}) *MockRepository_GetItemsByIDs_Call {
	return &MockRepository_GetItemsByIDs_Call{Call: _e.mock.On("GetItemsByIDs", ctx, itemIDs)}
}

func (_c *MockRepository_GetItemsByIDs_Call) Run(run func(ctx context.Context, itemIDs []int)) *MockRepository_GetItemsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int))
	})
	return _c
}

func (_c *MockRepository_GetItemsByIDs_Call) Return(_a0 []domain.Item, _a1 error) *MockRepository_GetItemsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetItemsByIDs_Call) RunAndReturn(run func(context.Context, []int) ([]domain.Item, error)) *MockRepository_GetItemsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecipeByTargetItemID provides a mock function with given fields: ctx, itemID
func (_m *MockRepository) GetRecipeByTargetItemID(ctx context.Context, itemID int) (*domain.Recipe, error) {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipeByTargetItemID")
	}

	var r0 *domain.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Recipe, error)); ok {
		return rf(ctx, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Recipe); ok {
		r0 = rf(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetRecipeByTargetItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecipeByTargetItemID'
type MockRepository_GetRecipeByTargetItemID_Call struct {
	*mock.Call
}

// GetRecipeByTargetItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID int
func (_e *MockRepository_Expecter) GetRecipeByTargetItemID(ctx interface{}, itemID interface{}) *MockRepository_GetRecipeByTargetItemID_Call {
	return &MockRepository_GetRecipeByTargetItemID_Call{Call: _e.mock.On("GetRecipeByTargetItemID", ctx, itemID)}
}

func (_c *MockRepository_GetRecipeByTargetItemID_Call) Run(run func(ctx context.Context, itemID int)) *MockRepository_GetRecipeByTargetItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_GetRecipeByTargetItemID_Call) Return(_a0 *domain.Recipe, _a1 error) *MockRepository_GetRecipeByTargetItemID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetRecipeByTargetItemID_Call) RunAndReturn(run func(context.Context, int) (*domain.Recipe, error)) *MockRepository_GetRecipeByTargetItemID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnlockedRecipesForUser provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetUnlockedRecipesForUser(ctx context.Context, userID string) ([]repository.UnlockedRecipeInfo, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnlockedRecipesForUser")
	}

	var r0 []repository.UnlockedRecipeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]repository.UnlockedRecipeInfo, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []repository.UnlockedRecipeInfo); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.UnlockedRecipeInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUnlockedRecipesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnlockedRecipesForUser'
type MockRepository_GetUnlockedRecipesForUser_Call struct {
	*mock.Call
}

// GetUnlockedRecipesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetUnlockedRecipesForUser(ctx interface{}, userID interface{}) *MockRepository_GetUnlockedRecipesForUser_Call {
	return &MockRepository_GetUnlockedRecipesForUser_Call{Call: _e.mock.On("GetUnlockedRecipesForUser", ctx, userID)}
}

func (_c *MockRepository_GetUnlockedRecipesForUser_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetUnlockedRecipesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUnlockedRecipesForUser_Call) Return(_a0 []repository.UnlockedRecipeInfo, _a1 error) *MockRepository_GetUnlockedRecipesForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUnlockedRecipesForUser_Call) RunAndReturn(run func(context.Context, string) ([]repository.UnlockedRecipeInfo, error)) *MockRepository_GetUnlockedRecipesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByPlatformID provides a mock function with given fields: ctx, platform, platformID
func (_m *MockRepository) GetUserByPlatformID(ctx context.Context, platform string, platformID string) (*domain.User, error) {
	ret := _m.Called(ctx, platform, platformID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByPlatformID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, platform, platformID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, platform, platformID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platform, platformID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByPlatformID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPlatformID'
type MockRepository_GetUserByPlatformID_Call struct {
	*mock.Call
}

// GetUserByPlatformID is a helper method to define mock.On call
//   - ctx context.Context
//   - platform string
//   - platformID string
func (_e *MockRepository_Expecter) GetUserByPlatformID(ctx interface{}, platform interface{}, platformID interface{}) *MockRepository_GetUserByPlatformID_Call {
	return &MockRepository_GetUserByPlatformID_Call{Call: _e.mock.On("GetUserByPlatformID", ctx, platform, platformID)}
}

func (_c *MockRepository_GetUserByPlatformID_Call) Run(run func(ctx context.Context, platform string, platformID string)) *MockRepository_GetUserByPlatformID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserByPlatformID_Call) Return(_a0 *domain.User, _a1 error) *MockRepository_GetUserByPlatformID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByPlatformID_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockRepository_GetUserByPlatformID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertCraftingRecipe provides a mock function with given fields: ctx, recipe
func (_m *MockRepository) InsertCraftingRecipe(ctx context.Context, recipe *domain.Recipe) (int, error) {
	ret := _m.Called(ctx, recipe)

	if len(ret) == 0 {
		panic("no return value specified for InsertCraftingRecipe")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Recipe) (int, error)); ok {
		return rf(ctx, recipe)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Recipe) int); ok {
		r0 = rf(ctx, recipe)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Recipe) error); ok {
		r1 = rf(ctx, recipe)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_InsertCraftingRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertCraftingRecipe'
type MockRepository_InsertCraftingRecipe_Call struct {
	*mock.Call
}

// InsertCraftingRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - recipe *domain.Recipe
func (_e *MockRepository_Expecter) InsertCraftingRecipe(ctx interface{}, recipe interface{}) *MockRepository_InsertCraftingRecipe_Call {
	return &MockRepository_InsertCraftingRecipe_Call{Call: _e.mock.On("InsertCraftingRecipe", ctx, recipe)}
}

func (_c *MockRepository_InsertCraftingRecipe_Call) Run(run func(ctx context.Context, recipe *domain.Recipe)) *MockRepository_InsertCraftingRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Recipe))
	})
	return _c
}

func (_c *MockRepository_InsertCraftingRecipe_Call) Return(_a0 int, _a1 error) *MockRepository_InsertCraftingRecipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_InsertCraftingRecipe_Call) RunAndReturn(run func(context.Context, *domain.Recipe) (int, error)) *MockRepository_InsertCraftingRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// InsertDisassembleOutput provides a mock function with given fields: ctx, recipeID, output
func (_m *MockRepository) InsertDisassembleOutput(ctx context.Context, recipeID int, output domain.RecipeOutput) error {
	ret := _m.Called(ctx, recipeID, output)

	if len(ret) == 0 {
		panic("no return value specified for InsertDisassembleOutput")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.RecipeOutput) error); ok {
		r0 = rf(ctx, recipeID, output)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_InsertDisassembleOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertDisassembleOutput'
type MockRepository_InsertDisassembleOutput_Call struct {
	*mock.Call
}

// InsertDisassembleOutput is a helper method to define mock.On call
//   - ctx context.Context
//   - recipeID int
//   - output domain.RecipeOutput
func (_e *MockRepository_Expecter) InsertDisassembleOutput(ctx interface{}, recipeID interface{}, output interface{}) *MockRepository_InsertDisassembleOutput_Call {
	return &MockRepository_InsertDisassembleOutput_Call{Call: _e.mock.On("InsertDisassembleOutput", ctx, recipeID, output)}
}

func (_c *MockRepository_InsertDisassembleOutput_Call) Run(run func(ctx context.Context, recipeID int, output domain.RecipeOutput)) *MockRepository_InsertDisassembleOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(domain.RecipeOutput))
	})
	return _c
}

func (_c *MockRepository_InsertDisassembleOutput_Call) Return(_a0 error) *MockRepository_InsertDisassembleOutput_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_InsertDisassembleOutput_Call) RunAndReturn(run func(context.Context, int, domain.RecipeOutput) error) *MockRepository_InsertDisassembleOutput_Call {
	_c.Call.Return(run)
	return _c
}

// InsertDisassembleRecipe provides a mock function with given fields: ctx, recipe
func (_m *MockRepository) InsertDisassembleRecipe(ctx context.Context, recipe *domain.DisassembleRecipe) (int, error) {
	ret := _m.Called(ctx, recipe)

	if len(ret) == 0 {
		panic("no return value specified for InsertDisassembleRecipe")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DisassembleRecipe) (int, error)); ok {
		return rf(ctx, recipe)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DisassembleRecipe) int); ok {
		r0 = rf(ctx, recipe)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.DisassembleRecipe) error); ok {
		r1 = rf(ctx, recipe)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_InsertDisassembleRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertDisassembleRecipe'
type MockRepository_InsertDisassembleRecipe_Call struct {
	*mock.Call
}

// InsertDisassembleRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - recipe *domain.DisassembleRecipe
func (_e *MockRepository_Expecter) InsertDisassembleRecipe(ctx interface{}, recipe interface{}) *MockRepository_InsertDisassembleRecipe_Call {
	return &MockRepository_InsertDisassembleRecipe_Call{Call: _e.mock.On("InsertDisassembleRecipe", ctx, recipe)}
}

func (_c *MockRepository_InsertDisassembleRecipe_Call) Run(run func(ctx context.Context, recipe *domain.DisassembleRecipe)) *MockRepository_InsertDisassembleRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.DisassembleRecipe))
	})
	return _c
}

func (_c *MockRepository_InsertDisassembleRecipe_Call) Return(_a0 int, _a1 error) *MockRepository_InsertDisassembleRecipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_InsertDisassembleRecipe_Call) RunAndReturn(run func(context.Context, *domain.DisassembleRecipe) (int, error)) *MockRepository_InsertDisassembleRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// IsRecipeUnlocked provides a mock function with given fields: ctx, userID, recipeID
func (_m *MockRepository) IsRecipeUnlocked(ctx context.Context, userID string, recipeID int) (bool, error) {
	ret := _m.Called(ctx, userID, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for IsRecipeUnlocked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (bool, error)); ok {
		return rf(ctx, userID, recipeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) bool); ok {
		r0 = rf(ctx, userID, recipeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, recipeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_IsRecipeUnlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRecipeUnlocked'
type MockRepository_IsRecipeUnlocked_Call struct {
	*mock.Call
}

// IsRecipeUnlocked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - recipeID int
func (_e *MockRepository_Expecter) IsRecipeUnlocked(ctx interface{}, userID interface{}, recipeID interface{}) *MockRepository_IsRecipeUnlocked_Call {
	return &MockRepository_IsRecipeUnlocked_Call{Call: _e.mock.On("IsRecipeUnlocked", ctx, userID, recipeID)}
}

func (_c *MockRepository_IsRecipeUnlocked_Call) Run(run func(ctx context.Context, userID string, recipeID int)) *MockRepository_IsRecipeUnlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_IsRecipeUnlocked_Call) Return(_a0 bool, _a1 error) *MockRepository_IsRecipeUnlocked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_IsRecipeUnlocked_Call) RunAndReturn(run func(context.Context, string, int) (bool, error)) *MockRepository_IsRecipeUnlocked_Call {
	_c.Call.Return(run)
	return _c
}

// UnlockRecipe provides a mock function with given fields: ctx, userID, recipeID
func (_m *MockRepository) UnlockRecipe(ctx context.Context, userID string, recipeID int) error {
	ret := _m.Called(ctx, userID, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for UnlockRecipe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, userID, recipeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UnlockRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlockRecipe'
type MockRepository_UnlockRecipe_Call struct {
	*mock.Call
}

// UnlockRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - recipeID int
func (_e *MockRepository_Expecter) UnlockRecipe(ctx interface{}, userID interface{}, recipeID interface{}) *MockRepository_UnlockRecipe_Call {
	return &MockRepository_UnlockRecipe_Call{Call: _e.mock.On("UnlockRecipe", ctx, userID, recipeID)}
}

func (_c *MockRepository_UnlockRecipe_Call) Run(run func(ctx context.Context, userID string, recipeID int)) *MockRepository_UnlockRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_UnlockRecipe_Call) Return(_a0 error) *MockRepository_UnlockRecipe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UnlockRecipe_Call) RunAndReturn(run func(context.Context, string, int) error) *MockRepository_UnlockRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCraftingRecipe provides a mock function with given fields: ctx, recipeID, recipe
func (_m *MockRepository) UpdateCraftingRecipe(ctx context.Context, recipeID int, recipe *domain.Recipe) error {
	ret := _m.Called(ctx, recipeID, recipe)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCraftingRecipe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Recipe) error); ok {
		r0 = rf(ctx, recipeID, recipe)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateCraftingRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCraftingRecipe'
type MockRepository_UpdateCraftingRecipe_Call struct {
	*mock.Call
}

// UpdateCraftingRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - recipeID int
//   - recipe *domain.Recipe
func (_e *MockRepository_Expecter) UpdateCraftingRecipe(ctx interface{}, recipeID interface{}, recipe interface{}) *MockRepository_UpdateCraftingRecipe_Call {
	return &MockRepository_UpdateCraftingRecipe_Call{Call: _e.mock.On("UpdateCraftingRecipe", ctx, recipeID, recipe)}
}

func (_c *MockRepository_UpdateCraftingRecipe_Call) Run(run func(ctx context.Context, recipeID int, recipe *domain.Recipe)) *MockRepository_UpdateCraftingRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Recipe))
	})
	return _c
}

func (_c *MockRepository_UpdateCraftingRecipe_Call) Return(_a0 error) *MockRepository_UpdateCraftingRecipe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateCraftingRecipe_Call) RunAndReturn(run func(context.Context, int, *domain.Recipe) error) *MockRepository_UpdateCraftingRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDisassembleRecipe provides a mock function with given fields: ctx, recipeID, recipe
func (_m *MockRepository) UpdateDisassembleRecipe(ctx context.Context, recipeID int, recipe *domain.DisassembleRecipe) error {
	ret := _m.Called(ctx, recipeID, recipe)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDisassembleRecipe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.DisassembleRecipe) error); ok {
		r0 = rf(ctx, recipeID, recipe)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateDisassembleRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDisassembleRecipe'
type MockRepository_UpdateDisassembleRecipe_Call struct {
	*mock.Call
}

// UpdateDisassembleRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - recipeID int
//   - recipe *domain.DisassembleRecipe
func (_e *MockRepository_Expecter) UpdateDisassembleRecipe(ctx interface{}, recipeID interface{}, recipe interface{}) *MockRepository_UpdateDisassembleRecipe_Call {
	return &MockRepository_UpdateDisassembleRecipe_Call{Call: _e.mock.On("UpdateDisassembleRecipe", ctx, recipeID, recipe)}
}

func (_c *MockRepository_UpdateDisassembleRecipe_Call) Run(run func(ctx context.Context, recipeID int, recipe *domain.DisassembleRecipe)) *MockRepository_UpdateDisassembleRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.DisassembleRecipe))
	})
	return _c
}

func (_c *MockRepository_UpdateDisassembleRecipe_Call) Return(_a0 error) *MockRepository_UpdateDisassembleRecipe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateDisassembleRecipe_Call) RunAndReturn(run func(context.Context, int, *domain.DisassembleRecipe) error) *MockRepository_UpdateDisassembleRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInventory provides a mock function with given fields: ctx, userID, inventory
func (_m *MockRepository) UpdateInventory(ctx context.Context, userID string, inventory domain.Inventory) error {
	ret := _m.Called(ctx, userID, inventory)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Inventory) error); ok {
		r0 = rf(ctx, userID, inventory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInventory'
type MockRepository_UpdateInventory_Call struct {
	*mock.Call
}

// UpdateInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inventory domain.Inventory
func (_e *MockRepository_Expecter) UpdateInventory(ctx interface{}, userID interface{}, inventory interface{}) *MockRepository_UpdateInventory_Call {
	return &MockRepository_UpdateInventory_Call{Call: _e.mock.On("UpdateInventory", ctx, userID, inventory)}
}

func (_c *MockRepository_UpdateInventory_Call) Run(run func(ctx context.Context, userID string, inventory domain.Inventory)) *MockRepository_UpdateInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Inventory))
	})
	return _c
}

func (_c *MockRepository_UpdateInventory_Call) Return(_a0 error) *MockRepository_UpdateInventory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateInventory_Call) RunAndReturn(run func(context.Context, string, domain.Inventory) error) *MockRepository_UpdateInventory_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertRecipeAssociation provides a mock function with given fields: ctx, upgradeRecipeID, disassembleRecipeID
func (_m *MockRepository) UpsertRecipeAssociation(ctx context.Context, upgradeRecipeID int, disassembleRecipeID int) error {
	ret := _m.Called(ctx, upgradeRecipeID, disassembleRecipeID)

	if len(ret) == 0 {
		panic("no return value specified for UpsertRecipeAssociation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, upgradeRecipeID, disassembleRecipeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpsertRecipeAssociation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertRecipeAssociation'
type MockRepository_UpsertRecipeAssociation_Call struct {
	*mock.Call
}

// UpsertRecipeAssociation is a helper method to define mock.On call
//   - ctx context.Context
//   - upgradeRecipeID int
//   - disassembleRecipeID int
func (_e *MockRepository_Expecter) UpsertRecipeAssociation(ctx interface{}, upgradeRecipeID interface{}, disassembleRecipeID interface{}) *MockRepository_UpsertRecipeAssociation_Call {
	return &MockRepository_UpsertRecipeAssociation_Call{Call: _e.mock.On("UpsertRecipeAssociation", ctx, upgradeRecipeID, disassembleRecipeID)}
}

func (_c *MockRepository_UpsertRecipeAssociation_Call) Run(run func(ctx context.Context, upgradeRecipeID int, disassembleRecipeID int)) *MockRepository_UpsertRecipeAssociation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_UpsertRecipeAssociation_Call) Return(_a0 error) *MockRepository_UpsertRecipeAssociation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpsertRecipeAssociation_Call) RunAndReturn(run func(context.Context, int, int) error) *MockRepository_UpsertRecipeAssociation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
